-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-24 14:49:08 WET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE aula CASCADE CONSTRAINTS 
;

DROP TABLE avaliacao CASCADE CONSTRAINTS 
;

DROP TABLE curso CASCADE CONSTRAINTS 
;

DROP TABLE docente CASCADE CONSTRAINTS 
;

DROP TABLE entrega CASCADE CONSTRAINTS 
;

DROP TABLE estudante CASCADE CONSTRAINTS 
;

DROP TABLE estudante_entrega CASCADE CONSTRAINTS 
;

DROP TABLE ficheiro_entrega CASCADE CONSTRAINTS 
;

DROP TABLE ficheiro_recurso CASCADE CONSTRAINTS 
;

DROP TABLE inscricao CASCADE CONSTRAINTS 
;

DROP TABLE log CASCADE CONSTRAINTS 
;

DROP TABLE matricula CASCADE CONSTRAINTS 
;

DROP TABLE nota CASCADE CONSTRAINTS 
;

DROP TABLE parcela_propina CASCADE CONSTRAINTS 
;

DROP TABLE presenca CASCADE CONSTRAINTS 
;

DROP TABLE recurso CASCADE CONSTRAINTS 
;

DROP TABLE sala CASCADE CONSTRAINTS 
;

DROP TABLE tipo_aula CASCADE CONSTRAINTS 
;

DROP TABLE tipo_avaliacao CASCADE CONSTRAINTS 
;

DROP TABLE tipo_curso CASCADE CONSTRAINTS 
;

DROP TABLE turma CASCADE CONSTRAINTS 
;

DROP TABLE uc_curso CASCADE CONSTRAINTS 
;

DROP TABLE uc_docente CASCADE CONSTRAINTS 
;

DROP TABLE unidade_curricular CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE aula 
    ( 
     id           INTEGER  NOT NULL , 
     data         DATE  NOT NULL , 
     hora_inicio  DATE  NOT NULL , 
     hora_fim     DATE  NOT NULL , 
     sumario      VARCHAR2 (255 CHAR) , 
     tipo_aula_id INTEGER  NOT NULL , 
     sala_id      INTEGER  NOT NULL , 
     turma_id     INTEGER  NOT NULL , 
     created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status       CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE aula 
    ADD CONSTRAINT aula_PK PRIMARY KEY ( id ) ;

CREATE TABLE avaliacao 
    ( 
     id                INTEGER  NOT NULL , 
     titulo            VARCHAR2 (100 CHAR)  NOT NULL , 
     data              DATE  NOT NULL , 
     data_entrega      DATE  NOT NULL , 
     peso              NUMBER , 
     max_alunos        INTEGER  NOT NULL , 
     turma_id          INTEGER  NOT NULL , 
     tipo_avaliacao_id INTEGER  NOT NULL , 
     avaliacao_pai_id  INTEGER , 
     created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status            CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE avaliacao 
    ADD CONSTRAINT avaliacao_PK PRIMARY KEY ( id ) ;

CREATE TABLE curso 
    ( 
     id            INTEGER  NOT NULL , 
     nome          VARCHAR2 (100 CHAR)  NOT NULL , 
     codigo        VARCHAR2 (20 CHAR)  NOT NULL , 
     descricao     VARCHAR2 (255 CHAR)  NOT NULL , 
     duracao       INTEGER  NOT NULL , 
     ects          INTEGER  NOT NULL , 
     tipo_curso_id INTEGER  NOT NULL , 
     created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status        CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE curso 
    ADD CONSTRAINT curso_PK PRIMARY KEY ( id ) ;

CREATE TABLE docente 
    ( 
     id               INTEGER  NOT NULL , 
     nome             VARCHAR2 (100 CHAR)  NOT NULL , 
     data_contratacao DATE  NOT NULL , 
     nif              VARCHAR2 (9 CHAR)  NOT NULL , 
     iban             VARCHAR2 (25 CHAR) , 
     email            VARCHAR2 (255)  NOT NULL , 
     telemovel        VARCHAR2 (9 CHAR)  NOT NULL , 
     created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status           CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE docente 
    ADD CONSTRAINT docente_PK PRIMARY KEY ( id ) ;

CREATE TABLE entrega 
    ( 
     id           INTEGER  NOT NULL , 
     data_entrega DATE  NOT NULL , 
     avaliacao_id INTEGER  NOT NULL , 
     created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status       CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE entrega 
    ADD CONSTRAINT entrega_PK PRIMARY KEY ( id ) ;

CREATE TABLE estudante 
    ( 
     id              INTEGER  NOT NULL , 
     nome            VARCHAR2 (50 CHAR)  NOT NULL , 
     morada          VARCHAR2 (100 CHAR) , 
     data_nascimento DATE  NOT NULL , 
     cc              VARCHAR2 (8)  NOT NULL , 
     nif             VARCHAR2 (9)  NOT NULL , 
     iban            VARCHAR2 (25 CHAR) , 
     email           VARCHAR2 (255)  NOT NULL , 
     telemovel       VARCHAR2 (9 CHAR)  NOT NULL , 
     created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status          CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE estudante 
    ADD CONSTRAINT estudante_PK PRIMARY KEY ( id ) ;

CREATE TABLE estudante_entrega 
    ( 
     inscricao_id INTEGER  NOT NULL , 
     entrega_id   INTEGER  NOT NULL , 
     created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status       CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE estudante_entrega 
    ADD CONSTRAINT estudante_entrega_PK PRIMARY KEY ( entrega_id, inscricao_id ) ;

CREATE TABLE ficheiro_entrega 
    ( 
     id         INTEGER  NOT NULL , 
     entrega_id INTEGER  NOT NULL , 
     nome       VARCHAR2 (100 CHAR)  NOT NULL , 
     ficheiro   BLOB , 
     tamanho    INTEGER  NOT NULL , 
     tipo       VARCHAR2 (20 CHAR)  NOT NULL , 
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status     CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE ficheiro_entrega 
    ADD CONSTRAINT ficheiro_entrega_PK PRIMARY KEY ( id ) ;

CREATE TABLE ficheiro_recurso 
    ( 
     id         INTEGER  NOT NULL , 
     recurso_id INTEGER  NOT NULL , 
     nome       VARCHAR2 (100 CHAR)  NOT NULL , 
     ficheiro   BLOB , 
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status     CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE ficheiro_recurso 
    ADD CONSTRAINT ficheiro_recurso_PK PRIMARY KEY ( id ) ;

CREATE TABLE inscricao 
    ( 
     id                  INTEGER  NOT NULL , 
     turma_id            INTEGER  NOT NULL , 
     matricula_id        INTEGER  NOT NULL , 
     data                DATE  NOT NULL , 
     estado_inscricao_id INTEGER  NOT NULL , 
     created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status              CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE inscricao 
    ADD CONSTRAINT inscricao_PK PRIMARY KEY ( id ) ;

CREATE TABLE log 
    ( 
     id         INTEGER  NOT NULL , 
     acao       VARCHAR2 (100 CHAR)  NOT NULL , 
     tabela     VARCHAR2 (100 CHAR) , 
     data       CLOB , 
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL 
    ) 
;

ALTER TABLE log 
    ADD CONSTRAINT log_PK PRIMARY KEY ( id ) ;

CREATE TABLE matricula 
    ( 
     id                  INTEGER  NOT NULL , 
     curso_id            INTEGER  NOT NULL , 
     ano_inscricao       INTEGER  NOT NULL , 
     estado_matricula_id INTEGER  NOT NULL , 
     estudante_id        INTEGER  NOT NULL , 
     numero_parcelas     INTEGER  NOT NULL , 
     created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status              CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE matricula 
    ADD CONSTRAINT matricula_PK PRIMARY KEY ( id ) ;

CREATE TABLE nota 
    ( 
     inscricao_id INTEGER  NOT NULL , 
     avaliacao_id INTEGER  NOT NULL , 
     nota         NUMBER  NOT NULL , 
     comentario   VARCHAR2 (255 CHAR) , 
     created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status       CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE nota 
    ADD CONSTRAINT nota_PK PRIMARY KEY ( avaliacao_id, inscricao_id ) ;

CREATE TABLE parcela_propina 
    ( 
     id              INTEGER  NOT NULL , 
     valor           NUMBER  NOT NULL , 
     data_vencimento DATE  NOT NULL , 
     data_pagamento  DATE , 
     numero          INTEGER  NOT NULL , 
     estado          CHAR (1)  NOT NULL , 
     matricula_id    INTEGER  NOT NULL , 
     created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status          CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE parcela_propina 
    ADD CONSTRAINT parcela_propina_PK PRIMARY KEY ( id ) ;

CREATE TABLE presenca 
    ( 
     inscricao_id INTEGER  NOT NULL , 
     aula_id      INTEGER  NOT NULL , 
     presente     CHAR (1)  NOT NULL , 
     created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status       CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE presenca 
    ADD CONSTRAINT presenca_PK PRIMARY KEY ( aula_id, inscricao_id ) ;

CREATE TABLE recurso 
    ( 
     id         INTEGER  NOT NULL , 
     nome       VARCHAR2 (100 CHAR)  NOT NULL , 
     descricao  VARCHAR2 (255 CHAR) , 
     turma_id   INTEGER  NOT NULL , 
     docente_id INTEGER  NOT NULL , 
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status     CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE recurso 
    ADD CONSTRAINT recurso_PK PRIMARY KEY ( id ) ;

CREATE TABLE sala 
    ( 
     id         INTEGER  NOT NULL , 
     nome       VARCHAR2 (50 CHAR)  NOT NULL , 
     capacidade INTEGER  NOT NULL , 
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status     CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE sala 
    ADD CONSTRAINT sala_PK PRIMARY KEY ( id ) ;

CREATE TABLE tipo_aula 
    ( 
     id         INTEGER  NOT NULL , 
     nome       VARCHAR2 (50 CHAR)  NOT NULL , 
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status     CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE tipo_aula 
    ADD CONSTRAINT tipo_aula_PK PRIMARY KEY ( id ) ;

CREATE TABLE tipo_avaliacao 
    ( 
     id             INTEGER  NOT NULL , 
     nome           VARCHAR2 (50 CHAR)  NOT NULL , 
     descricao      VARCHAR2 (255 CHAR) , 
     requer_entrega CHAR (1)  NOT NULL , 
     permite_grupo  CHAR (1)  NOT NULL , 
     permite_filhos CHAR (1)  NOT NULL , 
     created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status         CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE tipo_avaliacao 
    ADD CONSTRAINT tipo_avaliacao_PK PRIMARY KEY ( id ) ;

CREATE TABLE tipo_curso 
    ( 
     id             INTEGER  NOT NULL , 
     nome           VARCHAR2 (50 CHAR)  NOT NULL , 
     valor_propinas NUMBER  NOT NULL , 
     created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status         CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE tipo_curso 
    ADD CONSTRAINT tipo_curso_PK PRIMARY KEY ( id ) ;

CREATE TABLE turma 
    ( 
     id                    INTEGER  NOT NULL , 
     nome                  VARCHAR2 (20 CHAR)  NOT NULL , 
     ano_letivo            VARCHAR2 (10 CHAR)  NOT NULL , 
     unidade_curricular_id INTEGER  NOT NULL , 
     turno_aulas_id        INTEGER  NOT NULL , 
     created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status                CHAR (1) DEFAULT '1'  NOT NULL , 
     docente_id            INTEGER  NOT NULL 
    ) 
;

ALTER TABLE turma 
    ADD CONSTRAINT turma_PK PRIMARY KEY ( id ) ;

CREATE TABLE uc_curso 
    ( 
     curso_id              INTEGER  NOT NULL , 
     unidade_curricular_id INTEGER  NOT NULL , 
     semestre              INTEGER  NOT NULL , 
     ano                   INTEGER  NOT NULL , 
     ects                  INTEGER  NOT NULL , 
     presenca_obrigatoria  CHAR (1)  NOT NULL , 
     percentagem_presenca  NUMBER , 
     created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status                CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE uc_curso 
    ADD CONSTRAINT unidade_curricular_curso_PK PRIMARY KEY ( curso_id, unidade_curricular_id ) ;

CREATE TABLE uc_docente 
    ( 
     unidade_curricular_id INTEGER  NOT NULL , 
     docente_id            INTEGER  NOT NULL , 
     created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status                CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE uc_docente 
    ADD CONSTRAINT unidade_curricular_docente_PK PRIMARY KEY ( unidade_curricular_id, docente_id ) ;

CREATE TABLE unidade_curricular 
    ( 
     id             INTEGER  NOT NULL , 
     nome           VARCHAR2 (100 CHAR)  NOT NULL , 
     codigo         VARCHAR2 (20 CHAR)  NOT NULL , 
     horas_teoricas INTEGER  NOT NULL , 
     horas_praticas INTEGER  NOT NULL , 
     created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL , 
     status         CHAR (1) DEFAULT '1'  NOT NULL 
    ) 
;

ALTER TABLE unidade_curricular 
    ADD CONSTRAINT unidade_curricular_PK PRIMARY KEY ( id ) ;

ALTER TABLE aula 
    ADD CONSTRAINT aula_sala_FK FOREIGN KEY 
    ( 
     sala_id
    ) 
    REFERENCES sala 
    ( 
     id
    ) 
;

ALTER TABLE aula 
    ADD CONSTRAINT aula_tipo_aula_FK FOREIGN KEY 
    ( 
     tipo_aula_id
    ) 
    REFERENCES tipo_aula 
    ( 
     id
    ) 
;

ALTER TABLE aula 
    ADD CONSTRAINT aula_turma_FK FOREIGN KEY 
    ( 
     turma_id
    ) 
    REFERENCES turma 
    ( 
     id
    ) 
;

ALTER TABLE avaliacao 
    ADD CONSTRAINT avaliacao_avaliacao_FK FOREIGN KEY 
    ( 
     avaliacao_pai_id
    ) 
    REFERENCES avaliacao 
    ( 
     id
    ) 
;

ALTER TABLE avaliacao 
    ADD CONSTRAINT avaliacao_tipo_avaliacao_FK FOREIGN KEY 
    ( 
     tipo_avaliacao_id
    ) 
    REFERENCES tipo_avaliacao 
    ( 
     id
    ) 
;

ALTER TABLE avaliacao 
    ADD CONSTRAINT avaliacao_turma_FK FOREIGN KEY 
    ( 
     turma_id
    ) 
    REFERENCES turma 
    ( 
     id
    ) 
;

ALTER TABLE curso 
    ADD CONSTRAINT curso_tipo_curso_FK FOREIGN KEY 
    ( 
     tipo_curso_id
    ) 
    REFERENCES tipo_curso 
    ( 
     id
    ) 
;

ALTER TABLE entrega 
    ADD CONSTRAINT entrega_avaliacao_FK FOREIGN KEY 
    ( 
     avaliacao_id
    ) 
    REFERENCES avaliacao 
    ( 
     id
    ) 
;

ALTER TABLE estudante_entrega 
    ADD CONSTRAINT estudante_entrega_entrega_FK FOREIGN KEY 
    ( 
     entrega_id
    ) 
    REFERENCES entrega 
    ( 
     id
    ) 
;

ALTER TABLE estudante_entrega 
    ADD CONSTRAINT estudante_entrega_inscricao_FK FOREIGN KEY 
    ( 
     inscricao_id
    ) 
    REFERENCES inscricao 
    ( 
     id
    ) 
;

ALTER TABLE ficheiro_entrega 
    ADD CONSTRAINT ficheiro_entrega_FK FOREIGN KEY 
    ( 
     entrega_id
    ) 
    REFERENCES entrega 
    ( 
     id
    ) 
;

ALTER TABLE ficheiro_recurso 
    ADD CONSTRAINT ficheiro_recurso_recurso_FK FOREIGN KEY 
    ( 
     recurso_id
    ) 
    REFERENCES recurso 
    ( 
     id
    ) 
;

ALTER TABLE matricula 
    ADD CONSTRAINT inscricao_curso_curso_FK FOREIGN KEY 
    ( 
     curso_id
    ) 
    REFERENCES curso 
    ( 
     id
    ) 
;

ALTER TABLE matricula 
    ADD CONSTRAINT inscricao_curso_estudante_FK FOREIGN KEY 
    ( 
     estudante_id
    ) 
    REFERENCES estudante 
    ( 
     id
    ) 
;

ALTER TABLE inscricao 
    ADD CONSTRAINT inscricao_turma_matricula_FK FOREIGN KEY 
    ( 
     matricula_id
    ) 
    REFERENCES matricula 
    ( 
     id
    ) 
;

ALTER TABLE inscricao 
    ADD CONSTRAINT inscricao_turma_turma_FK FOREIGN KEY 
    ( 
     turma_id
    ) 
    REFERENCES turma 
    ( 
     id
    ) 
;

ALTER TABLE nota 
    ADD CONSTRAINT nota_avaliacao_FK FOREIGN KEY 
    ( 
     avaliacao_id
    ) 
    REFERENCES avaliacao 
    ( 
     id
    ) 
;

ALTER TABLE nota 
    ADD CONSTRAINT nota_inscricao_FK FOREIGN KEY 
    ( 
     inscricao_id
    ) 
    REFERENCES inscricao 
    ( 
     id
    ) 
;

ALTER TABLE parcela_propina 
    ADD CONSTRAINT parcela_propina_matricula_FK FOREIGN KEY 
    ( 
     matricula_id
    ) 
    REFERENCES matricula 
    ( 
     id
    ) 
;

ALTER TABLE presenca 
    ADD CONSTRAINT presenca_aula_FK FOREIGN KEY 
    ( 
     aula_id
    ) 
    REFERENCES aula 
    ( 
     id
    ) 
;

ALTER TABLE presenca 
    ADD CONSTRAINT presenca_inscricao_FK FOREIGN KEY 
    ( 
     inscricao_id
    ) 
    REFERENCES inscricao 
    ( 
     id
    ) 
;

ALTER TABLE recurso 
    ADD CONSTRAINT recurso_docente_FK FOREIGN KEY 
    ( 
     docente_id
    ) 
    REFERENCES docente 
    ( 
     id
    ) 
;

ALTER TABLE recurso 
    ADD CONSTRAINT recurso_turma_FK FOREIGN KEY 
    ( 
     turma_id
    ) 
    REFERENCES turma 
    ( 
     id
    ) 
;

ALTER TABLE turma 
    ADD CONSTRAINT turma_docente_FK FOREIGN KEY 
    ( 
     docente_id
    ) 
    REFERENCES docente 
    ( 
     id
    ) 
;

ALTER TABLE turma 
    ADD CONSTRAINT turma_unidade_curricular_FK FOREIGN KEY 
    ( 
     unidade_curricular_id
    ) 
    REFERENCES unidade_curricular 
    ( 
     id
    ) 
;

ALTER TABLE uc_curso 
    ADD CONSTRAINT uc_curso_curso_FK FOREIGN KEY 
    ( 
     curso_id
    ) 
    REFERENCES curso 
    ( 
     id
    ) 
;

ALTER TABLE uc_curso 
    ADD CONSTRAINT uc_curso_uc_FK FOREIGN KEY 
    ( 
     unidade_curricular_id
    ) 
    REFERENCES unidade_curricular 
    ( 
     id
    ) 
;

ALTER TABLE uc_docente 
    ADD CONSTRAINT uc_docente_docente_FK FOREIGN KEY 
    ( 
     docente_id
    ) 
    REFERENCES docente 
    ( 
     id
    ) 
;

ALTER TABLE uc_docente 
    ADD CONSTRAINT uc_docente_uc_FK FOREIGN KEY 
    ( 
     unidade_curricular_id
    ) 
    REFERENCES unidade_curricular 
    ( 
     id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            24
-- CREATE INDEX                             0
-- ALTER TABLE                             53
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
