insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3003, 1, 1.45, 'In hac habitasse platea dictumst.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3004, 1, 6.74, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3005, 1, 12.11, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3006, 1, 14.29, 'Pellentesque viverra pede ac diam.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3007, 1, 17.05, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3008, 1, 6.76, 'Donec vitae nisi.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3009, 1, 15.66, 'Duis aliquam convallis nunc.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3010, 1, 19.51, 'Aenean fermentum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3011, 1, 4.48, 'Aenean auctor gravida sem.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3012, 1, 0.39, 'Vivamus vestibulum sagittis sapien.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3013, 1, 0.49, 'Mauris sit amet eros.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3014, 1, 12.38, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3015, 1, 5.33, 'Etiam faucibus cursus urna.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3016, 1, 7.48, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3017, 1, 17.03, 'Integer ac leo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3018, 1, 3.21, 'Suspendisse potenti.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3019, 1, 2.74, 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3020, 1, 17.41, 'Morbi non lectus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3021, 1, 15.71, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3022, 1, 1.44, 'Integer a nibh.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3023, 1, 18.33, 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3024, 1, 8.63, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3025, 1, 6.26, 'Curabitur gravida nisi at nibh.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3026, 1, 0.15, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3027, 1, 16.31, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3028, 1, 14.19, 'Nulla ut erat id mauris vulputate elementum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3029, 1, 15.29, 'Nulla nisl.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3030, 1, 16.21, 'Mauris sit amet eros.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3031, 1, 12.29, 'Nunc rhoncus dui vel sem.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3032, 1, 17.35, 'Donec quis orci eget orci vehicula condimentum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3033, 2, 15.87, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3034, 2, 11.87, 'In blandit ultrices enim.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3035, 2, 15.52, 'Praesent blandit lacinia erat.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3036, 2, 17.36, 'Nam dui.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3037, 2, 11.67, 'Morbi vel lectus in quam fringilla rhoncus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3038, 2, 8.78, 'Etiam faucibus cursus urna.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3039, 2, 4.28, 'Aenean sit amet justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3040, 2, 16.35, 'Sed ante.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3041, 2, 14.39, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3042, 2, 6.41, 'Fusce consequat.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3043, 2, 15.7, 'Morbi a ipsum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3044, 2, 3.19, 'In blandit ultrices enim.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3045, 2, 4.53, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3046, 2, 13.04, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3047, 2, 2.74, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3048, 2, 7.33, 'Integer tincidunt ante vel ipsum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3049, 2, 13.13, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3050, 2, 12.47, 'Sed ante.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3051, 2, 5.92, 'Sed ante.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3052, 2, 18.16, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3053, 2, 2.17, 'Ut at dolor quis odio consequat varius.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3054, 2, 10.87, 'Maecenas ut massa quis augue luctus tincidunt.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3055, 2, 10.22, 'In congue.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3056, 2, 7.07, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3057, 2, 6.89, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3058, 2, 6.94, 'Donec dapibus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3059, 2, 4.86, 'Nullam porttitor lacus at turpis.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3060, 2, 15.31, 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3061, 2, 12.28, 'Integer non velit.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3062, 2, 4.49, 'Praesent blandit lacinia erat.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3063, 3, 14.66, 'Donec posuere metus vitae ipsum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3064, 3, 4.55, 'Duis aliquam convallis nunc.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3065, 3, 4.04, 'Integer tincidunt ante vel ipsum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3066, 3, 8.47, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3067, 3, 16.77, 'Suspendisse potenti.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3068, 3, 2.14, 'Aenean lectus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3069, 3, 18.45, 'Vestibulum rutrum rutrum neque.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3070, 3, 12.15, 'In hac habitasse platea dictumst.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3071, 3, 2.09, 'Nam tristique tortor eu pede.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3072, 3, 7.14, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3073, 3, 14.22, 'Ut at dolor quis odio consequat varius.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3074, 3, 16.67, 'Nulla justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3075, 3, 6.91, 'Vivamus vestibulum sagittis sapien.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3076, 3, 2.54, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3077, 3, 11.09, 'Phasellus in felis.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3078, 3, 15.64, 'Pellentesque ultrices mattis odio.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3079, 3, 17.11, 'Praesent blandit lacinia erat.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3080, 3, 8.37, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3081, 3, 18.57, 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3082, 3, 3.35, 'Cras pellentesque volutpat dui.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3083, 3, 16.13, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3084, 3, 10.24, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3085, 3, 16.73, 'Integer ac leo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3086, 3, 14.85, 'Vestibulum rutrum rutrum neque.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3087, 3, 7.2, 'Vivamus vestibulum sagittis sapien.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3088, 3, 0.75, 'Proin eu mi.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3089, 3, 12.69, 'Donec vitae nisi.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3090, 3, 2.38, 'Donec ut dolor.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3091, 3, 5.55, 'Nulla justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3092, 3, 17.68, 'Mauris ullamcorper purus sit amet nulla.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3093, 4, 3.15, 'Morbi a ipsum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3094, 4, 8.52, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3095, 4, 7.94, 'Duis mattis egestas metus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3096, 4, 16.13, 'Nullam varius.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3097, 4, 19.54, 'Pellentesque viverra pede ac diam.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3098, 4, 3.35, 'Sed vel enim sit amet nunc viverra dapibus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3099, 4, 12.13, 'Proin at turpis a pede posuere nonummy.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3100, 4, 12.3, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3101, 4, 3.53, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3102, 4, 3.22, 'Morbi non lectus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3103, 4, 4.94, 'Etiam justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3104, 4, 3.18, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3105, 4, 11.57, 'Vestibulum sed magna at nunc commodo placerat.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3106, 4, 0.09, 'Proin eu mi.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3107, 4, 13.5, 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3108, 4, 16.74, 'Nulla tempus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3109, 4, 7.44, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3110, 4, 1.83, 'Nunc purus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3111, 4, 13.21, 'Nulla facilisi.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3112, 4, 2.31, 'Integer tincidunt ante vel ipsum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3113, 4, 11.06, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3114, 4, 4.55, 'Integer a nibh.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3115, 4, 9.07, 'Aenean sit amet justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3116, 4, 4.03, 'Morbi a ipsum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3117, 4, 3.64, 'Integer ac leo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3118, 4, 17.86, 'Pellentesque at nulla.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3119, 4, 5.41, 'Duis aliquam convallis nunc.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3120, 4, 4.04, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3121, 4, 4.29, 'Mauris sit amet eros.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3122, 4, 1.62, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3123, 5, 9.82, 'Vestibulum rutrum rutrum neque.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3124, 5, 15.58, 'In sagittis dui vel nisl.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3125, 5, 13.15, 'Nunc rhoncus dui vel sem.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3126, 5, 13.9, 'Donec vitae nisi.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3127, 5, 15.74, 'Aenean sit amet justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3128, 5, 0.39, 'In hac habitasse platea dictumst.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3129, 5, 17.17, 'Donec ut dolor.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3130, 5, 14.04, 'Pellentesque eget nunc.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3131, 5, 0.06, 'Cras non velit nec nisi vulputate nonummy.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3132, 5, 1.74, 'Curabitur convallis.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3133, 5, 12.25, 'Nulla tempus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3134, 5, 4.23, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3135, 5, 10.42, 'Suspendisse accumsan tortor quis turpis.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3136, 5, 11.68, 'In quis justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3137, 5, 6.58, 'Etiam faucibus cursus urna.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3138, 5, 2.19, 'Nulla ac enim.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3139, 5, 3.19, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3140, 5, 1.01, 'In congue.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3141, 5, 7.99, 'Phasellus in felis.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3142, 5, 12.19, 'Pellentesque eget nunc.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3143, 5, 1.0, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3144, 5, 5.92, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3145, 5, 14.8, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3146, 5, 12.9, 'In quis justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3147, 5, 19.73, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3148, 5, 16.8, 'Integer tincidunt ante vel ipsum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3149, 5, 19.06, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3150, 5, 9.64, 'Etiam justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3151, 5, 1.77, 'Duis consequat dui nec nisi volutpat eleifend.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3152, 5, 17.94, 'Nulla mollis molestie lorem.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3153, 6, 18.15, 'Fusce posuere felis sed lacus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3154, 6, 8.99, 'Donec ut mauris eget massa tempor convallis.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3155, 6, 12.39, 'Quisque ut erat.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3156, 6, 19.21, 'Integer ac neque.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3157, 6, 19.34, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3158, 6, 14.34, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3159, 6, 7.42, 'In congue.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3160, 6, 13.93, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3161, 6, 5.96, 'Phasellus id sapien in sapien iaculis congue.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3162, 6, 4.22, 'Maecenas ut massa quis augue luctus tincidunt.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3163, 6, 17.08, 'Curabitur in libero ut massa volutpat convallis.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3164, 6, 12.56, 'Morbi porttitor lorem id ligula.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3165, 6, 3.3, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3166, 6, 12.85, 'Nulla justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3167, 6, 3.0, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3168, 6, 3.64, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3169, 6, 3.85, 'Morbi ut odio.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3170, 6, 18.92, 'Morbi vel lectus in quam fringilla rhoncus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3171, 6, 3.95, 'Aenean fermentum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3172, 6, 2.46, 'Praesent id massa id nisl venenatis lacinia.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3173, 6, 17.9, 'In eleifend quam a odio.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3174, 6, 8.54, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3175, 6, 5.79, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3176, 6, 9.76, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3177, 6, 14.38, 'Nulla facilisi.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3178, 6, 8.42, 'Pellentesque viverra pede ac diam.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3179, 6, 19.99, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3180, 6, 17.16, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3181, 6, 7.07, 'Morbi vel lectus in quam fringilla rhoncus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3182, 6, 3.98, 'Vestibulum sed magna at nunc commodo placerat.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3183, 7, 19.13, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3184, 7, 4.52, 'Suspendisse potenti.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3185, 7, 11.29, 'Nullam molestie nibh in lectus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3186, 7, 3.06, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3187, 7, 12.44, 'Maecenas ut massa quis augue luctus tincidunt.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3188, 7, 5.2, 'In quis justo.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3189, 7, 5.34, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3190, 7, 12.6, 'Mauris sit amet eros.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3191, 7, 14.43, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3192, 7, 4.44, 'Duis mattis egestas metus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3193, 7, 4.58, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3194, 7, 0.93, 'Ut at dolor quis odio consequat varius.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3195, 7, 11.19, 'Morbi non lectus.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3196, 7, 8.18, 'Vivamus tortor.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3197, 7, 11.03, 'Vestibulum sed magna at nunc commodo placerat.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3198, 7, 1.28, 'Curabitur convallis.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3199, 7, 13.78, 'Praesent blandit lacinia erat.');
insert into nota (inscricao_id, avaliacao_id, nota, comentario) values (3200, 7, 13.79, 'Praesent blandit lacinia erat.');

