insert into recurso (id, nome, descricao, turma_id, docente_id) values (1, 'accumsan', 'In congue.', 1, 1);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (2, 'amet', 'Aenean fermentum.', 1, 1);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (3, 'at', 'Nulla ac enim.', 1, 1);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (4, 'a', 'Vestibulum sed magna at nunc commodo placerat.', 1, 1);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (5, 'sapien', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 2, 1);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (6, 'accumsan', 'Proin risus.', 2, 1);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (7, 'nec', 'Duis at velit eu est congue elementum.', 2, 2);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (8, 'dolor', 'In eleifend quam a odio.', 2, 2);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (9, 'id', 'Integer tincidunt ante vel ipsum.', 3, 2);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (10, 'justo', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 3, 2);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (11, 'duis', 'Nunc nisl.', 3, 2);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (12, 'etiam', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 3, 2);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (13, 'morbi', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 4, 3);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (14, 'neque', 'Morbi vel lectus in quam fringilla rhoncus.', 4, 3);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (15, 'donec', 'Morbi non quam nec dui luctus rutrum.', 4, 3);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (16, 'duis', 'Sed sagittis.', 4, 3);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (17, 'ac', 'Vivamus vestibulum sagittis sapien.', 5, 3);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (18, 'blandit', 'Mauris lacinia sapien quis libero.', 5, 3);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (19, 'dui', 'Morbi non lectus.', 5, 4);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (20, 'sit', 'Donec semper sapien a libero.', 5, 4);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (21, 'venenatis', 'Nulla nisl.', 6, 4);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (22, 'tempus', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 6, 4);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (23, 'id', 'Morbi non quam nec dui luctus rutrum.', 6, 4);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (24, 'odio', 'Curabitur in libero ut massa volutpat convallis.', 6, 4);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (25, 'ipsum', 'Pellentesque ultrices mattis odio.', 7, 5);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (26, 'tempus', 'Etiam vel augue.', 7, 5);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (27, 'non', 'Nulla nisl.', 7, 5);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (28, 'tristique', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 7, 5);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (29, 'eu', 'Integer non velit.', 8, 5);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (30, 'suspendisse', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 8, 5);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (31, 'nulla', 'Pellentesque at nulla.', 8, 6);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (32, 'massa', 'Quisque id justo sit amet sapien dignissim vestibulum.', 8, 6);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (33, 'amet', 'Vivamus vel nulla eget eros elementum pellentesque.', 9, 6);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (34, 'aliquet', 'Maecenas ut massa quis augue luctus tincidunt.', 9, 6);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (35, 'vivamus', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 9, 6);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (36, 'id', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 9, 6);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (37, 'posuere', 'Nam dui.', 10, 7);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (38, 'at', 'Proin at turpis a pede posuere nonummy.', 10, 7);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (39, 'lobortis', 'Nullam varius.', 10, 7);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (40, 'aliquam', 'Duis consequat dui nec nisi volutpat eleifend.', 10, 7);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (41, 'ultrices', 'Duis mattis egestas metus.', 11, 7);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (42, 'dolor', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 11, 7);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (43, 'semper', 'Sed accumsan felis.', 11, 8);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (44, 'hac', 'Morbi ut odio.', 11, 8);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (45, 'in', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 12, 8);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (46, 'platea', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 12, 8);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (47, 'posuere', 'Suspendisse potenti.', 12, 8);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (48, 'libero', 'Vivamus in felis eu sapien cursus vestibulum.', 12, 8);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (49, 'consequat', 'Praesent id massa id nisl venenatis lacinia.', 13, 9);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (50, 'ut', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 13, 9);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (51, 'varius', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 13, 9);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (52, 'diam', 'Quisque ut erat.', 13, 9);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (53, 'sodales', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 14, 9);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (54, 'nisi', 'Pellentesque at nulla.', 14, 9);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (55, 'at', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 14, 10);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (56, 'praesent', 'Curabitur at ipsum ac tellus semper interdum.', 14, 10);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (57, 'lorem', 'Proin at turpis a pede posuere nonummy.', 15, 10);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (58, 'justo', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 15, 10);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (59, 'augue', 'Nulla justo.', 15, 10);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (60, 'cubilia', 'Integer non velit.', 15, 10);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (61, 'cras', 'Mauris sit amet eros.', 16, 11);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (62, 'montes', 'Morbi non quam nec dui luctus rutrum.', 16, 11);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (63, 'orci', 'Morbi a ipsum.', 16, 11);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (64, 'vestibulum', 'Donec dapibus.', 16, 11);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (65, 'sociis', 'Nunc rhoncus dui vel sem.', 17, 11);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (66, 'adipiscing', 'Proin risus.', 17, 11);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (67, 'duis', 'In hac habitasse platea dictumst.', 17, 12);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (68, 'nonummy', 'Praesent blandit lacinia erat.', 17, 12);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (69, 'lobortis', 'In hac habitasse platea dictumst.', 18, 12);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (70, 'magna', 'Morbi ut odio.', 18, 12);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (71, 'quisque', 'Proin interdum mauris non ligula pellentesque ultrices.', 18, 12);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (72, 'orci', 'Praesent id massa id nisl venenatis lacinia.', 18, 12);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (73, 'rhoncus', 'Cras non velit nec nisi vulputate nonummy.', 19, 13);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (74, 'hac', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 19, 13);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (75, 'turpis', 'Cras non velit nec nisi vulputate nonummy.', 19, 13);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (76, 'et', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 19, 13);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (77, 'cubilia', 'Donec vitae nisi.', 20, 13);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (78, 'quam', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 20, 13);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (79, 'in', 'Donec ut dolor.', 20, 14);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (80, 'nisl', 'Nulla nisl.', 20, 14);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (81, 'at', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 21, 14);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (82, 'vestibulum', 'Pellentesque viverra pede ac diam.', 21, 14);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (83, 'proin', 'Curabitur convallis.', 21, 14);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (84, 'massa', 'Mauris lacinia sapien quis libero.', 21, 14);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (85, 'fringilla', 'Aenean fermentum.', 22, 15);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (86, 'nec', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 22, 15);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (87, 'porttitor', 'In hac habitasse platea dictumst.', 22, 15);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (88, 'rutrum', 'Praesent blandit.', 22, 15);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (89, 'laoreet', 'Quisque ut erat.', 23, 15);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (90, 'nisi', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 23, 15);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (91, 'volutpat', 'Aliquam non mauris.', 23, 16);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (92, 'proin', 'Aliquam erat volutpat.', 23, 16);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (93, 'lectus', 'Etiam pretium iaculis justo.', 24, 16);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (94, 'justo', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 24, 16);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (95, 'ante', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 24, 16);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (96, 'turpis', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 24, 16);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (97, 'sed', 'Vestibulum rutrum rutrum neque.', 25, 17);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (98, 'nisl', 'Integer tincidunt ante vel ipsum.', 25, 17);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (99, 'pharetra', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 25, 17);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (100, 'odio', 'Morbi quis tortor id nulla ultrices aliquet.', 25, 17);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (101, 'proin', 'Nam tristique tortor eu pede.', 26, 17);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (102, 'ac', 'Curabitur at ipsum ac tellus semper interdum.', 26, 17);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (103, 'erat', 'Nullam varius.', 26, 18);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (104, 'varius', 'Suspendisse accumsan tortor quis turpis.', 26, 18);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (105, 'felis', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 27, 18);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (106, 'venenatis', 'In hac habitasse platea dictumst.', 27, 18);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (107, 'in', 'Suspendisse potenti.', 27, 18);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (108, 'at', 'Duis bibendum.', 27, 18);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (109, 'ipsum', 'Vivamus in felis eu sapien cursus vestibulum.', 28, 19);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (110, 'non', 'Quisque ut erat.', 28, 19);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (111, 'sem', 'Morbi ut odio.', 28, 19);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (112, 'amet', 'Vivamus vel nulla eget eros elementum pellentesque.', 28, 19);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (113, 'nisl', 'Nunc rhoncus dui vel sem.', 29, 19);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (114, 'ridiculus', 'Aenean fermentum.', 29, 19);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (115, 'in', 'Etiam faucibus cursus urna.', 29, 20);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (116, 'justo', 'Sed accumsan felis.', 29, 20);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (117, 'ultrices', 'In hac habitasse platea dictumst.', 30, 20);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (118, 'convallis', 'Pellentesque at nulla.', 30, 20);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (119, 'felis', 'Vivamus tortor.', 30, 20);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (120, 'volutpat', 'Etiam vel augue.', 30, 20);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (121, 'tellus', 'Cras pellentesque volutpat dui.', 31, 21);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (122, 'tincidunt', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 31, 21);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (123, 'ligula', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 31, 21);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (124, 'tristique', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 31, 21);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (125, 'quis', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 32, 21);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (126, 'rhoncus', 'Suspendisse potenti.', 32, 21);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (127, 'in', 'Duis at velit eu est congue elementum.', 32, 22);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (128, 'at', 'Nam dui.', 32, 22);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (129, 'justo', 'Pellentesque viverra pede ac diam.', 33, 22);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (130, 'primis', 'Curabitur gravida nisi at nibh.', 33, 22);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (131, 'nisi', 'Donec posuere metus vitae ipsum.', 33, 22);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (132, 'volutpat', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 33, 22);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (133, 'ut', 'Vestibulum ac est lacinia nisi venenatis tristique.', 34, 23);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (134, 'et', 'Integer ac neque.', 34, 23);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (135, 'quis', 'In blandit ultrices enim.', 34, 23);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (136, 'odio', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 34, 23);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (137, 'maecenas', 'Proin risus.', 35, 23);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (138, 'molestie', 'Nam dui.', 35, 23);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (139, 'et', 'Integer ac leo.', 35, 24);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (140, 'justo', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 35, 24);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (141, 'cum', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 36, 24);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (142, 'auctor', 'Nulla ut erat id mauris vulputate elementum.', 36, 24);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (143, 'odio', 'Donec quis orci eget orci vehicula condimentum.', 36, 24);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (144, 'maecenas', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 36, 24);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (145, 'nisl', 'Nam nulla.', 37, 25);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (146, 'diam', 'Pellentesque viverra pede ac diam.', 37, 25);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (147, 'semper', 'Aliquam non mauris.', 37, 25);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (148, 'habitasse', 'Nullam porttitor lacus at turpis.', 37, 25);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (149, 'at', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 38, 25);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (150, 'suscipit', 'Sed vel enim sit amet nunc viverra dapibus.', 38, 25);
