insert into area (id, nome, descricao) values (1, 'Singapore Airlines', 'etiam justo');
insert into area (id, nome, descricao) values (2, 'Southwest Airlines', 'tincidunt eu');
insert into area (id, nome, descricao) values (3, 'Delta Air Lines', 'vestibulum');
insert into area (id, nome, descricao) values (4, 'Iberia', 'proin');
insert into area (id, nome, descricao) values (5, 'Air France', 'ligula vehicula');
insert into area (id, nome, descricao) values (6, 'SAS Scandinavian', 'interdum');
insert into area (id, nome, descricao) values (7, 'Iberia', 'fusce congue');
insert into area (id, nome, descricao) values (8, 'Thai Airways', 'rutrum nulla');
insert into area (id, nome, descricao) values (9, 'United Airlines', 'ultrices');
insert into area (id, nome, descricao) values (10, 'Ethiopian Airlines', 'vivamus vel');
insert into area (id, nome, descricao) values (11, 'Avianca', 'imperdiet nullam');
insert into area (id, nome, descricao) values (12, 'American Airlines', 'lectus');
insert into area (id, nome, descricao) values (13, 'Qantas', 'at turpis');
insert into area (id, nome, descricao) values (14, 'KLM Royal Dutch Airlines', 'fermentum justo');
insert into area (id, nome, descricao) values (15, 'KLM Royal Dutch Airlines', 'tempus sit');
insert into area (id, nome, descricao) values (16, 'Emirates', 'vitae mattis');
insert into area (id, nome, descricao) values (17, 'Cathay Pacific', 'integer pede');
insert into area (id, nome, descricao) values (18, 'Alitalia', 'dictumst morbi');
insert into area (id, nome, descricao) values (19, 'Iberia', 'posuere felis');
insert into area (id, nome, descricao) values (20, 'Alitalia', 'nulla elit');
insert into area (id, nome, descricao) values (21, 'Alitalia', 'non');
insert into area (id, nome, descricao) values (22, 'Singapore Airlines', 'mauris');
insert into area (id, nome, descricao) values (23, 'Thai Airways', 'nunc');
insert into area (id, nome, descricao) values (24, 'Air New Zealand', 'ac leo');
insert into area (id, nome, descricao) values (25, 'British Airways', 'id');
insert into area (id, nome, descricao) values (26, 'Air India', 'interdum');
insert into area (id, nome, descricao) values (27, 'Air India', 'sociis');
insert into area (id, nome, descricao) values (28, 'Air Canada', 'rutrum');
insert into area (id, nome, descricao) values (29, 'Air India', 'ut');
insert into area (id, nome, descricao) values (30, 'KLM Royal Dutch Airlines', 'at');
insert into area (id, nome, descricao) values (31, 'LATAM Airlines', 'nam congue');
insert into area (id, nome, descricao) values (32, 'South African Airways', 'felis donec');
insert into area (id, nome, descricao) values (33, 'Aeroméxico', 'neque sapien');
insert into area (id, nome, descricao) values (34, 'Cathay Pacific', 'neque');
insert into area (id, nome, descricao) values (35, 'Iberia', 'ridiculus mus');
insert into area (id, nome, descricao) values (36, 'Aeroméxico', 'vivamus vestibulum');
insert into area (id, nome, descricao) values (37, 'Avianca', 'consectetuer adipiscing');
insert into area (id, nome, descricao) values (38, 'South African Airways', 'nascetur ridiculus');
insert into area (id, nome, descricao) values (39, 'Avianca', 'ac consequat');
insert into area (id, nome, descricao) values (40, 'American Airlines', 'etiam justo');
insert into area (id, nome, descricao) values (41, 'Air Canada', 'lobortis convallis');
insert into area (id, nome, descricao) values (42, 'KLM Royal Dutch Airlines', 'at');
insert into area (id, nome, descricao) values (43, 'Qantas', 'risus');
insert into area (id, nome, descricao) values (44, 'American Airlines', 'maecenas');
insert into area (id, nome, descricao) values (45, 'Thai Airways', 'sem praesent');
insert into area (id, nome, descricao) values (46, 'Korean Air', 'maecenas tincidunt');
insert into area (id, nome, descricao) values (47, 'SAS Scandinavian', 'ut erat');
insert into area (id, nome, descricao) values (48, 'All Nippon Airways', 'luctus');
insert into area (id, nome, descricao) values (49, 'Iberia', 'duis');
insert into area (id, nome, descricao) values (50, 'Air India', 'penatibus et');
insert into area (id, nome, descricao) values (51, 'British Airways', 'ut volutpat');
insert into area (id, nome, descricao) values (52, 'American Airlines', 'leo');
insert into area (id, nome, descricao) values (53, 'American Airlines', 'dapibus at');
insert into area (id, nome, descricao) values (54, 'All Nippon Airways', 'pede justo');
insert into area (id, nome, descricao) values (55, 'Alitalia', 'mattis');
insert into area (id, nome, descricao) values (56, 'South African Airways', 'lacus');
insert into area (id, nome, descricao) values (57, 'Cathay Pacific', 'quisque');
insert into area (id, nome, descricao) values (58, 'Korean Air', 'nullam porttitor');
insert into area (id, nome, descricao) values (59, 'Emirates', 'pede');
insert into area (id, nome, descricao) values (60, 'Southwest Airlines', 'nam');
insert into area (id, nome, descricao) values (61, 'Korean Air', 'non pretium');
insert into area (id, nome, descricao) values (62, 'Ethiopian Airlines', 'volutpat in');
insert into area (id, nome, descricao) values (63, 'Air Canada', 'accumsan');
insert into area (id, nome, descricao) values (64, 'Qantas', 'suspendisse ornare');
insert into area (id, nome, descricao) values (65, 'KLM Royal Dutch Airlines', 'in libero');
insert into area (id, nome, descricao) values (66, 'Aeroméxico', 'magnis');
insert into area (id, nome, descricao) values (67, 'Alitalia', 'justo in');
insert into area (id, nome, descricao) values (68, 'Singapore Airlines', 'odio curabitur');
insert into area (id, nome, descricao) values (69, 'Air New Zealand', 'lectus aliquam');
insert into area (id, nome, descricao) values (70, 'British Airways', 'quam fringilla');
insert into area (id, nome, descricao) values (71, 'United Airlines', 'nunc donec');
insert into area (id, nome, descricao) values (72, 'Avianca', 'nibh');
insert into area (id, nome, descricao) values (73, 'Air Canada', 'molestie');
insert into area (id, nome, descricao) values (74, 'Cathay Pacific', 'tortor');
insert into area (id, nome, descricao) values (75, 'Cathay Pacific', 'sem');
insert into area (id, nome, descricao) values (76, 'Qatar Airways', 'imperdiet sapien');
insert into area (id, nome, descricao) values (77, 'Korean Air', 'lobortis vel');
insert into area (id, nome, descricao) values (78, 'KLM Royal Dutch Airlines', 'metus');
insert into area (id, nome, descricao) values (79, 'South African Airways', 'ultricies eu');
insert into area (id, nome, descricao) values (80, 'Air France', 'amet');
insert into area (id, nome, descricao) values (81, 'SAS Scandinavian', 'viverra eget');
insert into area (id, nome, descricao) values (82, 'Alitalia', 'at');
insert into area (id, nome, descricao) values (83, 'Lufthansa', 'vel');
insert into area (id, nome, descricao) values (84, 'SAS Scandinavian', 'curabitur at');
insert into area (id, nome, descricao) values (85, 'Thai Airways', 'pede');
insert into area (id, nome, descricao) values (86, 'British Airways', 'nulla dapibus');
insert into area (id, nome, descricao) values (87, 'Air Canada', 'in');
insert into area (id, nome, descricao) values (88, 'Emirates', 'quam suspendisse');
insert into area (id, nome, descricao) values (89, 'All Nippon Airways', 'sem mauris');
insert into area (id, nome, descricao) values (90, 'American Airlines', 'congue');
insert into area (id, nome, descricao) values (91, 'LATAM Airlines', 'vestibulum proin');
insert into area (id, nome, descricao) values (92, 'British Airways', 'lectus in');
insert into area (id, nome, descricao) values (93, 'Thai Airways', 'elit');
insert into area (id, nome, descricao) values (94, 'South African Airways', 'ut');
insert into area (id, nome, descricao) values (95, 'Thai Airways', 'praesent');
insert into area (id, nome, descricao) values (96, 'Aeroméxico', 'feugiat');
insert into area (id, nome, descricao) values (97, 'American Airlines', 'vestibulum ante');
insert into area (id, nome, descricao) values (98, 'South African Airways', 'tempor turpis');
insert into area (id, nome, descricao) values (99, 'South African Airways', 'diam');
insert into area (id, nome, descricao) values (100, 'Singapore Airlines', 'in');
insert into area (id, nome, descricao) values (101, 'Avianca', 'dictumst');
insert into area (id, nome, descricao) values (102, 'SAS Scandinavian', 'felis sed');
insert into area (id, nome, descricao) values (103, 'Ethiopian Airlines', 'aliquam');
insert into area (id, nome, descricao) values (104, 'United Airlines', 'vestibulum');
insert into area (id, nome, descricao) values (105, 'Korean Air', 'mauris');
insert into area (id, nome, descricao) values (106, 'Emirates', 'blandit non');
insert into area (id, nome, descricao) values (107, 'Avianca', 'quisque arcu');
insert into area (id, nome, descricao) values (108, 'KLM Royal Dutch Airlines', 'non');
insert into area (id, nome, descricao) values (109, 'Air France', 'velit');
insert into area (id, nome, descricao) values (110, 'Thai Airways', 'semper');
insert into area (id, nome, descricao) values (111, 'Air France', 'nunc viverra');
insert into area (id, nome, descricao) values (112, 'Avianca', 'at');
insert into area (id, nome, descricao) values (113, 'Alitalia', 'sociis');
insert into area (id, nome, descricao) values (114, 'Air New Zealand', 'suspendisse ornare');
insert into area (id, nome, descricao) values (115, 'United Airlines', 'morbi odio');
insert into area (id, nome, descricao) values (116, 'Emirates', 'consequat');
insert into area (id, nome, descricao) values (117, 'SAS Scandinavian', 'ipsum dolor');
insert into area (id, nome, descricao) values (118, 'Air France', 'ut ultrices');
insert into area (id, nome, descricao) values (119, 'Iberia', 'erat');
insert into area (id, nome, descricao) values (120, 'South African Airways', 'amet');
insert into area (id, nome, descricao) values (121, 'Qantas', 'augue a');
insert into area (id, nome, descricao) values (122, 'Lufthansa', 'orci');
insert into area (id, nome, descricao) values (123, 'SAS Scandinavian', 'volutpat dui');
insert into area (id, nome, descricao) values (124, 'Air New Zealand', 'id nulla');
insert into area (id, nome, descricao) values (125, 'Qatar Airways', 'eros');
insert into area (id, nome, descricao) values (126, 'Air Canada', 'dui vel');
insert into area (id, nome, descricao) values (127, 'Avianca', 'volutpat');
insert into area (id, nome, descricao) values (128, 'South African Airways', 'dui vel');
insert into area (id, nome, descricao) values (129, 'Avianca', 'tempus vivamus');
insert into area (id, nome, descricao) values (130, 'Thai Airways', 'sapien');
insert into area (id, nome, descricao) values (131, 'British Airways', 'elementum nullam');
insert into area (id, nome, descricao) values (132, 'KLM Royal Dutch Airlines', 'tortor quis');
insert into area (id, nome, descricao) values (133, 'Air Canada', 'orci');
insert into area (id, nome, descricao) values (134, 'British Airways', 'nullam');
insert into area (id, nome, descricao) values (135, 'All Nippon Airways', 'ipsum dolor');
insert into area (id, nome, descricao) values (136, 'Qantas', 'mauris non');
insert into area (id, nome, descricao) values (137, 'Avianca', 'velit donec');
insert into area (id, nome, descricao) values (138, 'Air Canada', 'sed');
insert into area (id, nome, descricao) values (139, 'Iberia', 'sed');
insert into area (id, nome, descricao) values (140, 'British Airways', 'justo pellentesque');
insert into area (id, nome, descricao) values (141, 'British Airways', 'proin risus');
insert into area (id, nome, descricao) values (142, 'Singapore Airlines', 'in');
insert into area (id, nome, descricao) values (143, 'Southwest Airlines', 'volutpat eleifend');
insert into area (id, nome, descricao) values (144, 'SAS Scandinavian', 'condimentum neque');
insert into area (id, nome, descricao) values (145, 'American Airlines', 'tincidunt');
insert into area (id, nome, descricao) values (146, 'American Airlines', 'maecenas rhoncus');
insert into area (id, nome, descricao) values (147, 'United Airlines', 'mauris');
insert into area (id, nome, descricao) values (148, 'Lufthansa', 'convallis nunc');
insert into area (id, nome, descricao) values (149, 'Thai Airways', 'libero');
insert into area (id, nome, descricao) values (150, 'Avianca', 'sed');
insert into area (id, nome, descricao) values (151, 'Iberia', 'proin');
insert into area (id, nome, descricao) values (152, 'Qatar Airways', 'nunc');
insert into area (id, nome, descricao) values (153, 'British Airways', 'dictumst');
insert into area (id, nome, descricao) values (154, 'Air Canada', 'ipsum primis');
insert into area (id, nome, descricao) values (155, 'Cathay Pacific', 'in');
insert into area (id, nome, descricao) values (156, 'Korean Air', 'massa');
insert into area (id, nome, descricao) values (157, 'Iberia', 'felis donec');
insert into area (id, nome, descricao) values (158, 'Air India', 'auctor gravida');
insert into area (id, nome, descricao) values (159, 'Air New Zealand', 'quis tortor');
insert into area (id, nome, descricao) values (160, 'Iberia', 'sapien');
insert into area (id, nome, descricao) values (161, 'British Airways', 'pretium iaculis');
insert into area (id, nome, descricao) values (162, 'Lufthansa', 'pellentesque eget');
insert into area (id, nome, descricao) values (163, 'South African Airways', 'cursus vestibulum');
insert into area (id, nome, descricao) values (164, 'Singapore Airlines', 'dui');
insert into area (id, nome, descricao) values (165, 'Thai Airways', 'ac');
insert into area (id, nome, descricao) values (166, 'LATAM Airlines', 'rhoncus');
insert into area (id, nome, descricao) values (167, 'Qantas', 'consequat');
insert into area (id, nome, descricao) values (168, 'Air France', 'praesent blandit');
insert into area (id, nome, descricao) values (169, 'Emirates', 'amet');
insert into area (id, nome, descricao) values (170, 'LATAM Airlines', 'nunc viverra');
insert into area (id, nome, descricao) values (171, 'Air India', 'primis');
insert into area (id, nome, descricao) values (172, 'Cathay Pacific', 'euismod');
insert into area (id, nome, descricao) values (173, 'Qatar Airways', 'luctus tincidunt');
insert into area (id, nome, descricao) values (174, 'Qantas', 'vivamus');
insert into area (id, nome, descricao) values (175, 'Alitalia', 'pede malesuada');
insert into area (id, nome, descricao) values (176, 'Qatar Airways', 'ornare imperdiet');
insert into area (id, nome, descricao) values (177, 'Air Canada', 'quam');
insert into area (id, nome, descricao) values (178, 'KLM Royal Dutch Airlines', 'tortor');
insert into area (id, nome, descricao) values (179, 'Aeroméxico', 'sed augue');
insert into area (id, nome, descricao) values (180, 'American Airlines', 'non');
insert into area (id, nome, descricao) values (181, 'Emirates', 'a');
insert into area (id, nome, descricao) values (182, 'United Airlines', 'mauris');
insert into area (id, nome, descricao) values (183, 'South African Airways', 'lacinia');
insert into area (id, nome, descricao) values (184, 'Lufthansa', 'erat');
insert into area (id, nome, descricao) values (185, 'Air France', 'morbi');
insert into area (id, nome, descricao) values (186, 'Iberia', 'ut');
insert into area (id, nome, descricao) values (187, 'Lufthansa', 'iaculis diam');
insert into area (id, nome, descricao) values (188, 'South African Airways', 'sapien');
insert into area (id, nome, descricao) values (189, 'Avianca', 'sit');
insert into area (id, nome, descricao) values (190, 'Aeroméxico', 'et');
insert into area (id, nome, descricao) values (191, 'Air Canada', 'ut mauris');
insert into area (id, nome, descricao) values (192, 'Air France', 'vivamus vestibulum');
insert into area (id, nome, descricao) values (193, 'Avianca', 'platea');
insert into area (id, nome, descricao) values (194, 'LATAM Airlines', 'proin');
insert into area (id, nome, descricao) values (195, 'South African Airways', 'enim in');
insert into area (id, nome, descricao) values (196, 'Lufthansa', 'neque');
insert into area (id, nome, descricao) values (197, 'Air India', 'eu');
insert into area (id, nome, descricao) values (198, 'Air France', 'maecenas tincidunt');
insert into area (id, nome, descricao) values (199, 'Air India', 'vivamus vestibulum');
insert into area (id, nome, descricao) values (200, 'American Airlines', 'in');
insert into area (id, nome, descricao) values (201, 'United Airlines', 'dapibus');
insert into area (id, nome, descricao) values (202, 'KLM Royal Dutch Airlines', 'parturient montes');
insert into area (id, nome, descricao) values (203, 'Alitalia', 'luctus et');
insert into area (id, nome, descricao) values (204, 'British Airways', 'curabitur');
insert into area (id, nome, descricao) values (205, 'Singapore Airlines', 'aenean fermentum');
insert into area (id, nome, descricao) values (206, 'Cathay Pacific', 'at');
insert into area (id, nome, descricao) values (207, 'United Airlines', 'ut');
insert into area (id, nome, descricao) values (208, 'South African Airways', 'diam vitae');
insert into area (id, nome, descricao) values (209, 'Ethiopian Airlines', 'vehicula consequat');
insert into area (id, nome, descricao) values (210, 'Singapore Airlines', 'sed augue');
insert into area (id, nome, descricao) values (211, 'Lufthansa', 'auctor gravida');
insert into area (id, nome, descricao) values (212, 'SAS Scandinavian', 'cum');
insert into area (id, nome, descricao) values (213, 'Southwest Airlines', 'vestibulum');
insert into area (id, nome, descricao) values (214, 'Qatar Airways', 'sed magna');
insert into area (id, nome, descricao) values (215, 'American Airlines', 'massa tempor');
insert into area (id, nome, descricao) values (216, 'Iberia', 'at');
insert into area (id, nome, descricao) values (217, 'British Airways', 'sed interdum');
insert into area (id, nome, descricao) values (218, 'British Airways', 'ante');
insert into area (id, nome, descricao) values (219, 'SAS Scandinavian', 'vestibulum');
insert into area (id, nome, descricao) values (220, 'South African Airways', 'sit amet');
insert into area (id, nome, descricao) values (221, 'Thai Airways', 'non mauris');
insert into area (id, nome, descricao) values (222, 'Qatar Airways', 'dictumst');
insert into area (id, nome, descricao) values (223, 'South African Airways', 'amet erat');
insert into area (id, nome, descricao) values (224, 'Singapore Airlines', 'tristique');
insert into area (id, nome, descricao) values (225, 'Emirates', 'dictumst');
insert into area (id, nome, descricao) values (226, 'Alitalia', 'erat id');
insert into area (id, nome, descricao) values (227, 'All Nippon Airways', 'potenti nullam');
insert into area (id, nome, descricao) values (228, 'Avianca', 'congue etiam');
insert into area (id, nome, descricao) values (229, 'Alitalia', 'metus arcu');
insert into area (id, nome, descricao) values (230, 'Korean Air', 'vel');
insert into area (id, nome, descricao) values (231, 'Air India', 'volutpat erat');
insert into area (id, nome, descricao) values (232, 'Aeroméxico', 'dis');
insert into area (id, nome, descricao) values (233, 'Lufthansa', 'odio');
insert into area (id, nome, descricao) values (234, 'Aeroméxico', 'ut');
insert into area (id, nome, descricao) values (235, 'Qantas', 'vestibulum eget');
insert into area (id, nome, descricao) values (236, 'Aeroméxico', 'amet turpis');
insert into area (id, nome, descricao) values (237, 'Delta Air Lines', 'ac');
insert into area (id, nome, descricao) values (238, 'Cathay Pacific', 'et');
insert into area (id, nome, descricao) values (239, 'SAS Scandinavian', 'amet consectetuer');
insert into area (id, nome, descricao) values (240, 'KLM Royal Dutch Airlines', 'eu interdum');
insert into area (id, nome, descricao) values (241, 'Avianca', 'magna');
insert into area (id, nome, descricao) values (242, 'LATAM Airlines', 'lacus morbi');
insert into area (id, nome, descricao) values (243, 'Alitalia', 'ipsum dolor');
insert into area (id, nome, descricao) values (244, 'Cathay Pacific', 'libero ut');
insert into area (id, nome, descricao) values (245, 'Qatar Airways', 'velit');
insert into area (id, nome, descricao) values (246, 'All Nippon Airways', 'donec odio');
insert into area (id, nome, descricao) values (247, 'Singapore Airlines', 'aenean');
insert into area (id, nome, descricao) values (248, 'KLM Royal Dutch Airlines', 'id ornare');
insert into area (id, nome, descricao) values (249, 'Singapore Airlines', 'consequat');
insert into area (id, nome, descricao) values (250, 'Singapore Airlines', 'augue');
