insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (1, 'rhoncus', 'GL-U-A', 'ultrices aliquet', 1, 46, 1);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (2, 'lectus', 'MN-046', 'lacinia aenean', 4, 9, 2);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (3, 'rhoncus', 'MY-10', 'ante', 5, 30, 3);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (4, 'mauris', 'PK-PB', 'vitae', 4, 21, 4);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (5, 'vulputate', 'JP-28', 'maecenas leo', 4, 49, 5);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (6, 'proin', 'DE-BY', 'magna vulputate', 1, 42, 6);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (7, 'turpis', 'US-MN', 'nisl duis', 5, 34, 7);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (8, 'fusce', 'US-IL', 'augue', 5, 27, 8);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (9, 'in', 'US-IN', 'curae', 3, 25, 9);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (10, 'et', 'CD-KA', 'at', 5, 40, 10);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (11, 'turpis', 'AU-QLD', 'volutpat', 5, 48, 11);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (12, 'dignissim', 'NI-AN', 'rhoncus', 2, 50, 12);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (13, 'purus', 'JP-32', 'proin at', 5, 16, 13);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (14, 'vel', 'IN-JK', 'lobortis sapien', 4, 41, 14);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (15, 'tortor', 'PG-MPL', 'vel', 1, 19, 15);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (16, 'nec', 'US-AK', 'aliquet ultrices', 1, 23, 16);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (17, 'convallis', 'KZ-KUS', 'sed tristique', 3, 30, 17);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (18, 'eget', 'ZA-NL', 'a feugiat', 3, 29, 18);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (19, 'nulla', 'BR-AC', 'leo pellentesque', 1, 37, 19);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (20, 'varius', 'US-GA', 'cubilia', 4, 21, 20);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (21, 'enim', 'NA-OH', 'massa volutpat', 5, 46, 21);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (22, 'ante', 'DE-NW', 'in', 5, 15, 22);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (23, 'nisi', 'US-ME', 'erat', 5, 37, 23);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (24, 'interdum', 'PK-SD', 'vestibulum', 2, 29, 24);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (25, 'justo', 'BO-S', 'ut mauris', 5, 34, 25);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (26, 'aliquam', 'CA-ON', 'nam', 2, 46, 26);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (27, 'est', 'TR-56', 'justo sit', 5, 27, 27);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (28, 'ut', 'LA-AT', 'parturient', 5, 34, 28);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (29, 'felis', 'MY-13', 'fermentum', 2, 28, 29);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (30, 'ultrices', 'IN-CT', 'quis odio', 4, 25, 30);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (31, 'ut', 'US-AL', 'nulla', 2, 33, 31);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (32, 'proin', 'CA-NS', 'curae donec', 4, 50, 32);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (33, 'eleifend', 'US-NV', 'elementum ligula', 3, 8, 33);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (34, 'lacinia', 'PG-MPL', 'orci luctus', 3, 35, 34);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (35, 'dis', 'BR-PI', 'eu mi', 2, 49, 35);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (36, 'nec', 'FR-I', 'sit', 5, 39, 36);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (37, 'eget', 'PG-NSB', 'ante', 4, 47, 37);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (38, 'volutpat', 'RS-07', 'sapien', 1, 27, 38);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (39, 'et', 'MX-BCN', 'quam pede', 4, 23, 39);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (40, 'id', 'NP-BA', 'nulla', 2, 4, 40);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (41, 'ac', 'BR-MG', 'ultrices vel', 2, 50, 41);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (42, 'neque', 'US-MA', 'vestibulum eget', 1, 24, 42);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (43, 'est', 'EG-MN', 'in', 4, 30, 43);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (44, 'lobortis', 'BR-PA', 'tincidunt nulla', 5, 22, 44);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (45, 'elit', 'US-FL', 'vestibulum ante', 2, 24, 45);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (46, 'vel', 'RU-SA', 'nunc', 4, 45, 46);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (47, 'mi', 'ZW-MN', 'egestas', 1, 22, 47);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (48, 'pede', 'AR-B', 'diam', 4, 19, 48);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (49, 'quam', 'US-MO', 'ac est', 2, 7, 49);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (50, 'sapien', 'BR-BA', 'dolor', 3, 23, 50);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (51, 'consequat', 'ET-AM', 'in', 5, 5, 51);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (52, 'tristique', 'LA-BK', 'erat', 2, 6, 52);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (53, 'sit', 'CA-BC', 'luctus', 2, 16, 53);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (54, 'vestibulum', 'AE-DU', 'neque', 1, 21, 54);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (55, 'nibh', 'BR-PR', 'ante', 4, 12, 55);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (56, 'potenti', 'RU-SA', 'nam dui', 2, 32, 56);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (57, 'mauris', 'MX-MIC', 'nam', 5, 48, 57);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (58, 'lacinia', 'IT-72', 'tortor sollicitudin', 2, 30, 58);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (59, 'posuere', 'ID-RI', 'vestibulum ante', 2, 29, 59);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (60, 'aliquet', 'US-IA', 'quisque', 1, 47, 60);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (61, 'dui', 'AU-NT', 'enim sit', 4, 8, 61);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (62, 'eget', 'NZ-MWT', 'curae mauris', 2, 27, 62);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (63, 'nam', 'SD-13', 'at', 1, 10, 63);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (64, 'orci', 'US-HI', 'enim', 5, 3, 64);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (65, 'duis', 'CN-45', 'ut', 1, 50, 65);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (66, 'tortor', 'US-SC', 'sit amet', 5, 9, 66);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (67, 'arcu', 'IE-G', 'dui luctus', 5, 32, 67);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (68, 'duis', 'LA-HO', 'non', 3, 13, 68);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (69, 'aenean', 'UA-77', 'non', 1, 20, 69);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (70, 'nulla', 'DE-SH', 'porttitor pede', 3, 41, 70);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (71, 'in', 'PH-BTN', 'cum', 3, 10, 71);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (72, 'adipiscing', 'BY-MI', 'nunc viverra', 5, 28, 72);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (73, 'ut', 'US-AK', 'curabitur', 3, 37, 73);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (74, 'odio', 'BR-RJ', 'platea', 5, 36, 74);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (75, 'eget', 'CA-ON', 'lectus', 2, 37, 75);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (76, 'ante', 'EG-JS', 'aliquam', 2, 33, 76);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (77, 'sem', 'AU-QLD', 'auctor sed', 2, 9, 77);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (78, 'amet', 'QA-DA', 'curae mauris', 5, 11, 78);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (79, 'non', 'PG-SAN', 'neque', 1, 20, 79);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (80, 'congue', 'US-IL', 'pretium iaculis', 1, 43, 80);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (81, 'proin', 'AO-HUI', 'nisi volutpat', 1, 38, 81);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (82, 'non', 'PG-CPM', 'hendrerit at', 5, 43, 82);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (83, 'vestibulum', 'CD-OR', 'tortor', 5, 3, 83);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (84, 'gravida', 'NG-LA', 'quis orci', 3, 31, 84);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (85, 'vestibulum', 'MM-04', 'volutpat quam', 2, 17, 85);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (86, 'mauris', 'IR-30', 'dictumst', 1, 38, 86);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (87, 'lorem', 'CU-11', 'in lacus', 1, 47, 87);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (88, 'justo', 'BR-SP', 'in', 3, 15, 88);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (89, 'leo', 'BR-PA', 'sociis natoque', 1, 40, 89);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (90, 'phasellus', 'RO-CS', 'feugiat non', 2, 35, 90);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (91, 'justo', 'US-WA', 'ut', 1, 27, 91);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (92, 'luctus', 'CN-62', 'eget', 3, 2, 92);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (93, 'nibh', 'AU-QLD', 'ligula', 1, 2, 93);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (94, 'nulla', 'NZ-MBH', 'volutpat convallis', 4, 9, 94);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (95, 'non', 'TD-CB', 'aliquet at', 3, 18, 95);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (96, 'ipsum', 'CD-OR', 'sollicitudin ut', 1, 8, 96);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (97, 'ante', 'VI-U-A', 'aliquam sit', 5, 30, 97);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (98, 'interdum', 'AU-QLD', 'vestibulum velit', 5, 30, 98);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (99, 'sagittis', 'US-MS', 'donec', 1, 18, 99);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (100, 'velit', 'US-PA', 'at turpis', 5, 5, 100);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (101, 'massa', 'US-AK', 'nulla nisl', 1, 24, 101);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (102, 'dolor', 'DK-84', 'porttitor lorem', 4, 50, 102);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (103, 'integer', 'CA-BC', 'donec ut', 1, 35, 103);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (104, 'tellus', 'US-TX', 'iaculis', 1, 16, 104);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (105, 'odio', 'EC-S', 'ornare imperdiet', 4, 44, 105);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (106, 'semper', 'US-FL', 'consectetuer', 4, 15, 106);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (107, 'ut', 'RU-SE', 'cursus vestibulum', 1, 9, 107);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (108, 'hac', 'AU-NT', 'consequat dui', 2, 21, 108);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (109, 'adipiscing', 'ID-PA', 'suspendisse ornare', 4, 4, 109);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (110, 'porttitor', 'CN-62', 'sapien', 2, 5, 110);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (111, 'suspendisse', 'CN-51', 'interdum in', 4, 4, 111);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (112, 'enim', 'BR-BA', 'tempus', 1, 36, 112);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (113, 'lobortis', 'BR-MG', 'non', 1, 12, 113);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (114, 'in', 'LV-RIX', 'aenean sit', 1, 15, 114);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (115, 'duis', 'IN-MM', 'orci nullam', 3, 15, 115);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (116, 'vestibulum', 'CA-QC', 'cum sociis', 4, 7, 116);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (117, 'blandit', 'RU-YAN', 'cras mi', 2, 17, 117);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (118, 'eros', 'VE-S', 'rhoncus', 2, 33, 118);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (119, 'sed', 'AU-WA', 'dignissim vestibulum', 4, 49, 119);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (120, 'quis', 'US-HI', 'non', 2, 20, 120);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (121, 'at', 'TZ-08', 'convallis', 5, 22, 121);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (122, 'dapibus', 'MG-D', 'nullam molestie', 4, 20, 122);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (123, 'donec', 'RU-CHU', 'magna at', 1, 2, 123);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (124, 'duis', 'BW-SE', 'eu', 2, 24, 124);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (125, 'rutrum', 'SX-U-A', 'blandit', 5, 43, 125);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (126, 'vivamus', 'US-PA', 'amet consectetuer', 4, 39, 126);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (127, 'dui', 'UA-14', 'id massa', 5, 26, 127);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (128, 'dis', 'IN-TG', 'at velit', 4, 20, 128);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (129, 'aliquam', 'SR-MA', 'vivamus', 1, 22, 129);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (130, 'magna', 'CO-COR', 'curabitur gravida', 4, 26, 130);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (131, 'rutrum', 'UY-RO', 'hendrerit at', 3, 32, 131);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (132, 'maecenas', 'TO-04', 'suspendisse potenti', 3, 34, 132);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (133, 'odio', 'US-IA', 'volutpat sapien', 1, 23, 133);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (134, 'diam', 'CO-CAL', 'vel', 5, 1, 134);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (135, 'natoque', 'AU-SA', 'consequat', 2, 5, 135);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (136, 'in', 'BE-VAN', 'interdum venenatis', 2, 31, 136);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (137, 'suscipit', 'US-FL', 'leo rhoncus', 2, 7, 137);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (138, 'erat', 'IN-GJ', 'lacinia aenean', 1, 16, 138);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (139, 'elit', 'US-CA', 'ante', 4, 39, 139);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (140, 'massa', 'CN-52', 'id', 5, 23, 140);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (141, 'semper', 'GB-ENG', 'viverra', 1, 9, 141);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (142, 'laoreet', 'SL-N', 'donec', 1, 21, 142);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (143, 'non', 'CU-09', 'id', 5, 43, 143);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (144, 'metus', 'CN-37', 'massa', 4, 9, 144);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (145, 'elit', 'NA-OH', 'eget congue', 3, 39, 145);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (146, 'at', 'AU-QLD', 'fusce', 5, 21, 146);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (147, 'odio', 'US-SD', 'tellus nulla', 4, 45, 147);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (148, 'primis', 'AU-VIC', 'mauris', 2, 23, 148);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (149, 'est', 'CA-QC', 'morbi sem', 3, 47, 149);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (150, 'quis', 'CA-MB', 'porttitor lacus', 4, 28, 150);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (151, 'odio', 'PF-U-A', 'pretium quis', 1, 39, 151);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (152, 'sit', 'AU-VIC', 'lacus', 1, 18, 152);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (153, 'sapien', 'ID-KB', 'nulla tellus', 3, 10, 153);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (154, 'non', 'AU-WA', 'libero quis', 3, 7, 154);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (155, 'mattis', 'GE-IM', 'etiam', 3, 29, 155);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (156, 'diam', 'CA-NL', 'felis', 3, 27, 156);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (157, 'adipiscing', 'ZA-EC', 'eget', 3, 21, 157);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (158, 'eget', 'MW-LK', 'ut erat', 3, 37, 158);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (159, 'condimentum', 'US-AK', 'viverra eget', 5, 29, 159);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (160, 'vehicula', 'RU-SA', 'purus', 4, 18, 160);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (161, 'sit', 'BR-MG', 'adipiscing molestie', 1, 32, 161);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (162, 'morbi', 'CA-NL', 'vel', 2, 44, 162);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (163, 'vel', 'KR-41', 'ante', 1, 25, 163);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (164, 'molestie', 'US-NM', 'eu pede', 1, 20, 164);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (165, 'vel', 'AF-GHA', 'mus', 2, 28, 165);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (166, 'id', 'US-NY', 'ut ultrices', 5, 34, 166);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (167, 'nam', 'CA-SK', 'donec', 5, 9, 167);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (168, 'erat', 'NP-GA', 'vivamus', 2, 26, 168);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (169, 'condimentum', 'US-IL', 'maecenas', 5, 11, 169);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (170, 'enim', 'US-OH', 'integer tincidunt', 3, 7, 170);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (171, 'fermentum', 'BR-MS', 'eu', 5, 29, 171);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (172, 'integer', 'IN-TR', 'dui', 4, 36, 172);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (173, 'morbi', 'TH-53', 'platea', 3, 11, 173);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (174, 'enim', 'SA-04', 'sagittis', 4, 4, 174);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (175, 'fusce', 'SA-01', 'donec vitae', 1, 9, 175);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (176, 'nascetur', 'CA-ON', 'ut mauris', 1, 20, 176);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (177, 'vel', 'US-AK', 'ultrices', 2, 38, 177);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (178, 'a', 'CD-BN', 'nisl', 2, 2, 178);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (179, 'sed', 'US-GA', 'curabitur', 2, 47, 179);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (180, 'etiam', 'CA-MB', 'mauris', 5, 3, 180);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (181, 'orci', 'US-AK', 'sed', 2, 31, 181);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (182, 'suspendisse', 'US-CA', 'non', 5, 20, 182);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (183, 'purus', 'US-FL', 'cubilia curae', 1, 42, 183);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (184, 'nulla', 'VE-F', 'phasellus', 1, 46, 184);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (185, 'iaculis', 'US-AK', 'volutpat eleifend', 1, 27, 185);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (186, 'magna', 'CO-ANT', 'id luctus', 1, 13, 186);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (187, 'sit', 'TZ-02', 'non', 2, 18, 187);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (188, 'nullam', 'PK-PB', 'diam cras', 4, 25, 188);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (189, 'sit', 'SB-ML', 'mi', 2, 13, 189);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (190, 'leo', 'LS-F', 'leo pellentesque', 1, 41, 190);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (191, 'nulla', 'CN-42', 'justo', 5, 6, 191);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (192, 'velit', 'MX-GUA', 'donec', 1, 36, 192);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (193, 'posuere', 'US-NY', 'mi pede', 5, 22, 193);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (194, 'libero', 'CD-OR', 'congue', 5, 42, 194);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (195, 'eu', 'PG-WPD', 'lectus', 2, 7, 195);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (196, 'nec', 'ES-PV', 'enim leo', 4, 14, 196);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (197, 'lectus', 'PG-NIK', 'enim lorem', 3, 29, 197);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (198, 'donec', 'BR-RS', 'eget', 2, 25, 198);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (199, 'odio', 'YE-HD', 'vestibulum vestibulum', 3, 46, 199);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (200, 'a', 'UZ-XO', 'consequat', 2, 43, 200);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (201, 'turpis', 'PG-MPM', 'adipiscing elit', 1, 22, 201);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (202, 'lacus', 'CN-22', 'odio in', 2, 38, 202);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (203, 'aliquam', 'GE-AB', 'cum', 2, 8, 203);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (204, 'justo', 'KH-16', 'blandit nam', 2, 49, 204);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (205, 'augue', 'CN-43', 'felis', 5, 13, 205);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (206, 'lorem', 'PH-CAN', 'pretium', 2, 38, 206);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (207, 'integer', 'BR-PR', 'ante', 1, 9, 207);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (208, 'blandit', 'ID-PB', 'proin', 5, 38, 208);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (209, 'vel', 'PH-CAM', 'ipsum', 5, 29, 209);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (210, 'cursus', 'GA-6', 'amet', 3, 15, 210);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (211, 'sem', 'IR-04', 'erat eros', 4, 23, 211);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (212, 'id', 'BE-WLG', 'viverra', 2, 40, 212);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (213, 'placerat', 'IN-PB', 'purus', 3, 39, 213);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (214, 'et', 'CI-09', 'parturient', 1, 12, 214);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (215, 'vulputate', 'TD-OD', 'nec euismod', 5, 37, 215);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (216, 'aliquet', 'US-OK', 'aliquam', 5, 50, 216);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (217, 'blandit', 'US-TX', 'nulla', 4, 30, 217);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (218, 'nulla', 'US-ND', 'posuere felis', 1, 4, 218);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (219, 'eget', 'US-TX', 'ac', 4, 18, 219);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (220, 'erat', 'CA-YT', 'dis parturient', 1, 19, 220);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (221, 'sollicitudin', 'PG-WPD', 'sodales sed', 5, 34, 221);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (222, 'quam', 'NO-20', 'nisi', 4, 6, 222);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (223, 'in', 'CO-VAU', 'dictumst', 1, 2, 223);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (224, 'rutrum', 'CA-MB', 'leo odio', 5, 6, 224);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (225, 'metus', 'UA-12', 'convallis', 4, 19, 225);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (226, 'volutpat', 'KI-G', 'proin leo', 3, 7, 226);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (227, 'morbi', 'AU-NT', 'orci luctus', 4, 7, 227);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (228, 'consectetuer', 'MV-28', 'consequat', 4, 14, 228);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (229, 'quisque', 'PG-MBA', 'sem duis', 4, 32, 229);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (230, 'vulputate', 'US-MI', 'fusce', 2, 34, 230);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (231, 'viverra', 'LS-A', 'tempor convallis', 5, 31, 231);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (232, 'nulla', 'FR-H', 'nulla ultrices', 2, 24, 232);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (233, 'tempus', 'PY-11', 'nec', 5, 13, 233);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (234, 'ultrices', 'GB-ENG', 'luctus nec', 1, 44, 234);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (235, 'facilisi', 'IR-06', 'praesent', 2, 18, 235);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (236, 'sit', 'US-IL', 'quam', 2, 50, 236);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (237, 'eget', 'AU-WA', 'nam nulla', 3, 22, 237);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (238, 'vel', 'DZ-03', 'aenean sit', 4, 20, 238);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (239, 'sodales', 'CN-32', 'augue luctus', 3, 30, 239);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (240, 'condimentum', 'US-AK', 'suspendisse', 4, 18, 240);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (241, 'vivamus', 'IN-MP', 'convallis', 3, 50, 241);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (242, 'libero', 'BR-SP', 'nulla ut', 5, 10, 242);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (243, 'proin', 'FR-U', 'nibh', 2, 29, 243);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (244, 'semper', 'BR-MG', 'eu massa', 5, 29, 244);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (245, 'integer', 'GR-82', 'fusce', 5, 25, 245);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (246, 'tempus', 'ID-NT', 'dui proin', 4, 49, 246);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (247, 'in', 'WS-TU', 'justo in', 3, 2, 247);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (248, 'eu', 'NP-SE', 'in', 3, 24, 248);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (249, 'pellentesque', 'PK-NW', 'ac', 3, 39, 249);
insert into curso (id, nome, codigo, descricao, duracao, ects, tipo_curso_id) values (250, 'interdum', 'CA-ON', 'platea', 5, 15, 250);
