insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (1, 'acid relief', 'nunc proin', 954334144, 1);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (2, 'laura mercier tinted moisturizer Broad Spectrum SPF 20 Sunscreen Lightweight Flawless Coverage NATURAL', 'pulvinar lobortis', 935939791, 2);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (3, 'AGARICINUM', 'auctor', 955716431, 3);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (4, 'Doxy 100', 'tortor sollicitudin', 927036761, 4);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (5, 'Up and Up Nicotine', 'eget rutrum', 933455496, 5);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (6, 'Bioelements', 'sit amet', 965577416, 6);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (7, 'Ofloxacin', 'cursus urna', 922488737, 7);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (8, 'BENAZEPRIL HYDROCHLORIDE', 'parturient', 922174108, 8);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (9, 'Cymbalta', 'pede', 954083196, 9);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (10, 'Aveeno Eczema Therapy Moisturizing', 'a', 917348254, 10);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (11, 'Neutrogena SkinClearing', 'non velit', 953641157, 11);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (12, 'Good Sense Allergy and Congestion Relief', 'sem duis', 920990044, 12);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (13, 'Breakout Control', 'nunc', 947763851, 13);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (14, 'ERWINAZE', 'aenean fermentum', 964491068, 14);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (15, 'No7 Stay Perfect Foundation Sunscreen SPF 15 Tan', 'ridiculus', 965053144, 15);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (16, 'Unblemish', 'viverra eget', 926818031, 16);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (17, 'Amlodipine Besylate', 'urna', 929894044, 17);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (18, 'PARURE DE LUMIERE LIGHT-DIFFUSING FOUNDATION WITH SUNSCREEN MOISTURE INFUSION BROAD SPECTRUM SPF 25 03 BEIGE NATUREL', 'odio', 924416348, 18);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (19, 'Isopropyl alcohol', 'porttitor id', 918211501, 19);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (20, 'Body Luxuries Tihitian Vanilla Antibacterial Hand Sanitizer', 'vitae nisl', 968814411, 20);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (21, 'Gold Bond Medicated Foot', 'sollicitudin vitae', 919501152, 21);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (22, 'Oxcarbazepine', 'libero quis', 941799689, 22);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (23, 'Sprayology DigestivEase', 'arcu', 963586166, 23);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (24, 'QUERCUS ALBA POLLEN', 'quam', 930906242, 24);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (25, 'PRINCIPAL SECRET', 'pede', 939744797, 25);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (26, 'VOLTAREN', 'ut', 960256590, 26);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (27, 'Telmisartan and Hydrochlorothiazide', 'nibh', 911080590, 27);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (28, 'Triton AB-741', 'cubilia', 922175170, 28);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (29, 'Treatment Set TS350663', 'in', 911592261, 29);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (30, 'NIFEDIPINE', 'vivamus vel', 959163435, 30);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (31, 'Berry Scented Hand Sanitizer', 'bibendum imperdiet', 940920254, 31);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (32, 'Mentholatum Ironman Muscle Spray', 'magna ac', 942988588, 32);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (33, 'EQUUS CABALLUS SKIN', 'ut', 957203579, 33);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (34, 'FASLODEX', 'ante', 941459602, 34);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (35, 'Tanda pearl professional whitening', 'odio porttitor', 954398446, 35);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (36, 'Theo-24', 'cubilia curae', 919773642, 36);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (37, 'DEXTROSE', 'proin interdum', 959608944, 37);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (38, 'PURIXAN', 'pede morbi', 938702844, 38);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (39, 'Kadian', 'vel nisl', 926775610, 39);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (40, 'Dolce and Gabbana The Lift Foundation Soft Sable 180', 'nulla elit', 966851826, 40);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (41, 'Maximum Strength Allergy Sinus', 'in', 917176202, 41);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (42, 'Body Luxuries French Lavender Scented Waterless Anti Bacterial Hand gel', 'euismod', 935209968, 42);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (43, 'Oxygen', 'mauris', 963013193, 43);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (44, 'Desquam-X', 'sed nisl', 957142862, 44);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (45, 'Slash Pine', 'sit', 925665434, 45);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (46, 'Dr. Scholls', 'sit amet', 951244619, 46);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (47, 'mycophenolate mofetil', 'morbi porttitor', 933683174, 47);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (48, 'emmi dent Sodium Fluoride Anticavity Mild', 'mi', 968852184, 48);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (49, 'Good Neighbor Senna', 'tempus', 936394517, 49);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (50, 'Clonidine Hydrochloride', 'sapien sapien', 947423820, 50);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (51, 'Ketorolac Tromethamine', 'vulputate ut', 936693640, 51);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (52, 'FEIBA', 'praesent lectus', 943387014, 52);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (53, 'Glipizide XL', 'vestibulum', 942628974, 53);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (54, 'Povidone Iodine', 'porttitor lorem', 967018993, 54);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (55, 'Naloxone Hydrochloride', 'mauris ullamcorper', 950267467, 55);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (56, 'Topcare Cold Head Congestion Severe', 'vivamus tortor', 964994298, 56);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (57, 'carbidopa, levodopa and entacapone', 'est quam', 931205396, 57);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (58, 'Umcka Menthol', 'augue', 921951006, 58);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (59, 'Bacitracin', 'leo odio', 949131351, 59);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (60, 'CLINIMIX E', 'semper', 949809685, 60);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (61, 'Classic Care Apricot Scrub', 'cras', 940230372, 61);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (62, 'Fluconazole', 'eu', 950918815, 62);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (63, 'TRAMADOL HYDROCHLORIDE', 'accumsan tortor', 957322219, 63);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (64, 'Oxygen', 'aliquam quis', 962510904, 64);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (65, 'Spironolactone', 'ut tellus', 967220996, 65);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (66, 'Ultimate Rescue', 'eros vestibulum', 938561465, 66);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (67, 'HEB', 'maecenas pulvinar', 966087323, 67);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (68, 'Scot-Tussin Senior SF DMEXP', 'vel enim', 942562000, 68);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (69, 'Diazepam', 'vulputate elementum', 922245546, 69);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (70, 'all day pain relief', 'vestibulum', 942927142, 70);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (71, 'Zolpidem Tartrate', 'integer', 931189682, 71);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (72, 'CPDA-1', 'orci', 964261914, 72);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (73, 'Naproxen Sodium', 'non quam', 957712182, 73);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (74, 'Flumazenil', 'ut', 916792520, 74);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (75, 'SOLU-MEDROL', 'lacinia', 960220072, 75);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (76, 'Cough', 'dui proin', 965830741, 76);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (77, 'PLENDIL', 'nulla', 912950657, 77);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (78, 'Ropinirole', 'platea dictumst', 952341614, 78);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (79, 'Simvastatin', 'varius ut', 947675360, 79);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (80, 'Alcohol Prep Pad', 'magna', 910493435, 80);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (81, 'Hydrocortisone', 'non ligula', 954944116, 81);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (82, 'Adidas', 'purus eu', 955823506, 82);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (83, 'Gleevec', 'sapien cum', 927888370, 83);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (84, 'Crest Complete Multi-Benefit', 'viverra pede', 918268528, 84);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (85, 'FALMINA', 'faucibus orci', 920365721, 85);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (86, 'Up and Up Sensitive Toothpaste Whitening', 'eget eleifend', 941399057, 86);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (87, 'Carroll Ultrex Antimicrobial Wipes', 'suscipit nulla', 921418915, 87);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (88, 'Menopause Relief', 'convallis morbi', 937940378, 88);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (89, 'SAFEWAY CARE', 'nulla', 963342869, 89);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (90, 'miconazole 3', 'vivamus metus', 944240250, 90);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (91, 'Diclofenac Potassium', 'felis sed', 911196420, 91);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (92, 'Simvastatin', 'accumsan', 937499164, 92);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (93, 'Ortho-Nesic With Capsaicin', 'orci nullam', 935224850, 93);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (94, 'phentermine hydrochloride', 'pede libero', 936010345, 94);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (95, 'Loratadine', 'habitasse', 925739151, 95);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (96, 'Manefit Beauty Planner Lily Whitening Brightening Mask', 'cursus', 938187180, 96);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (97, 'Witch Hazel', 'cras', 916259483, 97);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (98, 'Alprazolam', 'erat eros', 918988054, 98);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (99, 'Pollens - Weeds and Garden Plants, Ragweed, Giant Ambrosia trifida', 'faucibus orci', 960459232, 99);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (100, 'Cefuroxime Axetil', 'morbi non', 960039647, 100);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (101, 'FORTAZ', 'rhoncus mauris', 940471075, 101);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (102, 'Truist Sunscreen Moisturizer', 'donec', 931008986, 102);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (103, 'SHISEIDO ADVANCED HYDRO-LIQUID COMPACT (REFILL)', 'pretium', 925419434, 103);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (104, 'Glyburide', 'vehicula consequat', 941494374, 104);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (105, 'Paroxetine', 'iaculis', 968144501, 105);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (106, 'quetiapine fumarate', 'ligula', 951019687, 106);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (107, 'Metoprolol Succinate', 'mus vivamus', 943589203, 107);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (108, 'Mefenamic Acid', 'sagittis sapien', 917959022, 108);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (109, 'Acetaminophen And Codeine', 'cum sociis', 968242468, 109);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (110, 'Hydralazine Hydrochloride', 'nullam', 968461519, 110);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (111, 'Neostigmine Methylsulfate', 'odio cras', 911939525, 111);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (112, 'Doxy 100', 'etiam', 935565607, 112);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (113, 'HAND SANITIZING', 'justo morbi', 918086943, 113);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (114, 'Probenecid', 'sociis natoque', 929856295, 114);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (115, 'Lidocaine Hydrochloride and Epinephrine', 'nisi', 962256243, 115);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (116, 'Naproxen Sodium', 'venenatis', 924224043, 116);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (117, 'Primidone', 'ut erat', 913251084, 117);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (118, 'Wok Lok Pain Relieving Oil', 'lobortis', 937868562, 118);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (119, 'Infants Ibuprofen', 'duis', 918930395, 119);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (120, 'Flavoxate Hydrochloride', 'sed interdum', 914168346, 120);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (121, 'Hydrochlorothiazide', 'proin risus', 935219536, 121);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (122, 'Promethazine Hydrochloride', 'nunc proin', 962411535, 122);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (123, 'Nasal Decongestant', 'venenatis tristique', 942239321, 123);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (124, 'Crest Sensitivity', 'tortor', 933092582, 124);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (125, 'IDOLE CARROT', 'morbi sem', 951328404, 125);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (126, 'Lansoprazole', 'eu', 938847862, 126);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (127, 'Isosorbide Dinitrate', 'ante ipsum', 944197390, 127);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (128, 'ABILIFY', 'fusce lacus', 948619300, 128);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (129, 'Acute Care Kit', 'nulla', 927207845, 129);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (130, 'Fluticasone Propionate', 'quisque', 947989397, 130);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (131, 'Methocarbamol', 'eget', 923098281, 131);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (132, 'Diethylpropion HCl Controlled-Release', 'ullamcorper augue', 947646416, 132);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (133, 'Senna Plus', 'turpis donec', 921137327, 133);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (134, 'Terazosin', 'blandit', 922496086, 134);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (135, 'Ondansetron', 'quam', 934006125, 135);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (136, 'Norpace', 'elit proin', 951959254, 136);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (137, 'Kogenate FS', 'nulla', 953562331, 137);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (138, 'Justice Mixed Berry ANTI BAC HAND SANITIZER', 'nam', 931230203, 138);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (139, 'Ruta Graveolens Kit Refill', 'justo', 960590826, 139);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (140, 'PERTZYE', 'odio in', 928987911, 140);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (141, 'Bupropion Hydrochloride', 'sapien', 923958377, 141);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (142, 'flu and severe cold and cough', 'at nunc', 951276396, 142);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (143, 'Ciprofloxacin Hydrochloride', 'nisl ut', 960962947, 143);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (144, 'Olay Total Effects Tone Correcting', 'aenean fermentum', 912380094, 144);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (145, 'Anti-Bacterial Moisturizing Hand', 'porta', 911875777, 145);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (146, 'topcare childrens mucus relief multi symptom cold', 'nisi vulputate', 934405159, 146);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (147, 'Mag Phos', 'dictumst etiam', 950659393, 147);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (148, 'VOLTAREN', 'nulla justo', 956742685, 148);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (149, 'CareAll Medicated Chest Rub', 'sed justo', 965924359, 149);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (150, 'Effervescent Cold Relief', 'vulputate', 940880103, 150);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (151, 'Prednisone', 'semper', 943532669, 151);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (152, 'UV LOCK ULTRA MILK SUN', 'quam pharetra', 922758142, 152);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (153, 'ESIKA', 'praesent blandit', 953371555, 153);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (154, 'NARS ALL DAY LUMINOUS FOUNDATION', 'in', 929413319, 154);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (155, 'Activase', 'libero', 966754684, 155);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (156, 'Propranolol Hydrochloride', 'elit ac', 914083147, 156);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (157, 'Lactulose', 'amet', 953397080, 157);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (158, 'MENOMUNE - A/C/Y/W-135 COMBINED', 'pede', 930803076, 158);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (159, 'Zolpidem tartrate', 'orci', 919919936, 159);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (160, 'Risperidone', 'justo', 963458166, 160);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (161, 'Head and Shoulders', 'lorem ipsum', 913264376, 161);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (162, 'JANUMET', 'odio justo', 934529222, 162);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (163, 'Oxycodone and Acetaminophen', 'nulla', 948319140, 163);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (164, 'Pepcid', 'vestibulum rutrum', 954743749, 164);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (165, 'Fenofibrate', 'eu', 955254439, 165);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (166, 'Assured Childrens Cold and Cough', 'mattis', 948436712, 166);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (167, 'Fig', 'odio', 955739023, 167);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (168, 'Smart Sense Hemorrhoidal', 'lacus', 944527095, 168);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (169, 'Rabbit Epithelium', 'suscipit', 931519733, 169);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (170, 'Purminerals 4 in 1 Makeup SPF 15 Medium Dark', 'ipsum', 919773593, 170);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (171, 'Ibuprofen', 'natoque', 940629898, 171);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (172, 'CYCLOBENZAPRINE HYROCHLORIDE', 'suscipit ligula', 956108467, 172);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (173, 'VOLTAREN', 'donec ut', 936379768, 173);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (174, 'Sertraline', 'ut suscipit', 947073755, 174);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (175, 'Melissa Cold Sore Relief', 'augue aliquam', 926058597, 175);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (176, 'Isoniazid', 'id', 910210697, 176);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (177, 'ENTEX LQ', 'mauris laoreet', 933338237, 177);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (178, 'Cefazolin', 'lobortis est', 947552941, 178);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (179, 'NBB', 'est', 936701450, 179);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (180, 'Dysport', 'gravida nisi', 931553819, 180);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (181, 'Arnica', 'vulputate luctus', 963563803, 181);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (182, 'Cetirizine Hydrochloride', 'phasellus', 946361223, 182);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (183, 'Indomethacin', 'cum', 967291397, 183);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (184, 'Oxcarbazepine', 'augue', 943229884, 184);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (185, 'Ampicillin', 'morbi vel', 917958706, 185);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (186, 'Tetracycline Hydrochloride', 'orci', 932633979, 186);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (187, 'Clear Proof Acne System', 'purus aliquet', 919245538, 187);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (188, 'Lisinopril', 'rhoncus dui', 951102729, 188);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (189, 'TERRACOTTA JOLI TEINT BEAUTIFYING FOUNDATION WITH SUNSCREEN SUN-KISSED, HEALTHY GLOW BROAD SPECTRUM SPF 20 LIGHT', 'nulla ut', 932622109, 189);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (190, 'Ravicti', 'turpis eget', 913920823, 190);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (191, 'Ondansetron Hydrochloride', 'non', 915226826, 191);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (192, 'Alka-Seltzer Plus Fast Packs Cold and Flu Formula', 'a odio', 959008827, 192);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (193, 'Rowasa', 'accumsan odio', 945514181, 193);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (194, 'ACREMONIUM STRICTUM', 'scelerisque', 933356545, 194);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (195, 'Estradiol', 'suscipit nulla', 923173060, 195);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (196, 'Moderiba', 'morbi non', 966873468, 196);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (197, 'Amlodipine Besylate', 'sapien non', 932229835, 197);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (198, 'Ondansetron', 'quis', 969219961, 198);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (199, 'Amoxicillin', 'vitae', 959235754, 199);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (200, 'RUE21 Apple Spice Antibacterial Hand Sanitizer', 'tortor id', 923516387, 200);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (201, 'Clarithromycin', 'condimentum', 934525959, 201);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (202, 'Aspartame MSG Detox', 'proin', 912774745, 202);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (203, 'Kroger Aloe Vera', 'nullam', 944135425, 203);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (204, 'Hydrocodone Bitartrate and Acetaminophen', 'tortor sollicitudin', 934202335, 204);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (205, 'Nighttime Sleep Aid', 'rhoncus', 926607308, 205);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (206, 'Pink Bismuth Maximum Strength', 'cubilia curae', 965622544, 206);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (207, 'IBS Irritable Bowel Syndrome Relief', 'lorem', 932537646, 207);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (208, 'SHISEIDO ADVANCED HYDRO-LIQUID COMPACT (REFILL)', 'nullam', 965129347, 208);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (209, 'chlortab', 'amet eleifend', 912461496, 209);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (210, 'SHISEIDO SHEER AND PERFECT COMPACT (REFILL)', 'diam vitae', 943210890, 210);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (211, 'Doxazosin', 'ligula nec', 953240206, 211);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (212, 'WARFARIN SODIUM', 'sed interdum', 916502990, 212);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (213, 'Fluoxetine', 'felis', 943651316, 213);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (214, 'Vineyard Antibacterial Foaming Hand Wash', 'dis parturient', 946400297, 214);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (215, 'PEANUT FOOD', 'morbi', 922317676, 215);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (216, 'Metoprolol Tartrate', 'eu', 922159660, 216);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (217, 'Estradiol', 'vulputate', 950948694, 217);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (218, 'Rolaids Regular Strength- Cherry', 'felis eu', 941031762, 218);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (219, 'Bupropion Hydrochloride', 'bibendum morbi', 919906486, 219);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (220, 'Meprobamate', 'donec diam', 942501516, 220);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (221, 'Dilantin-125', 'mauris ullamcorper', 941992208, 221);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (222, 'Clotrimazole Antifungal', 'ipsum', 913199873, 222);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (223, 'Denti-Care', 'eros', 946558912, 223);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (224, 'Childrens Cold and Allergy', 'donec', 920304243, 224);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (225, 'Citalopram Hydrobromide', 'porta volutpat', 926434485, 225);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (226, 'Loxapine', 'id', 925894093, 226);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (227, 'Relaxoforce', 'ante ipsum', 968181475, 227);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (228, 'CEFPROZIL', 'vel', 947020697, 228);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (229, 'Tranexamic Acid', 'justo in', 956877307, 229);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (230, 'LE TECHNIQ', 'nunc', 926177479, 230);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (231, 'PERCOCET', 'in faucibus', 914430597, 231);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (232, 'APIS MELLIFICA', 'nunc', 939753213, 232);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (233, 'Red Maple', 'morbi', 965344624, 233);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (234, 'D3 Organ Support', 'mauris non', 969147369, 234);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (235, 'Childrens Acetaminophen', 'purus', 934492315, 235);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (236, 'Donepezil Hydrochloride', 'cursus', 913336809, 236);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (237, 'Lidocaine Hydrochloride', 'congue elementum', 913354851, 237);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (238, 'Benztropine Mesylate', 'pretium', 919424626, 238);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (239, 'A-METHAPRED', 'justo', 913139934, 239);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (240, 'Dr. J.I.s Arthritis Plus Gel', 'mauris laoreet', 912749256, 240);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (241, 'Ketamine Hydrochloride', 'eu', 943521525, 241);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (242, 'Childrens Pain and Fever', 'scelerisque', 942064129, 242);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (243, 'Niravam', 'non', 945423638, 243);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (244, 'Alphanate', 'viverra diam', 954642323, 244);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (245, 'MALE-PROS', 'lobortis', 955605204, 245);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (246, 'Rouge Dior 650 Peach Serum', 'quis', 917289337, 246);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (247, '50 Person ANSI', 'hac habitasse', 967857703, 247);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (248, 'Bite Beauty SPF 15 Sheer Balm', 'placerat praesent', 932898703, 248);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (249, 'doxazosin', 'turpis', 961031951, 249);
insert into departamento (id, nome, descricao, telefone, tipo_departamento_id) values (250, 'Brome Grass', 'cum sociis', 956722244, 250);
