insert into estado_matricula (id, nome, descricao) values (1, 'Bazaarvoice, Inc.', '2025-10-04');
insert into estado_matricula (id, nome, descricao) values (2, 'CMS Energy Corporation', '2025-04-09');
insert into estado_matricula (id, nome, descricao) values (3, 'Annaly Capital Management Inc', '2025-03-16');
insert into estado_matricula (id, nome, descricao) values (4, 'Stanley Black & Decker, Inc.', '2025-06-27');
insert into estado_matricula (id, nome, descricao) values (5, 'Harvest Capital Credit Corporation', '2025-11-21');
insert into estado_matricula (id, nome, descricao) values (6, 'PowerShares S&P SmallCap Information Technology Portfolio', '2025-10-09');
insert into estado_matricula (id, nome, descricao) values (7, 'MagneGas Corporation', '2025-01-01');
insert into estado_matricula (id, nome, descricao) values (8, 'Cerulean Pharma Inc.', '2025-06-25');
insert into estado_matricula (id, nome, descricao) values (9, '1347 Property Insurance Holdings, Inc.', '2024-12-19');
insert into estado_matricula (id, nome, descricao) values (10, 'GGP Inc.', '2025-11-08');
insert into estado_matricula (id, nome, descricao) values (11, 'CYS Investments, Inc.', '2025-03-10');
insert into estado_matricula (id, nome, descricao) values (12, 'Twenty-First Century Fox, Inc.', '2024-10-24');
insert into estado_matricula (id, nome, descricao) values (13, 'Amphenol Corporation', '2024-12-03');
insert into estado_matricula (id, nome, descricao) values (14, 'Rice Energy Inc.', '2024-12-23');
insert into estado_matricula (id, nome, descricao) values (15, 'State National Companies, Inc.', '2025-08-08');
insert into estado_matricula (id, nome, descricao) values (16, 'State Street Corporation', '2024-11-21');
insert into estado_matricula (id, nome, descricao) values (17, 'Tekla Life Sciences Investors', '2025-02-09');
insert into estado_matricula (id, nome, descricao) values (18, 'Guaranty Bancshares, Inc.', '2025-06-06');
insert into estado_matricula (id, nome, descricao) values (19, 'Osisko Gold Royalties Ltd', '2025-02-22');
insert into estado_matricula (id, nome, descricao) values (20, 'Apartment Investment and Management Company', '2025-12-03');
insert into estado_matricula (id, nome, descricao) values (21, 'Entergy Texas Inc', '2025-08-12');
insert into estado_matricula (id, nome, descricao) values (22, 'LivaNova PLC', '2024-11-10');
insert into estado_matricula (id, nome, descricao) values (23, 'Lake Shore Bancorp, Inc.', '2024-12-20');
insert into estado_matricula (id, nome, descricao) values (24, 'Resolute Forest Products Inc.', '2025-05-04');
insert into estado_matricula (id, nome, descricao) values (25, 'Salesforce.com Inc', '2025-09-15');
insert into estado_matricula (id, nome, descricao) values (26, 'Zion Oil & Gas Inc', '2025-02-10');
insert into estado_matricula (id, nome, descricao) values (27, 'Great Ajax Corp.', '2024-10-22');
insert into estado_matricula (id, nome, descricao) values (28, 'Viveve Medical, Inc.', '2025-03-21');
insert into estado_matricula (id, nome, descricao) values (29, 'Imperva, Inc.', '2025-08-29');
insert into estado_matricula (id, nome, descricao) values (30, 'Uni-Pixel, Inc.', '2025-02-05');
insert into estado_matricula (id, nome, descricao) values (31, 'Westlake Chemical Corporation', '2025-02-20');
insert into estado_matricula (id, nome, descricao) values (32, 'First Trust NASDAQ Clean Edge Green Energy Index Fund', '2025-07-27');
insert into estado_matricula (id, nome, descricao) values (33, 'Select Energy Services, Inc.', '2024-10-10');
insert into estado_matricula (id, nome, descricao) values (34, 'First Citizens BancShares, Inc.', '2025-02-16');
insert into estado_matricula (id, nome, descricao) values (35, 'Lennox International, Inc.', '2025-09-17');
insert into estado_matricula (id, nome, descricao) values (36, 'Banner Corporation', '2025-08-09');
insert into estado_matricula (id, nome, descricao) values (37, 'Centene Corporation', '2025-09-25');
insert into estado_matricula (id, nome, descricao) values (38, 'John Wiley & Sons, Inc.', '2025-10-20');
insert into estado_matricula (id, nome, descricao) values (39, 'Fenix Parts, Inc.', '2025-03-09');
insert into estado_matricula (id, nome, descricao) values (40, 'Cray Inc', '2025-12-01');
insert into estado_matricula (id, nome, descricao) values (41, 'Hostess Brands, Inc.', '2025-11-28');
insert into estado_matricula (id, nome, descricao) values (42, 'KMG Chemicals, Inc.', '2025-03-28');
insert into estado_matricula (id, nome, descricao) values (43, 'PHH Corp', '2025-03-25');
insert into estado_matricula (id, nome, descricao) values (44, 'Acadia Healthcare Company, Inc.', '2025-07-07');
insert into estado_matricula (id, nome, descricao) values (45, 'Meridian Bioscience Inc.', '2025-05-02');
insert into estado_matricula (id, nome, descricao) values (46, 'Liberty Media Corporation', '2025-10-30');
insert into estado_matricula (id, nome, descricao) values (47, 'First Cash, Inc.', '2025-08-13');
insert into estado_matricula (id, nome, descricao) values (48, 'Benefitfocus, Inc.', '2025-03-25');
insert into estado_matricula (id, nome, descricao) values (49, 'New Ireland Fund, Inc. (The)', '2025-10-02');
insert into estado_matricula (id, nome, descricao) values (50, 'Valero Energy Corporation', '2025-11-19');
insert into estado_matricula (id, nome, descricao) values (51, 'TFS Financial Corporation', '2025-12-18');
insert into estado_matricula (id, nome, descricao) values (52, 'Xenetic Biosciences, Inc.', '2025-04-03');
insert into estado_matricula (id, nome, descricao) values (53, 'Bassett Furniture Industries, Incorporated', '2025-10-01');
insert into estado_matricula (id, nome, descricao) values (54, 'Envision Healthcare Corporation', '2025-10-01');
insert into estado_matricula (id, nome, descricao) values (55, 'AstroNova, Inc.', '2025-07-31');
insert into estado_matricula (id, nome, descricao) values (56, 'DDR Corp.', '2025-07-09');
insert into estado_matricula (id, nome, descricao) values (57, 'MoSys, Inc.', '2025-10-07');
insert into estado_matricula (id, nome, descricao) values (58, 'Mitcham Industries, Inc.', '2025-09-27');
insert into estado_matricula (id, nome, descricao) values (59, 'Nustar Energy L.P.', '2025-07-06');
insert into estado_matricula (id, nome, descricao) values (60, 'John Wiley & Sons, Inc.', '2024-12-25');
insert into estado_matricula (id, nome, descricao) values (61, 'Preferred Bank', '2025-07-21');
insert into estado_matricula (id, nome, descricao) values (62, 'Potlatch Corporation', '2025-02-15');
insert into estado_matricula (id, nome, descricao) values (63, 'iStar Financial Inc.', '2025-07-22');
insert into estado_matricula (id, nome, descricao) values (64, 'Blackrock MuniHoldings New York Quality Fund, Inc.', '2024-12-13');
insert into estado_matricula (id, nome, descricao) values (65, 'Vantage Energy Acquisition Corp.', '2024-10-27');
insert into estado_matricula (id, nome, descricao) values (66, 'Agilent Technologies, Inc.', '2025-05-18');
insert into estado_matricula (id, nome, descricao) values (67, 'Wipro Limited', '2025-03-05');
insert into estado_matricula (id, nome, descricao) values (68, 'Ritter Pharmaceuticals, Inc.', '2025-02-09');
insert into estado_matricula (id, nome, descricao) values (69, 'ClearBridge Energy MLP Total Return Fund Inc.', '2025-10-25');
insert into estado_matricula (id, nome, descricao) values (70, 'DineEquity, Inc', '2025-04-10');
insert into estado_matricula (id, nome, descricao) values (71, 'America Movil, S.A.B. de C.V.', '2025-12-17');
insert into estado_matricula (id, nome, descricao) values (72, 'Amplify Snack Brands, inc.', '2024-10-21');
insert into estado_matricula (id, nome, descricao) values (73, 'Wells Fargo & Company', '2025-05-04');
insert into estado_matricula (id, nome, descricao) values (74, 'Teekay Offshore Partners L.P.', '2025-05-14');
insert into estado_matricula (id, nome, descricao) values (75, 'E*TRADE Financial Corporation', '2025-08-21');
insert into estado_matricula (id, nome, descricao) values (76, 'Cohen & Steers Limited Duration Preferred and Income Fund, Inc', '2025-03-05');
insert into estado_matricula (id, nome, descricao) values (77, 'JMP Group LLC', '2025-02-24');
insert into estado_matricula (id, nome, descricao) values (78, 'Party City Holdco Inc.', '2025-04-19');
insert into estado_matricula (id, nome, descricao) values (79, 'Zhaopin Limited', '2025-03-20');
insert into estado_matricula (id, nome, descricao) values (80, 'Teekay LNG Partners L.P.', '2025-08-18');
insert into estado_matricula (id, nome, descricao) values (81, 'Natural Alternatives International, Inc.', '2025-09-04');
insert into estado_matricula (id, nome, descricao) values (82, 'Stryker Corporation', '2025-02-23');
insert into estado_matricula (id, nome, descricao) values (83, 'Manulife Financial Corp', '2025-04-09');
insert into estado_matricula (id, nome, descricao) values (84, 'Southern Missouri Bancorp, Inc.', '2024-12-17');
insert into estado_matricula (id, nome, descricao) values (85, 'Special Opportunities Fund Inc.', '2025-08-10');
insert into estado_matricula (id, nome, descricao) values (86, 'Microsoft Corporation', '2025-03-26');
insert into estado_matricula (id, nome, descricao) values (87, 'CombiMatrix Corporation', '2025-01-12');
insert into estado_matricula (id, nome, descricao) values (88, 'Criteo S.A.', '2025-08-31');
insert into estado_matricula (id, nome, descricao) values (89, 'Discover Financial Services', '2025-08-13');
insert into estado_matricula (id, nome, descricao) values (90, 'Pier 1 Imports, Inc.', '2025-06-22');
insert into estado_matricula (id, nome, descricao) values (91, 'E.W. Scripps Company (The)', '2025-10-26');
insert into estado_matricula (id, nome, descricao) values (92, 'Darling Ingredients Inc.', '2025-11-03');
insert into estado_matricula (id, nome, descricao) values (93, 'CHS Inc', '2024-12-23');
insert into estado_matricula (id, nome, descricao) values (94, 'iShares FTSE EPRA/NAREIT Europe Index Fund', '2024-12-22');
insert into estado_matricula (id, nome, descricao) values (95, 'Bio-Techne Corp', '2025-05-08');
insert into estado_matricula (id, nome, descricao) values (96, 'Saratoga Investment Corp', '2025-07-22');
insert into estado_matricula (id, nome, descricao) values (97, 'Streamline Health Solutions, Inc.', '2025-04-02');
insert into estado_matricula (id, nome, descricao) values (98, 'Lindsay Corporation', '2024-10-13');
insert into estado_matricula (id, nome, descricao) values (99, 'Total System Services, Inc.', '2025-07-22');
insert into estado_matricula (id, nome, descricao) values (100, 'Kansas City Southern', '2025-10-02');
insert into estado_matricula (id, nome, descricao) values (101, 'Verso Corporation', '2025-07-06');
insert into estado_matricula (id, nome, descricao) values (102, 'Broadridge Financial Solutions, Inc.', '2025-01-17');
insert into estado_matricula (id, nome, descricao) values (103, 'Terra Nitrogen Company, L.P.', '2024-12-01');
insert into estado_matricula (id, nome, descricao) values (104, 'A V Homes, Inc.', '2025-03-18');
insert into estado_matricula (id, nome, descricao) values (105, 'Pitney Bowes Inc.', '2025-08-09');
insert into estado_matricula (id, nome, descricao) values (106, 'BlackBerry Limited', '2025-10-26');
insert into estado_matricula (id, nome, descricao) values (107, 'Hooker Furniture Corporation', '2025-11-22');
insert into estado_matricula (id, nome, descricao) values (108, 'Park City Group, Inc.', '2025-06-03');
insert into estado_matricula (id, nome, descricao) values (109, 'AquaVenture Holdings Limited', '2025-05-25');
insert into estado_matricula (id, nome, descricao) values (110, 'John Hancock Pfd Income Fund II', '2025-07-14');
insert into estado_matricula (id, nome, descricao) values (111, 'Western Digital Corporation', '2025-02-01');
insert into estado_matricula (id, nome, descricao) values (112, 'Green Brick Partners, Inc.', '2025-01-01');
insert into estado_matricula (id, nome, descricao) values (113, 'ING Group, N.V.', '2025-11-05');
insert into estado_matricula (id, nome, descricao) values (114, 'Ingles Markets, Incorporated', '2025-04-27');
insert into estado_matricula (id, nome, descricao) values (115, 'MFA Financial, Inc.', '2024-12-05');
insert into estado_matricula (id, nome, descricao) values (116, 'Clearfield, Inc.', '2024-11-11');
insert into estado_matricula (id, nome, descricao) values (117, 'Rubicon Technology, Inc.', '2025-01-16');
insert into estado_matricula (id, nome, descricao) values (118, 'Consolidated Communications Holdings, Inc.', '2025-01-19');
insert into estado_matricula (id, nome, descricao) values (119, 'MiX Telematics Limited', '2025-12-16');
insert into estado_matricula (id, nome, descricao) values (120, 'Sunrun Inc.', '2025-02-14');
insert into estado_matricula (id, nome, descricao) values (121, 'Banco Santander, S.A.', '2025-10-09');
insert into estado_matricula (id, nome, descricao) values (122, 'Mid-Con Energy Partners, LP', '2025-07-15');
insert into estado_matricula (id, nome, descricao) values (123, 'Northrop Grumman Corporation', '2025-05-23');
insert into estado_matricula (id, nome, descricao) values (124, 'Dick''s Sporting Goods Inc', '2025-01-06');
insert into estado_matricula (id, nome, descricao) values (125, 'Easterly Government Properties, Inc.', '2025-01-26');
insert into estado_matricula (id, nome, descricao) values (126, 'MagneGas Corporation', '2025-05-14');
insert into estado_matricula (id, nome, descricao) values (127, 'Grifols, S.A.', '2025-09-13');
insert into estado_matricula (id, nome, descricao) values (128, 'Union Bankshares Corporation', '2025-06-10');
insert into estado_matricula (id, nome, descricao) values (129, 'PowerShares Nasdaq Internet Portfolio', '2025-03-17');
insert into estado_matricula (id, nome, descricao) values (130, 'CalAmp Corp.', '2025-08-02');
insert into estado_matricula (id, nome, descricao) values (131, 'Forest City Realty Trust, Inc.', '2025-03-15');
insert into estado_matricula (id, nome, descricao) values (132, 'Gabelli Global Small and Mid Cap Value Trust (The)', '2024-11-03');
insert into estado_matricula (id, nome, descricao) values (133, 'BlueStar TA-BIGITech Israel Technology ETF', '2025-04-20');
insert into estado_matricula (id, nome, descricao) values (134, 'Tarena International, Inc.', '2025-11-20');
insert into estado_matricula (id, nome, descricao) values (135, 'IRSA Inversiones Y Representaciones S.A.', '2025-01-15');
insert into estado_matricula (id, nome, descricao) values (136, 'GasLog LP.', '2025-11-09');
insert into estado_matricula (id, nome, descricao) values (137, 'OUTFRONT Media Inc.', '2025-09-25');
insert into estado_matricula (id, nome, descricao) values (138, 'Ocean Power Technologies, Inc.', '2025-04-05');
insert into estado_matricula (id, nome, descricao) values (139, 'Yatra Online, Inc.', '2025-08-28');
insert into estado_matricula (id, nome, descricao) values (140, 'Minerals Technologies Inc.', '2025-10-22');
insert into estado_matricula (id, nome, descricao) values (141, 'Electrum Special Acquisition Corporation', '2025-01-16');
insert into estado_matricula (id, nome, descricao) values (142, 'Tandem Diabetes Care, Inc.', '2025-09-10');
insert into estado_matricula (id, nome, descricao) values (143, 'Euroseas Ltd.', '2024-10-22');
insert into estado_matricula (id, nome, descricao) values (144, 'Splunk Inc.', '2025-09-21');
insert into estado_matricula (id, nome, descricao) values (145, 'ASV Holdings, Inc.', '2025-07-19');
insert into estado_matricula (id, nome, descricao) values (146, 'General Electric Company', '2025-02-23');
insert into estado_matricula (id, nome, descricao) values (147, 'Genworth Financial Inc', '2025-10-07');
insert into estado_matricula (id, nome, descricao) values (148, 'Lake Shore Bancorp, Inc.', '2025-01-01');
insert into estado_matricula (id, nome, descricao) values (149, 'Teligent, Inc.', '2025-06-06');
insert into estado_matricula (id, nome, descricao) values (150, 'Invesco Trust for Investment Grade Municipals', '2025-09-02');
insert into estado_matricula (id, nome, descricao) values (151, 'USG Corporation', '2025-09-24');
insert into estado_matricula (id, nome, descricao) values (152, 'TransAct Technologies Incorporated', '2025-01-14');
insert into estado_matricula (id, nome, descricao) values (153, 'TiGenix', '2025-02-21');
insert into estado_matricula (id, nome, descricao) values (154, 'Arbor Realty Trust', '2025-06-16');
insert into estado_matricula (id, nome, descricao) values (155, 'Tandem Diabetes Care, Inc.', '2025-12-19');
insert into estado_matricula (id, nome, descricao) values (156, 'Paycom Software, Inc.', '2024-11-16');
insert into estado_matricula (id, nome, descricao) values (157, 'ObsEva SA', '2024-11-29');
insert into estado_matricula (id, nome, descricao) values (158, 'Haverty Furniture Companies, Inc.', '2025-08-17');
insert into estado_matricula (id, nome, descricao) values (159, 'Washington Federal, Inc.', '2025-06-30');
insert into estado_matricula (id, nome, descricao) values (160, 'HRG Group, Inc.', '2024-11-24');
insert into estado_matricula (id, nome, descricao) values (161, 'Community Health Systems, Inc.', '2025-06-23');
insert into estado_matricula (id, nome, descricao) values (162, 'Yirendai Ltd.', '2025-03-15');
insert into estado_matricula (id, nome, descricao) values (163, 'BioDelivery Sciences International, Inc.', '2025-08-18');
insert into estado_matricula (id, nome, descricao) values (164, 'Capital One Financial Corporation', '2025-03-08');
insert into estado_matricula (id, nome, descricao) values (165, 'Lsb Industries Inc.', '2025-11-21');
insert into estado_matricula (id, nome, descricao) values (166, 'Nortech Systems Incorporated', '2025-03-01');
insert into estado_matricula (id, nome, descricao) values (167, 'Genpact Limited', '2025-12-02');
insert into estado_matricula (id, nome, descricao) values (168, 'Apollo Investment Corporation', '2025-10-06');
insert into estado_matricula (id, nome, descricao) values (169, 'Matrix Service Company', '2025-10-19');
insert into estado_matricula (id, nome, descricao) values (170, 'National Holdings Corporation', '2025-01-31');
insert into estado_matricula (id, nome, descricao) values (171, 'PetroChina Company Limited', '2025-08-20');
insert into estado_matricula (id, nome, descricao) values (172, 'Bank of America Corporation', '2024-10-14');
insert into estado_matricula (id, nome, descricao) values (173, 'Denbury Resources Inc.', '2025-09-06');
insert into estado_matricula (id, nome, descricao) values (174, 'Deutsche Bank AG', '2025-08-19');
insert into estado_matricula (id, nome, descricao) values (175, 'Paychex, Inc.', '2025-11-29');
insert into estado_matricula (id, nome, descricao) values (176, 'Citizens Holding Company', '2025-01-08');
insert into estado_matricula (id, nome, descricao) values (177, 'XO Group, Inc.', '2025-12-12');
insert into estado_matricula (id, nome, descricao) values (178, 'Invesco Quality Municipal Income Trust', '2024-11-17');
insert into estado_matricula (id, nome, descricao) values (179, 'ObsEva SA', '2025-11-16');
insert into estado_matricula (id, nome, descricao) values (180, 'First Trust Asia Pacific Ex-Japan AlphaDEX Fund', '2025-11-18');
insert into estado_matricula (id, nome, descricao) values (181, 'Pluristem Therapeutics, Inc.', '2025-08-04');
insert into estado_matricula (id, nome, descricao) values (182, 'iShares 0-5 Year Investment Grade Corporate Bond ETF', '2025-05-02');
insert into estado_matricula (id, nome, descricao) values (183, 'VictoryShares US 500 Enhanced Volatility Wtd ETF', '2025-08-09');
insert into estado_matricula (id, nome, descricao) values (184, 'BlackRock Strategic Municipal Trust Inc. (The)', '2024-11-01');
insert into estado_matricula (id, nome, descricao) values (185, 'The Andersons, Inc.', '2025-05-06');
insert into estado_matricula (id, nome, descricao) values (186, 'Aircastle Limited', '2025-01-20');
insert into estado_matricula (id, nome, descricao) values (187, 'China Zenix Auto International Limited', '2025-04-17');
insert into estado_matricula (id, nome, descricao) values (188, 'Solar Capital Ltd.', '2024-12-30');
insert into estado_matricula (id, nome, descricao) values (189, 'Boingo Wireless, Inc.', '2025-10-09');
insert into estado_matricula (id, nome, descricao) values (190, 'Blackrock Muni New York Intermediate Duration Fund Inc', '2025-10-18');
insert into estado_matricula (id, nome, descricao) values (191, 'Upland Software, Inc.', '2025-06-12');
insert into estado_matricula (id, nome, descricao) values (192, 'Southern California Edison Company', '2025-08-30');
insert into estado_matricula (id, nome, descricao) values (193, 'Glaukos Corporation', '2025-12-21');
insert into estado_matricula (id, nome, descricao) values (194, 'Welltower Inc.', '2025-12-05');
insert into estado_matricula (id, nome, descricao) values (195, 'A. Schulman, Inc.', '2025-02-13');
insert into estado_matricula (id, nome, descricao) values (196, 'Vident International Equity Fund', '2025-04-30');
insert into estado_matricula (id, nome, descricao) values (197, 'Willamette Valley Vineyards, Inc.', '2025-12-20');
insert into estado_matricula (id, nome, descricao) values (198, 'TCG BDC, Inc.', '2025-01-28');
insert into estado_matricula (id, nome, descricao) values (199, 'Seadrill Limited', '2025-12-04');
insert into estado_matricula (id, nome, descricao) values (200, 'AzurRx BioPharma, Inc.', '2025-02-01');
insert into estado_matricula (id, nome, descricao) values (201, 'Valvoline Inc.', '2025-12-18');
insert into estado_matricula (id, nome, descricao) values (202, 'Oxford Lane Capital Corp.', '2025-01-09');
insert into estado_matricula (id, nome, descricao) values (203, 'Apptio, Inc.', '2024-10-28');
insert into estado_matricula (id, nome, descricao) values (204, 'W.P. Carey Inc.', '2025-04-17');
insert into estado_matricula (id, nome, descricao) values (205, 'Twilio Inc.', '2025-03-26');
insert into estado_matricula (id, nome, descricao) values (206, 'PowerShares S&P SmallCap Information Technology Portfolio', '2025-04-22');
insert into estado_matricula (id, nome, descricao) values (207, 'Monroe Capital Corporation', '2025-09-25');
insert into estado_matricula (id, nome, descricao) values (208, 'CM Finance Inc', '2025-11-30');
insert into estado_matricula (id, nome, descricao) values (209, 'Ocular Therapeutix, Inc.', '2025-04-25');
insert into estado_matricula (id, nome, descricao) values (210, 'Build-A-Bear Workshop, Inc.', '2024-11-25');
insert into estado_matricula (id, nome, descricao) values (211, 'Bank Of Montreal', '2025-04-11');
insert into estado_matricula (id, nome, descricao) values (212, 'ClearBridge All Cap Growth ETF', '2025-06-30');
insert into estado_matricula (id, nome, descricao) values (213, 'L.B. Foster Company', '2025-03-19');
insert into estado_matricula (id, nome, descricao) values (214, 'Diana Shipping inc.', '2025-07-19');
insert into estado_matricula (id, nome, descricao) values (215, 'iShares Global Infrastructure ETF', '2025-03-03');
insert into estado_matricula (id, nome, descricao) values (216, 'ChinaCache International Holdings Ltd.', '2025-03-24');
insert into estado_matricula (id, nome, descricao) values (217, 'MISONIX, Inc.', '2025-10-12');
insert into estado_matricula (id, nome, descricao) values (218, 'Greenlight Reinsurance, Ltd.', '2024-12-07');
insert into estado_matricula (id, nome, descricao) values (219, 'Eaton Vance Short Diversified Income Fund', '2025-12-16');
insert into estado_matricula (id, nome, descricao) values (220, 'Marlin Business Services Corp.', '2025-07-30');
insert into estado_matricula (id, nome, descricao) values (221, 'Pool Corporation', '2024-12-19');
insert into estado_matricula (id, nome, descricao) values (222, 'eBay Inc.', '2025-03-30');
insert into estado_matricula (id, nome, descricao) values (223, 'Western Asset Variable Rate Strategic Fund Inc.', '2024-10-24');
insert into estado_matricula (id, nome, descricao) values (224, 'The9 Limited', '2024-12-01');
insert into estado_matricula (id, nome, descricao) values (225, 'Crawford & Company', '2025-08-01');
insert into estado_matricula (id, nome, descricao) values (226, 'Harsco Corporation', '2024-10-25');
insert into estado_matricula (id, nome, descricao) values (227, 'Fomento Economico Mexicano S.A.B. de C.V.', '2025-03-04');
insert into estado_matricula (id, nome, descricao) values (228, 'NVE Corporation', '2025-03-25');
insert into estado_matricula (id, nome, descricao) values (229, 'ProShares UltraShort Nasdaq Biotechnology', '2025-06-24');
insert into estado_matricula (id, nome, descricao) values (230, 'DMC Global Inc.', '2025-08-03');
insert into estado_matricula (id, nome, descricao) values (231, 'Valero Energy Corporation', '2025-03-10');
insert into estado_matricula (id, nome, descricao) values (232, 'Annaly Capital Management Inc', '2024-12-09');
insert into estado_matricula (id, nome, descricao) values (233, 'PowerShares S&P SmallCap Health Care Portfolio', '2025-04-28');
insert into estado_matricula (id, nome, descricao) values (234, 'ACI Worldwide, Inc.', '2025-03-04');
insert into estado_matricula (id, nome, descricao) values (235, 'Cyclacel Pharmaceuticals, Inc.', '2025-04-20');
insert into estado_matricula (id, nome, descricao) values (236, 'Hubbell Inc', '2024-11-27');
insert into estado_matricula (id, nome, descricao) values (237, 'Wilhelmina International, Inc.', '2025-02-14');
insert into estado_matricula (id, nome, descricao) values (238, 'Georgia Power Company', '2025-07-31');
insert into estado_matricula (id, nome, descricao) values (239, 'The GDL Fund', '2024-11-12');
insert into estado_matricula (id, nome, descricao) values (240, 'J.C. Penney Company, Inc. Holding Company', '2025-03-06');
insert into estado_matricula (id, nome, descricao) values (241, 'Mattersight Corporation', '2024-11-25');
insert into estado_matricula (id, nome, descricao) values (242, 'Northern Trust Corporation', '2025-10-08');
insert into estado_matricula (id, nome, descricao) values (243, 'Liberty Broadband Corporation', '2025-04-29');
insert into estado_matricula (id, nome, descricao) values (244, 'ICU Medical, Inc.', '2025-09-26');
insert into estado_matricula (id, nome, descricao) values (245, 'Del Taco Restaurants, Inc.', '2024-12-06');
insert into estado_matricula (id, nome, descricao) values (246, 'Unifirst Corporation', '2025-01-31');
insert into estado_matricula (id, nome, descricao) values (247, 'HomeTown Bankshares Corporation', '2025-07-07');
insert into estado_matricula (id, nome, descricao) values (248, 'JetBlue Airways Corporation', '2024-11-23');
insert into estado_matricula (id, nome, descricao) values (249, 'Shutterstock, Inc.', '2024-11-29');
insert into estado_matricula (id, nome, descricao) values (250, 'LendingTree, Inc.', '2025-03-28');
