insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (1, 1, 'pede', '0o777', 902, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (2, 2, 'molestie hendrerit', '0o777', 661, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (3, 3, 'vivamus', '0x1234', 299, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (4, 4, 'quam', '0b1010', 108, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (5, 5, 'et ultrices', '0o777', 958, 'image/png');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (6, 6, 'elit', '0x1234', 4, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (7, 7, 'nisi', '0o777', 556, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (8, 8, 'consequat metus', '0x1234', 47, 'video/quicktime');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (9, 9, 'orci', '0x1234', 163, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (10, 10, 'mi', '0o777', 316, 'video/x-mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (11, 11, 'in tempor', '0o777', 492, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (12, 12, 'consequat nulla', '0x1234', 914, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (13, 13, 'ut', '0xFF00', 501, 'application/msword');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (14, 14, 'potenti', '0x1234', 146, 'video/quicktime');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (15, 15, 'a feugiat', '0o777', 152, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (16, 16, 'natoque', '0x1234', 758, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (17, 17, 'quis', '0x1234', 344, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (18, 18, 'consectetuer adipiscing', '0o777', 915, 'text/plain');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (19, 19, 'amet eros', '0b1010', 974, 'application/pdf');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (20, 20, 'ullamcorper augue', '0xFF00', 121, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (21, 21, 'diam erat', '0b1010', 850, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (22, 22, 'sapien', '0xFF00', 916, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (23, 23, 'non mi', '0o777', 586, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (24, 24, 'tempus sit', '0b1010', 300, 'application/x-msexcel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (25, 25, 'ante', '0x1234', 948, 'application/excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (26, 26, 'turpis', '0xFF00', 717, 'application/vnd.ms-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (27, 27, 'ipsum', '0x1234', 65, 'application/mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (28, 28, 'sit amet', '0xFF00', 823, 'video/x-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (29, 29, 'nascetur ridiculus', '0x1234', 775, 'application/mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (30, 30, 'nisl', '0xFF00', 56, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (31, 31, 'ultrices', '0x1234', 627, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (32, 32, 'molestie hendrerit', '0b1010', 331, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (33, 33, 'eros', '0o777', 98, 'application/msword');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (34, 34, 'enim', '0b1010', 44, 'text/plain');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (35, 35, 'enim lorem', '0xFF00', 944, 'video/avi');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (36, 36, 'aliquet', '0o777', 9, 'text/plain');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (37, 37, 'quisque arcu', '0o777', 189, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (38, 38, 'erat fermentum', '0o777', 53, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (39, 39, 'molestie', '0b1010', 658, 'video/x-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (40, 40, 'aliquam augue', '0b1010', 970, 'image/png');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (41, 41, 'suspendisse potenti', '0o777', 750, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (42, 42, 'lectus', '0o777', 292, 'image/x-tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (43, 43, 'aenean auctor', '0b1010', 693, 'video/avi');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (44, 44, 'lorem ipsum', '0b1010', 322, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (45, 45, 'non quam', '0xFF00', 747, 'application/vnd.ms-powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (46, 46, 'maecenas rhoncus', '0o777', 299, 'application/vnd.ms-powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (47, 47, 'fusce lacus', '0x1234', 492, 'image/x-tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (48, 48, 'phasellus', '0o777', 595, 'application/vnd.ms-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (49, 49, 'dui luctus', '0o777', 404, 'image/pjpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (50, 50, 'bibendum', '0xFF00', 998, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (51, 51, 'in hac', '0o777', 684, 'video/x-mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (52, 52, 'vivamus vel', '0o777', 559, 'image/x-tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (53, 53, 'mauris non', '0b1010', 470, 'image/png');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (54, 54, 'ultrices', '0o777', 887, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (55, 55, 'lobortis est', '0xFF00', 73, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (56, 56, 'dui', '0x1234', 120, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (57, 57, 'convallis', '0o777', 303, 'image/pjpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (58, 58, 'ut odio', '0x1234', 453, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (59, 59, 'lacus', '0o777', 347, 'audio/x-mpeg-3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (60, 60, 'accumsan', '0x1234', 99, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (61, 61, 'morbi', '0o777', 872, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (62, 62, 'sapien', '0x1234', 944, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (63, 63, 'aliquet pulvinar', '0xFF00', 732, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (64, 64, 'posuere', '0xFF00', 278, 'video/quicktime');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (65, 65, 'suscipit nulla', '0xFF00', 524, 'image/pjpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (66, 66, 'sit', '0o777', 537, 'image/x-tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (67, 67, 'euismod scelerisque', '0xFF00', 401, 'application/x-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (68, 68, 'pede justo', '0o777', 737, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (69, 69, 'habitasse', '0xFF00', 644, 'application/pdf');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (70, 70, 'primis', '0b1010', 821, 'image/x-tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (71, 71, 'felis', '0x1234', 73, 'image/pjpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (72, 72, 'aenean', '0x1234', 421, 'application/vnd.ms-powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (73, 73, 'cras', '0b1010', 39, 'application/vnd.ms-powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (74, 74, 'ridiculus mus', '0x1234', 478, 'audio/x-mpeg-3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (75, 75, 'tristique est', '0xFF00', 938, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (76, 76, 'at', '0xFF00', 494, 'video/x-mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (77, 77, 'cras', '0xFF00', 390, 'application/msword');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (78, 78, 'congue', '0x1234', 5, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (79, 79, 'sed tincidunt', '0xFF00', 525, 'application/x-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (80, 80, 'enim', '0o777', 320, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (81, 81, 'nam dui', '0b1010', 682, 'application/pdf');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (82, 82, 'a', '0b1010', 366, 'application/excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (83, 83, 'ultrices phasellus', '0o777', 139, 'application/excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (84, 84, 'sit amet', '0x1234', 789, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (85, 85, 'porttitor lacus', '0o777', 148, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (86, 86, 'arcu', '0b1010', 198, 'video/x-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (87, 87, 'donec dapibus', '0x1234', 951, 'audio/x-mpeg-3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (88, 88, 'commodo', '0xFF00', 118, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (89, 89, 'hac', '0b1010', 697, 'application/msword');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (90, 90, 'placerat', '0o777', 371, 'application/vnd.ms-powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (91, 91, 'ultrices posuere', '0x1234', 692, 'application/x-troff-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (92, 92, 'nisi vulputate', '0xFF00', 545, 'video/avi');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (93, 93, 'ornare consequat', '0xFF00', 89, 'application/x-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (94, 94, 'proin', '0o777', 341, 'application/mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (95, 95, 'dictumst morbi', '0xFF00', 112, 'text/plain');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (96, 96, 'ligula', '0xFF00', 241, 'application/mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (97, 97, 'suscipit', '0o777', 682, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (98, 98, 'habitasse platea', '0x1234', 562, 'audio/x-mpeg-3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (99, 99, 'nam ultrices', '0b1010', 702, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (100, 100, 'pretium nisl', '0b1010', 432, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (101, 101, 'ut', '0x1234', 60, 'application/vnd.ms-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (102, 102, 'curae duis', '0xFF00', 513, 'application/x-msexcel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (103, 103, 'dui', '0xFF00', 823, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (104, 104, 'cum', '0b1010', 104, 'image/tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (105, 105, 'ac', '0o777', 699, 'audio/x-mpeg-3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (106, 106, 'pretium', '0o777', 442, 'image/tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (107, 107, 'enim', '0xFF00', 217, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (108, 108, 'nullam', '0b1010', 184, 'application/pdf');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (109, 109, 'phasellus in', '0x1234', 885, 'video/x-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (110, 110, 'est', '0b1010', 181, 'application/vnd.ms-powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (111, 111, 'rutrum nulla', '0xFF00', 381, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (112, 112, 'pellentesque', '0x1234', 671, 'application/vnd.ms-powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (113, 113, 'praesent blandit', '0o777', 895, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (114, 114, 'praesent', '0b1010', 596, 'application/excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (115, 115, 'arcu', '0o777', 988, 'application/msword');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (116, 116, 'aenean', '0b1010', 524, 'image/tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (117, 117, 'iaculis diam', '0o777', 294, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (118, 118, 'suspendisse potenti', '0xFF00', 417, 'application/x-troff-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (119, 119, 'est lacinia', '0xFF00', 10, 'application/msword');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (120, 120, 'sapien placerat', '0b1010', 234, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (121, 121, 'mauris', '0xFF00', 155, 'application/x-msexcel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (122, 122, 'consectetuer', '0b1010', 340, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (123, 123, 'at', '0xFF00', 315, 'image/pjpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (124, 124, 'metus', '0b1010', 537, 'video/x-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (125, 125, 'nisl nunc', '0o777', 432, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (126, 126, 'nam', '0xFF00', 793, 'video/avi');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (127, 127, 'consequat', '0xFF00', 241, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (128, 128, 'odio in', '0xFF00', 74, 'application/pdf');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (129, 129, 'venenatis non', '0x1234', 73, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (130, 130, 'montes nascetur', '0xFF00', 614, 'image/pjpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (131, 131, 'curabitur in', '0b1010', 312, 'image/png');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (132, 132, 'gravida nisi', '0xFF00', 685, 'image/tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (133, 133, 'tortor risus', '0b1010', 757, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (134, 134, 'dapibus', '0b1010', 226, 'video/avi');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (135, 135, 'mollis', '0o777', 408, 'application/msword');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (136, 136, 'a', '0x1234', 531, 'video/avi');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (137, 137, 'luctus', '0b1010', 712, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (138, 138, 'ipsum primis', '0o777', 447, 'video/x-mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (139, 139, 'dictumst', '0o777', 153, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (140, 140, 'quis', '0x1234', 245, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (141, 141, 'duis', '0b1010', 441, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (142, 142, 'pellentesque', '0xFF00', 236, 'video/quicktime');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (143, 143, 'dapibus augue', '0x1234', 630, 'application/excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (144, 144, 'id', '0x1234', 192, 'text/plain');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (145, 145, 'magna', '0o777', 71, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (146, 146, 'sit amet', '0x1234', 987, 'image/tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (147, 147, 'molestie nibh', '0b1010', 39, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (148, 148, 'mauris', '0xFF00', 6, 'application/pdf');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (149, 149, 'cum', '0xFF00', 779, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (150, 150, 'parturient', '0b1010', 111, 'application/vnd.ms-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (151, 151, 'arcu', '0xFF00', 774, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (152, 152, 'non', '0x1234', 177, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (153, 153, 'nec', '0x1234', 396, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (154, 154, 'nulla ultrices', '0b1010', 579, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (155, 155, 'amet eros', '0xFF00', 848, 'application/mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (156, 156, 'fermentum justo', '0x1234', 510, 'application/x-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (157, 157, 'dapibus duis', '0o777', 18, 'application/x-msexcel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (158, 158, 'odio elementum', '0b1010', 448, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (159, 159, 'blandit', '0x1234', 973, 'image/pjpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (160, 160, 'quisque', '0b1010', 641, 'application/x-msexcel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (161, 161, 'nunc proin', '0x1234', 828, 'audio/x-mpeg-3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (162, 162, 'ut', '0o777', 532, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (163, 163, 'cum sociis', '0o777', 731, 'image/png');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (164, 164, 'blandit ultrices', '0o777', 360, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (165, 165, 'vestibulum', '0x1234', 647, 'application/x-troff-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (166, 166, 'consequat varius', '0o777', 786, 'text/plain');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (167, 167, 'libero', '0x1234', 621, 'video/x-mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (168, 168, 'in', '0xFF00', 998, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (169, 169, 'lacus', '0b1010', 434, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (170, 170, 'lobortis convallis', '0o777', 785, 'application/excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (171, 171, 'adipiscing molestie', '0b1010', 106, 'image/pjpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (172, 172, 'aliquet pulvinar', '0b1010', 149, 'application/excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (173, 173, 'dapibus augue', '0b1010', 98, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (174, 174, 'ut massa', '0x1234', 988, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (175, 175, 'molestie', '0x1234', 980, 'application/vnd.ms-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (176, 176, 'quam turpis', '0b1010', 10, 'application/mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (177, 177, 'faucibus orci', '0b1010', 235, 'application/x-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (178, 178, 'duis faucibus', '0b1010', 608, 'video/x-mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (179, 179, 'morbi', '0o777', 978, 'application/mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (180, 180, 'turpis eget', '0o777', 880, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (181, 181, 'vel ipsum', '0x1234', 942, 'text/plain');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (182, 182, 'augue quam', '0o777', 583, 'image/x-tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (183, 183, 'tellus nisi', '0x1234', 249, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (184, 184, 'quis augue', '0xFF00', 725, 'application/x-msexcel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (185, 185, 'sapien urna', '0o777', 126, 'image/png');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (186, 186, 'pede', '0b1010', 450, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (187, 187, 'ultrices', '0x1234', 489, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (188, 188, 'rutrum rutrum', '0x1234', 420, 'application/vnd.ms-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (189, 189, 'at', '0o777', 917, 'image/gif');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (190, 190, 'quisque', '0o777', 447, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (191, 191, 'luctus', '0b1010', 351, 'application/x-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (192, 192, 'eleifend', '0x1234', 127, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (193, 193, 'morbi non', '0x1234', 431, 'video/x-mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (194, 194, 'leo odio', '0xFF00', 961, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (195, 195, 'volutpat', '0xFF00', 496, 'application/x-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (196, 196, 'vestibulum rutrum', '0x1234', 989, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (197, 197, 'bibendum', '0xFF00', 803, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (198, 198, 'quisque porta', '0b1010', 316, 'video/x-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (199, 199, 'sodales scelerisque', '0b1010', 892, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (200, 200, 'sit', '0xFF00', 761, 'text/plain');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (201, 201, 'vel', '0o777', 404, 'video/x-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (202, 202, 'vel', '0b1010', 938, 'application/x-troff-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (203, 203, 'eu felis', '0xFF00', 563, 'video/mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (204, 204, 'tempor', '0b1010', 430, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (205, 205, 'mollis', '0xFF00', 70, 'application/pdf');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (206, 206, 'nulla ac', '0xFF00', 627, 'application/vnd.ms-powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (207, 207, 'posuere cubilia', '0x1234', 490, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (208, 208, 'mauris', '0x1234', 867, 'image/pjpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (209, 209, 'vivamus vel', '0x1234', 238, 'image/jpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (210, 210, 'cursus id', '0xFF00', 203, 'text/plain');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (211, 211, 'porta volutpat', '0b1010', 217, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (212, 212, 'sollicitudin vitae', '0xFF00', 938, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (213, 213, 'volutpat in', '0xFF00', 824, 'application/x-troff-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (214, 214, 'amet', '0xFF00', 37, 'application/x-troff-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (215, 215, 'est', '0xFF00', 832, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (216, 216, 'a pede', '0xFF00', 952, 'video/quicktime');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (217, 217, 'potenti', '0o777', 12, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (218, 218, 'non quam', '0x1234', 23, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (219, 219, 'mattis', '0o777', 268, 'video/avi');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (220, 220, 'duis faucibus', '0o777', 744, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (221, 221, 'augue', '0x1234', 99, 'application/mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (222, 222, 'mattis', '0b1010', 513, 'application/vnd.ms-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (223, 223, 'nulla dapibus', '0o777', 14, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (224, 224, 'consectetuer eget', '0o777', 364, 'video/avi');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (225, 225, 'ut nulla', '0x1234', 947, 'application/x-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (226, 226, 'tempor convallis', '0b1010', 689, 'video/msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (227, 227, 'nam', '0x1234', 864, 'application/x-msexcel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (228, 228, 'penatibus', '0o777', 686, 'image/x-tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (229, 229, 'mauris', '0b1010', 52, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (230, 230, 'enim', '0xFF00', 635, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (231, 231, 'tincidunt', '0o777', 50, 'application/x-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (232, 232, 'consequat', '0o777', 418, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (233, 233, 'a odio', '0x1234', 425, 'image/png');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (234, 234, 'eu felis', '0b1010', 965, 'application/vnd.ms-powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (235, 235, 'vestibulum', '0xFF00', 686, 'application/powerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (236, 236, 'donec', '0x1234', 155, 'image/pjpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (237, 237, 'odio condimentum', '0xFF00', 974, 'image/png');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (238, 238, 'interdum eu', '0xFF00', 377, 'application/x-msexcel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (239, 239, 'duis aliquam', '0xFF00', 237, 'image/x-tiff');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (240, 240, 'duis bibendum', '0x1234', 399, 'audio/mpeg3');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (241, 241, 'id consequat', '0b1010', 17, 'video/x-mpeg');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (242, 242, 'sem', '0o777', 309, 'video/x-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (243, 243, 'aenean', '0o777', 350, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (244, 244, 'sed magna', '0o777', 710, 'application/vnd.ms-excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (245, 245, 'sapien non', '0xFF00', 76, 'application/excel');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (246, 246, 'imperdiet nullam', '0o777', 256, 'video/avi');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (247, 247, 'curae mauris', '0b1010', 589, 'application/x-troff-msvideo');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (248, 248, 'dui', '0x1234', 969, 'application/msword');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (249, 249, 'nulla pede', '0x1234', 815, 'application/x-mspowerpoint');
insert into ficheiro_entrega (id, entrega_id, nome, ficheiro, tamanho, tipo) values (250, 250, 'sapien', '0xFF00', 302, 'audio/mpeg3');
