insert into funcao_docente (id, nome, descricao) values (1, 'Fabien Folger', 'consequat ut');
insert into funcao_docente (id, nome, descricao) values (2, 'Cad Pedro', 'sapien urna');
insert into funcao_docente (id, nome, descricao) values (3, 'Dagny Musslewhite', 'platea');
insert into funcao_docente (id, nome, descricao) values (4, 'Maxwell McLeish', 'tellus');
insert into funcao_docente (id, nome, descricao) values (5, 'Brianne Bice', 'sit amet');
insert into funcao_docente (id, nome, descricao) values (6, 'Sissie Skein', 'a ipsum');
insert into funcao_docente (id, nome, descricao) values (7, 'Brnaby Lisle', 'nibh');
insert into funcao_docente (id, nome, descricao) values (8, 'Doug Nossent', 'odio donec');
insert into funcao_docente (id, nome, descricao) values (9, 'Irving Gloy', 'odio justo');
insert into funcao_docente (id, nome, descricao) values (10, 'Shauna Hasslocher', 'magnis dis');
insert into funcao_docente (id, nome, descricao) values (11, 'Corrie Abramsky', 'semper');
insert into funcao_docente (id, nome, descricao) values (12, 'Emmie Fairs', 'convallis');
insert into funcao_docente (id, nome, descricao) values (13, 'Doralia Shuttlewood', 'fusce posuere');
insert into funcao_docente (id, nome, descricao) values (14, 'Caresse Gritsunov', 'pulvinar');
insert into funcao_docente (id, nome, descricao) values (15, 'Wileen Boshere', 'rhoncus');
insert into funcao_docente (id, nome, descricao) values (16, 'Anneliese Fullman', 'augue');
insert into funcao_docente (id, nome, descricao) values (17, 'Godiva Martinello', 'luctus');
insert into funcao_docente (id, nome, descricao) values (18, 'Bambie Schuelcke', 'sollicitudin ut');
insert into funcao_docente (id, nome, descricao) values (19, 'Cyndia Bayne', 'venenatis non');
insert into funcao_docente (id, nome, descricao) values (20, 'Lauren Lawrie', 'vel nulla');
insert into funcao_docente (id, nome, descricao) values (21, 'Margaretha Bloor', 'id');
insert into funcao_docente (id, nome, descricao) values (22, 'Claus Sothern', 'enim');
insert into funcao_docente (id, nome, descricao) values (23, 'Latisha Capey', 'rhoncus');
insert into funcao_docente (id, nome, descricao) values (24, 'Gayleen Elan', 'duis aliquam');
insert into funcao_docente (id, nome, descricao) values (25, 'Rikki Priestland', 'augue');
insert into funcao_docente (id, nome, descricao) values (26, 'Dunc Ladbrooke', 'augue vestibulum');
insert into funcao_docente (id, nome, descricao) values (27, 'Humfrid Raigatt', 'aliquam quis');
insert into funcao_docente (id, nome, descricao) values (28, 'Hebert Algore', 'curabitur');
insert into funcao_docente (id, nome, descricao) values (29, 'Armin Lonsdale', 'ultrices');
insert into funcao_docente (id, nome, descricao) values (30, 'Udell Quarrington', 'cras');
insert into funcao_docente (id, nome, descricao) values (31, 'Chrysler Pariso', 'enim');
insert into funcao_docente (id, nome, descricao) values (32, 'Penelopa Itzcovich', 'a');
insert into funcao_docente (id, nome, descricao) values (33, 'Dorey Scollard', 'odio');
insert into funcao_docente (id, nome, descricao) values (34, 'Benyamin Tourner', 'egestas');
insert into funcao_docente (id, nome, descricao) values (35, 'Lucretia Braine', 'viverra dapibus');
insert into funcao_docente (id, nome, descricao) values (36, 'Jeffie Gilleon', 'sed sagittis');
insert into funcao_docente (id, nome, descricao) values (37, 'Sascha Tattam', 'varius');
insert into funcao_docente (id, nome, descricao) values (38, 'Mathew Gallard', 'orci');
insert into funcao_docente (id, nome, descricao) values (39, 'Osborn Henric', 'in');
insert into funcao_docente (id, nome, descricao) values (40, 'Licha Matejovsky', 'suspendisse ornare');
insert into funcao_docente (id, nome, descricao) values (41, 'Cari Zoellner', 'vel dapibus');
insert into funcao_docente (id, nome, descricao) values (42, 'William Dugan', 'neque sapien');
insert into funcao_docente (id, nome, descricao) values (43, 'Whittaker Brimm', 'vestibulum proin');
insert into funcao_docente (id, nome, descricao) values (44, 'Fawne Ryan', 'neque sapien');
insert into funcao_docente (id, nome, descricao) values (45, 'Vidovic Whettleton', 'dapibus');
insert into funcao_docente (id, nome, descricao) values (46, 'Nicoline Popov', 'at');
insert into funcao_docente (id, nome, descricao) values (47, 'Caddric Merle', 'in');
insert into funcao_docente (id, nome, descricao) values (48, 'Aurel Kondratenko', 'purus');
insert into funcao_docente (id, nome, descricao) values (49, 'Lelah Bocke', 'ac');
insert into funcao_docente (id, nome, descricao) values (50, 'Hartley Warlawe', 'commodo');
insert into funcao_docente (id, nome, descricao) values (51, 'Trude Saylor', 'in');
insert into funcao_docente (id, nome, descricao) values (52, 'Hermy Persent', 'quis');
insert into funcao_docente (id, nome, descricao) values (53, 'Putnem Dowthwaite', 'lectus');
insert into funcao_docente (id, nome, descricao) values (54, 'Baxy Crusham', 'laoreet ut');
insert into funcao_docente (id, nome, descricao) values (55, 'Sindee Shatford', 'a');
insert into funcao_docente (id, nome, descricao) values (56, 'Raphaela Andreassen', 'erat volutpat');
insert into funcao_docente (id, nome, descricao) values (57, 'Haleigh Sherwood', 'quam a');
insert into funcao_docente (id, nome, descricao) values (58, 'Abel Bullion', 'at');
insert into funcao_docente (id, nome, descricao) values (59, 'Phylis Nockells', 'viverra');
insert into funcao_docente (id, nome, descricao) values (60, 'Derrek Chiommienti', 'nec');
insert into funcao_docente (id, nome, descricao) values (61, 'Letty Ledbetter', 'dictumst morbi');
insert into funcao_docente (id, nome, descricao) values (62, 'Vasilis Biernat', 'pede');
insert into funcao_docente (id, nome, descricao) values (63, 'Kurt Skynner', 'vel');
insert into funcao_docente (id, nome, descricao) values (64, 'Vladimir Corstorphine', 'et ultrices');
insert into funcao_docente (id, nome, descricao) values (65, 'Lana Sorrell', 'at');
insert into funcao_docente (id, nome, descricao) values (66, 'Clevie Wallman', 'consectetuer adipiscing');
insert into funcao_docente (id, nome, descricao) values (67, 'Jody McErlaine', 'ut tellus');
insert into funcao_docente (id, nome, descricao) values (68, 'Gabie Spridgen', 'viverra');
insert into funcao_docente (id, nome, descricao) values (69, 'Rafael Norris', 'convallis');
insert into funcao_docente (id, nome, descricao) values (70, 'Fleurette Crumbie', 'blandit');
insert into funcao_docente (id, nome, descricao) values (71, 'Clint Earley', 'quam');
insert into funcao_docente (id, nome, descricao) values (72, 'Cheri Greenside', 'sit amet');
insert into funcao_docente (id, nome, descricao) values (73, 'Frederich Woodison', 'risus');
insert into funcao_docente (id, nome, descricao) values (74, 'Mack Blackeby', 'porta volutpat');
insert into funcao_docente (id, nome, descricao) values (75, 'Alexandro Chetwind', 'ante');
insert into funcao_docente (id, nome, descricao) values (76, 'Vanni Langhorne', 'sapien');
insert into funcao_docente (id, nome, descricao) values (77, 'Ave Cudd', 'vivamus vestibulum');
insert into funcao_docente (id, nome, descricao) values (78, 'Susanne Dot', 'morbi');
insert into funcao_docente (id, nome, descricao) values (79, 'Jefferey Hallows', 'donec');
insert into funcao_docente (id, nome, descricao) values (80, 'Tiffani Chrishop', 'risus');
insert into funcao_docente (id, nome, descricao) values (81, 'Devon Haysham', 'nulla mollis');
insert into funcao_docente (id, nome, descricao) values (82, 'Cos Wheildon', 'erat');
insert into funcao_docente (id, nome, descricao) values (83, 'Aylmer Claughton', 'maecenas rhoncus');
insert into funcao_docente (id, nome, descricao) values (84, 'Tiffie Kyte', 'libero ut');
insert into funcao_docente (id, nome, descricao) values (85, 'Ellyn Roos', 'etiam');
insert into funcao_docente (id, nome, descricao) values (86, 'Alard Waugh', 'donec');
insert into funcao_docente (id, nome, descricao) values (87, 'Carilyn Hunnicutt', 'faucibus accumsan');
insert into funcao_docente (id, nome, descricao) values (88, 'Krista Membry', 'a nibh');
insert into funcao_docente (id, nome, descricao) values (89, 'Irvine Lamble', 'non');
insert into funcao_docente (id, nome, descricao) values (90, 'Joey Tennick', 'nibh fusce');
insert into funcao_docente (id, nome, descricao) values (91, 'Shawn Moss', 'at ipsum');
insert into funcao_docente (id, nome, descricao) values (92, 'Allix Cussons', 'neque');
insert into funcao_docente (id, nome, descricao) values (93, 'Daveen Brabon', 'venenatis');
insert into funcao_docente (id, nome, descricao) values (94, 'Patsy Asprey', 'aliquet ultrices');
insert into funcao_docente (id, nome, descricao) values (95, 'Arney Wiffler', 'lectus in');
insert into funcao_docente (id, nome, descricao) values (96, 'Tiffanie Beel', 'augue aliquam');
insert into funcao_docente (id, nome, descricao) values (97, 'Warren Divill', 'ligula');
insert into funcao_docente (id, nome, descricao) values (98, 'Yvette Rikkard', 'velit vivamus');
insert into funcao_docente (id, nome, descricao) values (99, 'Rozamond Weighell', 'ac');
insert into funcao_docente (id, nome, descricao) values (100, 'Tiffy Munnery', 'interdum');
insert into funcao_docente (id, nome, descricao) values (101, 'Devondra Ivushkin', 'vulputate');
insert into funcao_docente (id, nome, descricao) values (102, 'Aprilette Kubicek', 'morbi');
insert into funcao_docente (id, nome, descricao) values (103, 'Johan Spohr', 'eget');
insert into funcao_docente (id, nome, descricao) values (104, 'Terri Lucken', 'non quam');
insert into funcao_docente (id, nome, descricao) values (105, 'Robinson Coldham', 'sollicitudin');
insert into funcao_docente (id, nome, descricao) values (106, 'Goddard Kettlewell', 'ultrices');
insert into funcao_docente (id, nome, descricao) values (107, 'Karl Nand', 'ac leo');
insert into funcao_docente (id, nome, descricao) values (108, 'Maribel Fullbrook', 'non velit');
insert into funcao_docente (id, nome, descricao) values (109, 'Mychal Dahlman', 'donec ut');
insert into funcao_docente (id, nome, descricao) values (110, 'Clareta Sone', 'in');
insert into funcao_docente (id, nome, descricao) values (111, 'Stanford Natwick', 'at');
insert into funcao_docente (id, nome, descricao) values (112, 'Brina Leverich', 'aliquet');
insert into funcao_docente (id, nome, descricao) values (113, 'Libbey Dienes', 'ac leo');
insert into funcao_docente (id, nome, descricao) values (114, 'Harv Kerswill', 'ac');
insert into funcao_docente (id, nome, descricao) values (115, 'Tobiah Noriega', 'proin risus');
insert into funcao_docente (id, nome, descricao) values (116, 'Hillie Allonby', 'non');
insert into funcao_docente (id, nome, descricao) values (117, 'Eugenius Menguy', 'ipsum');
insert into funcao_docente (id, nome, descricao) values (118, 'Brucie Swanson', 'ultrices erat');
insert into funcao_docente (id, nome, descricao) values (119, 'Jesse Hayer', 'aliquet');
insert into funcao_docente (id, nome, descricao) values (120, 'Shandie How to preserve', 'euismod');
insert into funcao_docente (id, nome, descricao) values (121, 'Therese Dales', 'pretium nisl');
insert into funcao_docente (id, nome, descricao) values (122, 'Merrile Yellowlees', 'morbi');
insert into funcao_docente (id, nome, descricao) values (123, 'Christabel Coate', 'eget');
insert into funcao_docente (id, nome, descricao) values (124, 'Dov Charity', 'morbi');
insert into funcao_docente (id, nome, descricao) values (125, 'Dew Brimham', 'posuere');
insert into funcao_docente (id, nome, descricao) values (126, 'Fianna Cesco', 'congue');
insert into funcao_docente (id, nome, descricao) values (127, 'Orion Mingardi', 'tellus');
insert into funcao_docente (id, nome, descricao) values (128, 'Rickie Doody', 'aliquet maecenas');
insert into funcao_docente (id, nome, descricao) values (129, 'Malvin Tonks', 'dolor sit');
insert into funcao_docente (id, nome, descricao) values (130, 'Marlene Rosencrantz', 'justo etiam');
insert into funcao_docente (id, nome, descricao) values (131, 'Maude Fasler', 'nec');
insert into funcao_docente (id, nome, descricao) values (132, 'Stearn Sykora', 'eget');
insert into funcao_docente (id, nome, descricao) values (133, 'Doti Hardcastle', 'semper');
insert into funcao_docente (id, nome, descricao) values (134, 'Agneta Iacovazzi', 'in imperdiet');
insert into funcao_docente (id, nome, descricao) values (135, 'Jelene Odhams', 'ut');
insert into funcao_docente (id, nome, descricao) values (136, 'Ardyth Simion', 'nisi at');
insert into funcao_docente (id, nome, descricao) values (137, 'Sergio O''Halloran', 'eu');
insert into funcao_docente (id, nome, descricao) values (138, 'Sherwin Huffer', 'primis');
insert into funcao_docente (id, nome, descricao) values (139, 'Alverta Mecco', 'nulla');
insert into funcao_docente (id, nome, descricao) values (140, 'Titos Smallacombe', 'sit');
insert into funcao_docente (id, nome, descricao) values (141, 'Terrance Conti', 'suscipit ligula');
insert into funcao_docente (id, nome, descricao) values (142, 'Cale Wickey', 'ante');
insert into funcao_docente (id, nome, descricao) values (143, 'Vida Gwinnel', 'mauris viverra');
insert into funcao_docente (id, nome, descricao) values (144, 'Dorotea Lennie', 'ac est');
insert into funcao_docente (id, nome, descricao) values (145, 'Benjie Kernaghan', 'nam dui');
insert into funcao_docente (id, nome, descricao) values (146, 'Haily Drane', 'ut erat');
insert into funcao_docente (id, nome, descricao) values (147, 'Bobbie Meaney', 'suscipit');
insert into funcao_docente (id, nome, descricao) values (148, 'Erroll Crisp', 'id');
insert into funcao_docente (id, nome, descricao) values (149, 'Devi Ackenhead', 'dapibus at');
insert into funcao_docente (id, nome, descricao) values (150, 'Matti Marion', 'posuere');
insert into funcao_docente (id, nome, descricao) values (151, 'Tabbi Punchard', 'vehicula condimentum');
insert into funcao_docente (id, nome, descricao) values (152, 'Earvin Stave', 'in');
insert into funcao_docente (id, nome, descricao) values (153, 'Rosaline Menendes', 'phasellus sit');
insert into funcao_docente (id, nome, descricao) values (154, 'Raffaello MacCook', 'est donec');
insert into funcao_docente (id, nome, descricao) values (155, 'Laird O''Gavin', 'a');
insert into funcao_docente (id, nome, descricao) values (156, 'Almeria Pendle', 'eleifend donec');
insert into funcao_docente (id, nome, descricao) values (157, 'Bernie Kerfut', 'luctus et');
insert into funcao_docente (id, nome, descricao) values (158, 'Sharai Dreakin', 'donec');
insert into funcao_docente (id, nome, descricao) values (159, 'Augustin Beecroft', 'id sapien');
insert into funcao_docente (id, nome, descricao) values (160, 'Patricio Wotherspoon', 'sed');
insert into funcao_docente (id, nome, descricao) values (161, 'Clarice Kearle', 'ac nibh');
insert into funcao_docente (id, nome, descricao) values (162, 'Brynne Allawy', 'et');
insert into funcao_docente (id, nome, descricao) values (163, 'Hussein Beckworth', 'viverra');
insert into funcao_docente (id, nome, descricao) values (164, 'Linnet Grube', 'luctus');
insert into funcao_docente (id, nome, descricao) values (165, 'Breena Avesque', 'velit');
insert into funcao_docente (id, nome, descricao) values (166, 'Drew Traves', 'consequat ut');
insert into funcao_docente (id, nome, descricao) values (167, 'Riordan Clitherow', 'at turpis');
insert into funcao_docente (id, nome, descricao) values (168, 'Andreas Dailly', 'mi');
insert into funcao_docente (id, nome, descricao) values (169, 'Berk Tomaselli', 'vestibulum');
insert into funcao_docente (id, nome, descricao) values (170, 'Catha Renad', 'massa');
insert into funcao_docente (id, nome, descricao) values (171, 'Rivi Lafoy', 'nulla ultrices');
insert into funcao_docente (id, nome, descricao) values (172, 'Teresa Bande', 'pretium nisl');
insert into funcao_docente (id, nome, descricao) values (173, 'Malia Sheaf', 'justo morbi');
insert into funcao_docente (id, nome, descricao) values (174, 'Lissie Keerl', 'faucibus accumsan');
insert into funcao_docente (id, nome, descricao) values (175, 'Vaughn Middleweek', 'tincidunt');
insert into funcao_docente (id, nome, descricao) values (176, 'Gilbertina Donahue', 'in faucibus');
insert into funcao_docente (id, nome, descricao) values (177, 'Kathie Cuvley', 'est et');
insert into funcao_docente (id, nome, descricao) values (178, 'Austine Bulstrode', 'praesent');
insert into funcao_docente (id, nome, descricao) values (179, 'Fiorenze Swedeland', 'justo in');
insert into funcao_docente (id, nome, descricao) values (180, 'Rene Piggens', 'nulla ultrices');
insert into funcao_docente (id, nome, descricao) values (181, 'Audra Wollacott', 'ut');
insert into funcao_docente (id, nome, descricao) values (182, 'Gayle Shackle', 'pharetra magna');
insert into funcao_docente (id, nome, descricao) values (183, 'Alistair Lippingwell', 'amet');
insert into funcao_docente (id, nome, descricao) values (184, 'Adolf Clute', 'augue');
insert into funcao_docente (id, nome, descricao) values (185, 'Thorvald Berntsson', 'id');
insert into funcao_docente (id, nome, descricao) values (186, 'Carr Pinch', 'pede');
insert into funcao_docente (id, nome, descricao) values (187, 'Renault August', 'vel augue');
insert into funcao_docente (id, nome, descricao) values (188, 'Elga Spurrior', 'duis at');
insert into funcao_docente (id, nome, descricao) values (189, 'Devon Dewberry', 'mauris');
insert into funcao_docente (id, nome, descricao) values (190, 'Mary MacKenzie', 'ut mauris');
insert into funcao_docente (id, nome, descricao) values (191, 'Herby McChesney', 'habitasse platea');
insert into funcao_docente (id, nome, descricao) values (192, 'Kerri Daveran', 'ipsum primis');
insert into funcao_docente (id, nome, descricao) values (193, 'Walther Duchant', 'auctor');
insert into funcao_docente (id, nome, descricao) values (194, 'Orelie Kybbye', 'tempus vel');
insert into funcao_docente (id, nome, descricao) values (195, 'Dorisa Fass', 'ipsum primis');
insert into funcao_docente (id, nome, descricao) values (196, 'Taylor Bucklee', 'blandit');
insert into funcao_docente (id, nome, descricao) values (197, 'Kele Salsbury', 'bibendum morbi');
insert into funcao_docente (id, nome, descricao) values (198, 'Normand Wheadon', 'sit amet');
insert into funcao_docente (id, nome, descricao) values (199, 'Carola Waymont', 'ultrices');
insert into funcao_docente (id, nome, descricao) values (200, 'Yancey Joiner', 'donec');
insert into funcao_docente (id, nome, descricao) values (201, 'Ulrikaumeko Paule', 'platea');
insert into funcao_docente (id, nome, descricao) values (202, 'Jud Pidduck', 'posuere nonummy');
insert into funcao_docente (id, nome, descricao) values (203, 'Missy Orpyne', 'maecenas leo');
insert into funcao_docente (id, nome, descricao) values (204, 'Cordelia Gullefant', 'vulputate luctus');
insert into funcao_docente (id, nome, descricao) values (205, 'Francis Hallwood', 'in hac');
insert into funcao_docente (id, nome, descricao) values (206, 'Regina Balshen', 'accumsan felis');
insert into funcao_docente (id, nome, descricao) values (207, 'Fons Babidge', 'id');
insert into funcao_docente (id, nome, descricao) values (208, 'Lorilee Walsh', 'sem');
insert into funcao_docente (id, nome, descricao) values (209, 'Denyse Balshen', 'est');
insert into funcao_docente (id, nome, descricao) values (210, 'Morna Rizzardini', 'feugiat');
insert into funcao_docente (id, nome, descricao) values (211, 'Any Lever', 'id');
insert into funcao_docente (id, nome, descricao) values (212, 'Tessi Few', 'quam');
insert into funcao_docente (id, nome, descricao) values (213, 'Paige Berntssen', 'id sapien');
insert into funcao_docente (id, nome, descricao) values (214, 'Dickie Shiel', 'congue diam');
insert into funcao_docente (id, nome, descricao) values (215, 'Cedric Kenrick', 'nisl venenatis');
insert into funcao_docente (id, nome, descricao) values (216, 'Tanner Cossington', 'convallis');
insert into funcao_docente (id, nome, descricao) values (217, 'Lionel Notman', 'in');
insert into funcao_docente (id, nome, descricao) values (218, 'Fernando Coulson', 'blandit mi');
insert into funcao_docente (id, nome, descricao) values (219, 'Port Shouler', 'mi nulla');
insert into funcao_docente (id, nome, descricao) values (220, 'Rooney Gudgin', 'lectus');
insert into funcao_docente (id, nome, descricao) values (221, 'Harman Lount', 'interdum in');
insert into funcao_docente (id, nome, descricao) values (222, 'Frannie Veighey', 'tellus');
insert into funcao_docente (id, nome, descricao) values (223, 'Grove Greatland', 'curae mauris');
insert into funcao_docente (id, nome, descricao) values (224, 'Clarke Jakubczyk', 'consectetuer adipiscing');
insert into funcao_docente (id, nome, descricao) values (225, 'Alphonso Botwood', 'sollicitudin');
insert into funcao_docente (id, nome, descricao) values (226, 'Kathryne Westbury', 'tempor');
insert into funcao_docente (id, nome, descricao) values (227, 'Pace Mitchard', 'pretium iaculis');
insert into funcao_docente (id, nome, descricao) values (228, 'August Mold', 'pede ac');
insert into funcao_docente (id, nome, descricao) values (229, 'Martie Caroll', 'consectetuer eget');
insert into funcao_docente (id, nome, descricao) values (230, 'Neale Capelle', 'odio porttitor');
insert into funcao_docente (id, nome, descricao) values (231, 'Brannon Postance', 'penatibus');
insert into funcao_docente (id, nome, descricao) values (232, 'Emery Cohalan', 'elit sodales');
insert into funcao_docente (id, nome, descricao) values (233, 'Melony Quarry', 'eget');
insert into funcao_docente (id, nome, descricao) values (234, 'Marven Berzons', 'lorem integer');
insert into funcao_docente (id, nome, descricao) values (235, 'Danna De Mico', 'ultrices erat');
insert into funcao_docente (id, nome, descricao) values (236, 'Artur Warbey', 'eget');
insert into funcao_docente (id, nome, descricao) values (237, 'Tedra Caveney', 'accumsan');
insert into funcao_docente (id, nome, descricao) values (238, 'Liam Lyles', 'primis');
insert into funcao_docente (id, nome, descricao) values (239, 'Marisa Seamark', 'justo');
insert into funcao_docente (id, nome, descricao) values (240, 'Elisha Blunt', 'nascetur');
insert into funcao_docente (id, nome, descricao) values (241, 'Nicoline Radage', 'id');
insert into funcao_docente (id, nome, descricao) values (242, 'Mike Sleightholm', 'a suscipit');
insert into funcao_docente (id, nome, descricao) values (243, 'Alick Spybey', 'sociis natoque');
insert into funcao_docente (id, nome, descricao) values (244, 'Dehlia Ferro', 'vel augue');
insert into funcao_docente (id, nome, descricao) values (245, 'Doll McGarrity', 'rhoncus mauris');
insert into funcao_docente (id, nome, descricao) values (246, 'Vivyanne Danbrook', 'diam id');
insert into funcao_docente (id, nome, descricao) values (247, 'Kristian Labuschagne', 'risus praesent');
insert into funcao_docente (id, nome, descricao) values (248, 'Maiga Hinchcliffe', 'ut');
insert into funcao_docente (id, nome, descricao) values (249, 'Kanya De Hooch', 'et');
insert into funcao_docente (id, nome, descricao) values (250, 'Ryun Mountlow', 'luctus');
