insert into nota (estudante_id, avaliacao_id, nota, comentario) values (1, 1, 14, 'curae');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (2, 2, 11, 'aliquet');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (3, 3, 9, 'congue eget');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (4, 4, 14, 'suspendisse accumsan');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (5, 5, 18, 'imperdiet');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (6, 6, 11, 'sit');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (7, 7, 16, 'in ante');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (8, 8, 9, 'amet erat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (9, 9, 5, 'lacus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (10, 10, 4, 'quisque erat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (11, 11, 7, 'at nibh');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (12, 12, 15, 'libero nam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (13, 13, 12, 'a');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (14, 14, 15, 'maecenas pulvinar');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (15, 15, 4, 'pede');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (16, 16, 19, 'nascetur');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (17, 17, 7, 'consequat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (18, 18, 3, 'lectus pellentesque');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (19, 19, 9, 'dolor sit');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (20, 20, 17, 'venenatis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (21, 21, 15, 'luctus et');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (22, 22, 10, 'suspendisse');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (23, 23, 6, 'felis donec');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (24, 24, 1, 'justo maecenas');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (25, 25, 10, 'et');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (26, 26, 20, 'integer aliquet');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (27, 27, 14, 'amet consectetuer');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (28, 28, 4, 'metus arcu');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (29, 29, 9, 'blandit lacinia');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (30, 30, 7, 'tempus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (31, 31, 3, 'at nulla');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (32, 32, 18, 'maecenas');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (33, 33, 8, 'adipiscing');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (34, 34, 0, 'duis consequat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (35, 35, 19, 'phasellus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (36, 36, 7, 'lectus in');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (37, 37, 1, 'consequat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (38, 38, 15, 'ut erat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (39, 39, 11, 'lorem');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (40, 40, 16, 'venenatis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (41, 41, 14, 'blandit ultrices');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (42, 42, 1, 'pellentesque');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (43, 43, 15, 'amet');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (44, 44, 18, 'lectus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (45, 45, 10, 'volutpat sapien');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (46, 46, 0, 'cursus vestibulum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (47, 47, 18, 'lorem');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (48, 48, 5, 'justo morbi');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (49, 49, 8, 'ante');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (50, 50, 14, 'nulla suspendisse');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (51, 51, 12, 'imperdiet et');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (52, 52, 15, 'faucibus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (53, 53, 15, 'mi');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (54, 54, 7, 'massa tempor');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (55, 55, 19, 'tellus in');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (56, 56, 20, 'vel');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (57, 57, 7, 'id lobortis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (58, 58, 7, 'ante ipsum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (59, 59, 9, 'primis in');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (60, 60, 3, 'luctus nec');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (61, 61, 1, 'maecenas');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (62, 62, 17, 'eu tincidunt');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (63, 63, 11, 'adipiscing');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (64, 64, 11, 'tristique in');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (65, 65, 0, 'quisque erat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (66, 66, 1, 'ligula');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (67, 67, 15, 'interdum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (68, 68, 19, 'mus etiam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (69, 69, 13, 'at vulputate');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (70, 70, 16, 'tortor');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (71, 71, 20, 'in felis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (72, 72, 11, 'vivamus vel');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (73, 73, 7, 'vehicula');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (74, 74, 6, 'iaculis diam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (75, 75, 11, 'ligula nec');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (76, 76, 4, 'posuere');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (77, 77, 16, 'vivamus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (78, 78, 7, 'vulputate');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (79, 79, 12, 'pede malesuada');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (80, 80, 8, 'pede');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (81, 81, 4, 'amet cursus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (82, 82, 9, 'volutpat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (83, 83, 0, 'quam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (84, 84, 10, 'erat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (85, 85, 14, 'nunc');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (86, 86, 20, 'nulla');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (87, 87, 15, 'at');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (88, 88, 0, 'congue etiam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (89, 89, 5, 'morbi');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (90, 90, 8, 'sed vel');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (91, 91, 17, 'quis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (92, 92, 1, 'ante');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (93, 93, 11, 'eleifend');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (94, 94, 10, 'etiam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (95, 95, 6, 'condimentum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (96, 96, 6, 'ipsum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (97, 97, 13, 'id');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (98, 98, 20, 'id nulla');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (99, 99, 7, 'nec dui');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (100, 100, 2, 'convallis tortor');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (101, 101, 2, 'pede');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (102, 102, 1, 'congue vivamus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (103, 103, 4, 'consectetuer');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (104, 104, 13, 'donec ut');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (105, 105, 3, 'in');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (106, 106, 8, 'ut');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (107, 107, 16, 'lacus at');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (108, 108, 16, 'luctus et');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (109, 109, 10, 'rutrum nulla');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (110, 110, 16, 'proin at');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (111, 111, 0, 'proin leo');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (112, 112, 1, 'quam a');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (113, 113, 4, 'ac');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (114, 114, 7, 'ante');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (115, 115, 3, 'et tempus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (116, 116, 11, 'cubilia');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (117, 117, 20, 'suspendisse');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (118, 118, 7, 'sed tristique');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (119, 119, 7, 'justo etiam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (120, 120, 20, 'nisl');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (121, 121, 7, 'in');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (122, 122, 3, 'nulla pede');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (123, 123, 15, 'libero');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (124, 124, 3, 'parturient montes');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (125, 125, 6, 'eget rutrum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (126, 126, 6, 'tincidunt');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (127, 127, 14, 'varius');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (128, 128, 16, 'porta');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (129, 129, 12, 'in sagittis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (130, 130, 7, 'aenean lectus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (131, 131, 10, 'nisl duis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (132, 132, 10, 'sit');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (133, 133, 20, 'aliquet at');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (134, 134, 8, 'quis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (135, 135, 6, 'enim sit');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (136, 136, 13, 'primis in');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (137, 137, 0, 'vestibulum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (138, 138, 17, 'pharetra magna');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (139, 139, 14, 'dignissim');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (140, 140, 2, 'primis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (141, 141, 0, 'vel');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (142, 142, 10, 'ornare');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (143, 143, 16, 'venenatis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (144, 144, 20, 'sem fusce');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (145, 145, 5, 'pede libero');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (146, 146, 14, 'ac');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (147, 147, 8, 'tortor risus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (148, 148, 4, 'sapien');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (149, 149, 11, 'et');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (150, 150, 10, 'eu');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (151, 151, 9, 'diam nam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (152, 152, 11, 'mattis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (153, 153, 16, 'mi pede');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (154, 154, 1, 'augue');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (155, 155, 9, 'in porttitor');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (156, 156, 19, 'bibendum felis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (157, 157, 4, 'diam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (158, 158, 20, 'sapien');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (159, 159, 16, 'sollicitudin');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (160, 160, 5, 'primis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (161, 161, 13, 'amet nunc');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (162, 162, 1, 'eget');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (163, 163, 19, 'eleifend');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (164, 164, 11, 'amet nunc');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (165, 165, 10, 'maecenas');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (166, 166, 18, 'nisl duis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (167, 167, 2, 'volutpat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (168, 168, 7, 'rutrum neque');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (169, 169, 16, 'mus vivamus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (170, 170, 18, 'ut');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (171, 171, 18, 'ullamcorper');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (172, 172, 0, 'donec');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (173, 173, 2, 'sem praesent');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (174, 174, 3, 'quam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (175, 175, 14, 'nascetur ridiculus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (176, 176, 20, 'sapien');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (177, 177, 3, 'quam pharetra');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (178, 178, 2, 'eu');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (179, 179, 6, 'nascetur ridiculus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (180, 180, 15, 'in');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (181, 181, 18, 'bibendum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (182, 182, 10, 'ultrices libero');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (183, 183, 9, 'dui proin');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (184, 184, 13, 'in faucibus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (185, 185, 20, 'nulla ultrices');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (186, 186, 4, 'vitae mattis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (187, 187, 2, 'nam tristique');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (188, 188, 16, 'nunc donec');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (189, 189, 2, 'quis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (190, 190, 5, 'nisl venenatis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (191, 191, 4, 'faucibus orci');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (192, 192, 2, 'integer');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (193, 193, 19, 'dapibus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (194, 194, 13, 'non quam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (195, 195, 14, 'nisl');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (196, 196, 11, 'at nulla');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (197, 197, 12, 'lobortis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (198, 198, 18, 'vulputate');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (199, 199, 2, 'turpis enim');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (200, 200, 11, 'hac habitasse');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (201, 201, 12, 'non');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (202, 202, 11, 'turpis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (203, 203, 19, 'lacinia');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (204, 204, 14, 'aliquam');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (205, 205, 8, 'odio');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (206, 206, 8, 'at');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (207, 207, 9, 'pulvinar');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (208, 208, 6, 'convallis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (209, 209, 11, 'felis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (210, 210, 16, 'odio');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (211, 211, 14, 'ligula suspendisse');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (212, 212, 14, 'amet');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (213, 213, 14, 'sit amet');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (214, 214, 3, 'id sapien');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (215, 215, 17, 'nec sem');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (216, 216, 6, 'quisque id');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (217, 217, 6, 'a feugiat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (218, 218, 10, 'eget');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (219, 219, 16, 'at ipsum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (220, 220, 11, 'venenatis lacinia');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (221, 221, 10, 'eget');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (222, 222, 1, 'dapibus dolor');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (223, 223, 6, 'vestibulum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (224, 224, 18, 'porttitor');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (225, 225, 0, 'ipsum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (226, 226, 11, 'ornare');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (227, 227, 9, 'tincidunt ante');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (228, 228, 16, 'elementum eu');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (229, 229, 7, 'eu');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (230, 230, 10, 'vestibulum ac');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (231, 231, 2, 'nulla sed');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (232, 232, 2, 'tempus sit');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (233, 233, 8, 'nisl');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (234, 234, 17, 'platea dictumst');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (235, 235, 13, 'nisi at');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (236, 236, 17, 'turpis nec');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (237, 237, 9, 'luctus rutrum');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (238, 238, 0, 'amet');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (239, 239, 2, 'turpis adipiscing');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (240, 240, 4, 'vulputate');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (241, 241, 13, 'metus sapien');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (242, 242, 13, 'eu');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (243, 243, 14, 'habitasse');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (244, 244, 3, 'sit');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (245, 245, 9, 'dapibus at');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (246, 246, 16, 'amet turpis');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (247, 247, 1, 'rhoncus');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (248, 248, 5, 'erat');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (249, 249, 11, 'et');
insert into nota (estudante_id, avaliacao_id, nota, comentario) values (250, 250, 3, 'primis in');
