insert into recurso (id, nome, descricao, turma_id, docente_id) values (1, 'massa', 'tincidunt', 1, 1);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (2, 'ipsum', 'nulla pede', 2, 2);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (3, 'ipsum', 'pellentesque ultrices', 3, 3);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (4, 'semper', 'pede ullamcorper', 4, 4);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (5, 'posuere', 'ut', 5, 5);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (6, 'nec', 'nisi venenatis', 6, 6);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (7, 'donec', 'amet', 7, 7);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (8, 'ipsum', 'erat', 8, 8);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (9, 'justo', 'ante ipsum', 9, 9);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (10, 'congue', 'hac habitasse', 10, 10);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (11, 'quam', 'posuere cubilia', 11, 11);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (12, 'vitae', 'tempus sit', 12, 12);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (13, 'non', 'a', 13, 13);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (14, 'mauris', 'in', 14, 14);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (15, 'vivamus', 'odio', 15, 15);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (16, 'nullam', 'donec', 16, 16);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (17, 'fringilla', 'molestie hendrerit', 17, 17);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (18, 'pellentesque', 'risus semper', 18, 18);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (19, 'ac', 'sagittis nam', 19, 19);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (20, 'massa', 'amet', 20, 20);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (21, 'cras', 'dictumst', 21, 21);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (22, 'at', 'nulla mollis', 22, 22);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (23, 'faucibus', 'magnis dis', 23, 23);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (24, 'molestie', 'mattis egestas', 24, 24);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (25, 'dui', 'eget', 25, 25);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (26, 'nisl', 'at', 26, 26);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (27, 'eget', 'integer aliquet', 27, 27);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (28, 'pede', 'consequat varius', 28, 28);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (29, 'vel', 'nisi volutpat', 29, 29);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (30, 'congue', 'vulputate', 30, 30);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (31, 'nam', 'eget', 31, 31);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (32, 'ut', 'risus praesent', 32, 32);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (33, 'tellus', 'aenean lectus', 33, 33);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (34, 'justo', 'in faucibus', 34, 34);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (35, 'nonummy', 'velit', 35, 35);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (36, 'ipsum', 'vestibulum', 36, 36);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (37, 'in', 'molestie sed', 37, 37);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (38, 'aenean', 'tristique', 38, 38);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (39, 'in', 'vivamus', 39, 39);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (40, 'justo', 'congue', 40, 40);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (41, 'enim', 'tempor turpis', 41, 41);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (42, 'ante', 'vestibulum proin', 42, 42);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (43, 'maecenas', 'in', 43, 43);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (44, 'risus', 'cras pellentesque', 44, 44);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (45, 'ut', 'in', 45, 45);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (46, 'curabitur', 'sit amet', 46, 46);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (47, 'ut', 'turpis', 47, 47);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (48, 'sapien', 'semper', 48, 48);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (49, 'libero', 'turpis', 49, 49);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (50, 'mauris', 'pulvinar lobortis', 50, 50);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (51, 'sem', 'ridiculus mus', 51, 51);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (52, 'porttitor', 'praesent', 52, 52);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (53, 'fermentum', 'tincidunt eu', 53, 53);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (54, 'nullam', 'aliquam erat', 54, 54);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (55, 'eu', 'nisl duis', 55, 55);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (56, 'non', 'eros suspendisse', 56, 56);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (57, 'justo', 'semper rutrum', 57, 57);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (58, 'quam', 'pellentesque quisque', 58, 58);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (59, 'sem', 'diam', 59, 59);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (60, 'posuere', 'luctus', 60, 60);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (61, 'lectus', 'velit donec', 61, 61);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (62, 'elit', 'vivamus', 62, 62);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (63, 'libero', 'est', 63, 63);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (64, 'convallis', 'lectus in', 64, 64);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (65, 'sapien', 'nullam molestie', 65, 65);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (66, 'varius', 'tristique', 66, 66);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (67, 'eleifend', 'nibh', 67, 67);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (68, 'dolor', 'leo', 68, 68);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (69, 'augue', 'nulla', 69, 69);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (70, 'posuere', 'aenean', 70, 70);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (71, 'ac', 'ultrices', 71, 71);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (72, 'dignissim', 'nulla', 72, 72);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (73, 'donec', 'augue', 73, 73);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (74, 'venenatis', 'curae nulla', 74, 74);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (75, 'massa', 'in imperdiet', 75, 75);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (76, 'nulla', 'duis', 76, 76);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (77, 'elementum', 'diam', 77, 77);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (78, 'sapien', 'ultrices posuere', 78, 78);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (79, 'dictumst', 'congue', 79, 79);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (80, 'nam', 'ac diam', 80, 80);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (81, 'ipsum', 'dolor sit', 81, 81);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (82, 'eu', 'aliquet', 82, 82);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (83, 'tortor', 'interdum', 83, 83);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (84, 'amet', 'dictumst', 84, 84);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (85, 'sem', 'et', 85, 85);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (86, 'tellus', 'congue risus', 86, 86);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (87, 'viverra', 'leo maecenas', 87, 87);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (88, 'in', 'elit', 88, 88);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (89, 'ut', 'pede', 89, 89);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (90, 'ac', 'nibh', 90, 90);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (91, 'aliquam', 'mauris non', 91, 91);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (92, 'feugiat', 'integer', 92, 92);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (93, 'luctus', 'leo maecenas', 93, 93);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (94, 'quam', 'in', 94, 94);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (95, 'dui', 'congue risus', 95, 95);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (96, 'adipiscing', 'etiam justo', 96, 96);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (97, 'arcu', 'ridiculus mus', 97, 97);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (98, 'sed', 'sodales', 98, 98);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (99, 'nibh', 'ultrices aliquet', 99, 99);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (100, 'pede', 'nulla', 100, 100);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (101, 'aliquam', 'mattis odio', 101, 101);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (102, 'placerat', 'adipiscing elit', 102, 102);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (103, 'neque', 'diam in', 103, 103);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (104, 'nulla', 'diam', 104, 104);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (105, 'nibh', 'diam', 105, 105);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (106, 'a', 'in blandit', 106, 106);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (107, 'ligula', 'sem', 107, 107);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (108, 'mauris', 'pretium quis', 108, 108);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (109, 'tortor', 'quisque', 109, 109);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (110, 'est', 'diam', 110, 110);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (111, 'morbi', 'libero quis', 111, 111);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (112, 'augue', 'amet nulla', 112, 112);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (113, 'libero', 'facilisi', 113, 113);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (114, 'volutpat', 'pulvinar', 114, 114);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (115, 'interdum', 'vivamus in', 115, 115);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (116, 'adipiscing', 'tincidunt lacus', 116, 116);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (117, 'vulputate', 'dolor quis', 117, 117);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (118, 'interdum', 'non mauris', 118, 118);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (119, 'pellentesque', 'in magna', 119, 119);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (120, 'purus', 'magna bibendum', 120, 120);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (121, 'duis', 'erat tortor', 121, 121);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (122, 'tincidunt', 'in congue', 122, 122);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (123, 'lectus', 'vulputate', 123, 123);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (124, 'proin', 'proin', 124, 124);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (125, 'in', 'praesent', 125, 125);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (126, 'vestibulum', 'scelerisque mauris', 126, 126);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (127, 'et', 'nulla sed', 127, 127);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (128, 'turpis', 'in', 128, 128);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (129, 'ut', 'cursus', 129, 129);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (130, 'ac', 'id', 130, 130);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (131, 'potenti', 'in purus', 131, 131);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (132, 'cras', 'pede', 132, 132);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (133, 'augue', 'blandit', 133, 133);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (134, 'sollicitudin', 'pede', 134, 134);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (135, 'ultrices', 'sapien', 135, 135);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (136, 'sit', 'praesent blandit', 136, 136);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (137, 'odio', 'mattis', 137, 137);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (138, 'ut', 'quis turpis', 138, 138);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (139, 'lobortis', 'eu', 139, 139);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (140, 'pharetra', 'curae mauris', 140, 140);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (141, 'nisl', 'vulputate ut', 141, 141);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (142, 'in', 'pretium', 142, 142);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (143, 'nulla', 'sed tristique', 143, 143);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (144, 'ultricies', 'nunc commodo', 144, 144);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (145, 'vestibulum', 'consequat lectus', 145, 145);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (146, 'vulputate', 'at', 146, 146);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (147, 'dapibus', 'vestibulum ante', 147, 147);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (148, 'sit', 'ut', 148, 148);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (149, 'vel', 'lacus purus', 149, 149);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (150, 'blandit', 'sit', 150, 150);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (151, 'suspendisse', 'ac', 151, 151);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (152, 'quam', 'dapibus', 152, 152);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (153, 'integer', 'elementum in', 153, 153);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (154, 'consectetuer', 'nam', 154, 154);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (155, 'nulla', 'mauris', 155, 155);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (156, 'morbi', 'curabitur', 156, 156);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (157, 'pretium', 'dignissim vestibulum', 157, 157);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (158, 'morbi', 'vestibulum sed', 158, 158);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (159, 'vehicula', 'ligula vehicula', 159, 159);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (160, 'leo', 'tincidunt nulla', 160, 160);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (161, 'amet', 'quam a', 161, 161);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (162, 'molestie', 'maecenas', 162, 162);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (163, 'amet', 'felis', 163, 163);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (164, 'proin', 'orci', 164, 164);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (165, 'at', 'nonummy maecenas', 165, 165);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (166, 'suscipit', 'mus vivamus', 166, 166);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (167, 'eu', 'eleifend luctus', 167, 167);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (168, 'sapien', 'accumsan tellus', 168, 168);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (169, 'velit', 'pede', 169, 169);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (170, 'justo', 'platea', 170, 170);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (171, 'in', 'mattis odio', 171, 171);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (172, 'volutpat', 'lorem ipsum', 172, 172);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (173, 'tortor', 'sagittis dui', 173, 173);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (174, 'posuere', 'ante', 174, 174);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (175, 'risus', 'tortor eu', 175, 175);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (176, 'curae', 'nunc', 176, 176);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (177, 'sit', 'gravida sem', 177, 177);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (178, 'leo', 'vel dapibus', 178, 178);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (179, 'mi', 'at', 179, 179);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (180, 'eu', 'nec molestie', 180, 180);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (181, 'luctus', 'turpis', 181, 181);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (182, 'dui', 'nulla', 182, 182);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (183, 'in', 'lectus', 183, 183);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (184, 'curae', 'augue', 184, 184);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (185, 'imperdiet', 'at', 185, 185);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (186, 'congue', 'adipiscing', 186, 186);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (187, 'justo', 'sem mauris', 187, 187);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (188, 'turpis', 'id nisl', 188, 188);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (189, 'ante', 'proin', 189, 189);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (190, 'rutrum', 'tincidunt eu', 190, 190);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (191, 'quis', 'aliquam', 191, 191);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (192, 'libero', 'donec semper', 192, 192);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (193, 'morbi', 'nonummy', 193, 193);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (194, 'diam', 'ultrices posuere', 194, 194);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (195, 'interdum', 'orci luctus', 195, 195);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (196, 'vulputate', 'ac', 196, 196);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (197, 'ipsum', 'dis', 197, 197);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (198, 'tortor', 'sed tincidunt', 198, 198);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (199, 'vel', 'nulla', 199, 199);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (200, 'eget', 'nam', 200, 200);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (201, 'pulvinar', 'augue', 201, 201);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (202, 'lectus', 'mi', 202, 202);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (203, 'vel', 'ut', 203, 203);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (204, 'sed', 'amet', 204, 204);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (205, 'elit', 'justo', 205, 205);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (206, 'magna', 'nibh', 206, 206);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (207, 'dui', 'maecenas tincidunt', 207, 207);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (208, 'lectus', 'vestibulum', 208, 208);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (209, 'vestibulum', 'augue', 209, 209);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (210, 'nam', 'luctus cum', 210, 210);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (211, 'imperdiet', 'vivamus vestibulum', 211, 211);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (212, 'penatibus', 'in', 212, 212);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (213, 'eget', 'eu', 213, 213);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (214, 'id', 'praesent blandit', 214, 214);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (215, 'in', 'mauris non', 215, 215);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (216, 'erat', 'orci nullam', 216, 216);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (217, 'nunc', 'vestibulum ante', 217, 217);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (218, 'dui', 'interdum', 218, 218);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (219, 'mi', 'orci', 219, 219);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (220, 'adipiscing', 'leo rhoncus', 220, 220);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (221, 'vel', 'curae', 221, 221);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (222, 'etiam', 'vulputate nonummy', 222, 222);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (223, 'venenatis', 'cras', 223, 223);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (224, 'nisi', 'id justo', 224, 224);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (225, 'sapien', 'lacus', 225, 225);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (226, 'eu', 'quisque', 226, 226);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (227, 'amet', 'cubilia', 227, 227);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (228, 'nullam', 'orci', 228, 228);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (229, 'lobortis', 'purus sit', 229, 229);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (230, 'cubilia', 'porttitor', 230, 230);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (231, 'justo', 'ante ipsum', 231, 231);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (232, 'porttitor', 'maecenas leo', 232, 232);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (233, 'metus', 'molestie', 233, 233);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (234, 'ultricies', 'enim blandit', 234, 234);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (235, 'vestibulum', 'vel', 235, 235);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (236, 'luctus', 'congue', 236, 236);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (237, 'ut', 'nascetur ridiculus', 237, 237);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (238, 'risus', 'sapien', 238, 238);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (239, 'sagittis', 'ultrices posuere', 239, 239);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (240, 'in', 'donec ut', 240, 240);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (241, 'arcu', 'turpis adipiscing', 241, 241);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (242, 'nullam', 'mi', 242, 242);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (243, 'sit', 'ante vel', 243, 243);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (244, 'nulla', 'luctus', 244, 244);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (245, 'in', 'et', 245, 245);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (246, 'volutpat', 'condimentum', 246, 246);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (247, 'scelerisque', 'ac', 247, 247);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (248, 'pellentesque', 'habitasse', 248, 248);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (249, 'vestibulum', 'at vulputate', 249, 249);
insert into recurso (id, nome, descricao, turma_id, docente_id) values (250, 'vitae', 'ante vel', 250, 250);
