insert into tipo_departamento (id, nome, descricao) values (1, 'Blogtags', 'in hac');
insert into tipo_departamento (id, nome, descricao) values (2, 'Flipstorm', 'erat quisque');
insert into tipo_departamento (id, nome, descricao) values (3, 'Digitube', 'eget vulputate');
insert into tipo_departamento (id, nome, descricao) values (4, 'Katz', 'massa');
insert into tipo_departamento (id, nome, descricao) values (5, 'Meevee', 'blandit mi');
insert into tipo_departamento (id, nome, descricao) values (6, 'Gabtune', 'ultrices phasellus');
insert into tipo_departamento (id, nome, descricao) values (7, 'Yoveo', 'nam tristique');
insert into tipo_departamento (id, nome, descricao) values (8, 'Kaymbo', 'purus phasellus');
insert into tipo_departamento (id, nome, descricao) values (9, 'Meedoo', 'lacinia sapien');
insert into tipo_departamento (id, nome, descricao) values (10, 'Bluezoom', 'vestibulum');
insert into tipo_departamento (id, nome, descricao) values (11, 'Einti', 'nullam molestie');
insert into tipo_departamento (id, nome, descricao) values (12, 'Blognation', 'aliquam sit');
insert into tipo_departamento (id, nome, descricao) values (13, 'Mydo', 'et magnis');
insert into tipo_departamento (id, nome, descricao) values (14, 'Kare', 'ipsum primis');
insert into tipo_departamento (id, nome, descricao) values (15, 'Youopia', 'in hac');
insert into tipo_departamento (id, nome, descricao) values (16, 'Quamba', 'platea');
insert into tipo_departamento (id, nome, descricao) values (17, 'Kazio', 'id luctus');
insert into tipo_departamento (id, nome, descricao) values (18, 'Dablist', 'ante vivamus');
insert into tipo_departamento (id, nome, descricao) values (19, 'Meezzy', 'ut');
insert into tipo_departamento (id, nome, descricao) values (20, 'Fanoodle', 'non');
insert into tipo_departamento (id, nome, descricao) values (21, 'Tekfly', 'integer tincidunt');
insert into tipo_departamento (id, nome, descricao) values (22, 'Pixoboo', 'lacus');
insert into tipo_departamento (id, nome, descricao) values (23, 'Realpoint', 'ac');
insert into tipo_departamento (id, nome, descricao) values (24, 'Rhynoodle', 'accumsan odio');
insert into tipo_departamento (id, nome, descricao) values (25, 'Voonte', 'at diam');
insert into tipo_departamento (id, nome, descricao) values (26, 'Blogtag', 'ac');
insert into tipo_departamento (id, nome, descricao) values (27, 'Meevee', 'cursus');
insert into tipo_departamento (id, nome, descricao) values (28, 'Topiclounge', 'quisque erat');
insert into tipo_departamento (id, nome, descricao) values (29, 'Skipstorm', 'quisque erat');
insert into tipo_departamento (id, nome, descricao) values (30, 'Skaboo', 'vestibulum ante');
insert into tipo_departamento (id, nome, descricao) values (31, 'Trupe', 'integer');
insert into tipo_departamento (id, nome, descricao) values (32, 'Chatterpoint', 'orci eget');
insert into tipo_departamento (id, nome, descricao) values (33, 'Divanoodle', 'aliquam lacus');
insert into tipo_departamento (id, nome, descricao) values (34, 'Linkbuzz', 'purus');
insert into tipo_departamento (id, nome, descricao) values (35, 'Katz', 'ac');
insert into tipo_departamento (id, nome, descricao) values (36, 'Dabshots', 'lectus');
insert into tipo_departamento (id, nome, descricao) values (37, 'LiveZ', 'justo');
insert into tipo_departamento (id, nome, descricao) values (38, 'Mymm', 'nunc');
insert into tipo_departamento (id, nome, descricao) values (39, 'Topdrive', 'lectus');
insert into tipo_departamento (id, nome, descricao) values (40, 'Fivebridge', 'eget');
insert into tipo_departamento (id, nome, descricao) values (41, 'Flipbug', 'gravida nisi');
insert into tipo_departamento (id, nome, descricao) values (42, 'Yata', 'semper');
insert into tipo_departamento (id, nome, descricao) values (43, 'Agivu', 'magnis');
insert into tipo_departamento (id, nome, descricao) values (44, 'Leexo', 'ridiculus mus');
insert into tipo_departamento (id, nome, descricao) values (45, 'Skinder', 'varius');
insert into tipo_departamento (id, nome, descricao) values (46, 'Tagchat', 'facilisi cras');
insert into tipo_departamento (id, nome, descricao) values (47, 'Riffpedia', 'nunc');
insert into tipo_departamento (id, nome, descricao) values (48, 'Abatz', 'vestibulum rutrum');
insert into tipo_departamento (id, nome, descricao) values (49, 'Trudoo', 'congue');
insert into tipo_departamento (id, nome, descricao) values (50, 'Twitternation', 'fermentum donec');
insert into tipo_departamento (id, nome, descricao) values (51, 'Ozu', 'quisque ut');
insert into tipo_departamento (id, nome, descricao) values (52, 'Vimbo', 'odio');
insert into tipo_departamento (id, nome, descricao) values (53, 'Devshare', 'lorem');
insert into tipo_departamento (id, nome, descricao) values (54, 'Centimia', 'quam pede');
insert into tipo_departamento (id, nome, descricao) values (55, 'Meevee', 'ut');
insert into tipo_departamento (id, nome, descricao) values (56, 'Meembee', 'augue vel');
insert into tipo_departamento (id, nome, descricao) values (57, 'Zoonoodle', 'imperdiet');
insert into tipo_departamento (id, nome, descricao) values (58, 'Dynava', 'velit vivamus');
insert into tipo_departamento (id, nome, descricao) values (59, 'Demivee', 'urna');
insert into tipo_departamento (id, nome, descricao) values (60, 'Shuffletag', 'integer');
insert into tipo_departamento (id, nome, descricao) values (61, 'Yata', 'eget');
insert into tipo_departamento (id, nome, descricao) values (62, 'Kayveo', 'sapien dignissim');
insert into tipo_departamento (id, nome, descricao) values (63, 'Tazz', 'sem');
insert into tipo_departamento (id, nome, descricao) values (64, 'Jabbertype', 'orci');
insert into tipo_departamento (id, nome, descricao) values (65, 'Gevee', 'convallis duis');
insert into tipo_departamento (id, nome, descricao) values (66, 'Skaboo', 'sapien');
insert into tipo_departamento (id, nome, descricao) values (67, 'Dablist', 'pulvinar lobortis');
insert into tipo_departamento (id, nome, descricao) values (68, 'Meemm', 'interdum');
insert into tipo_departamento (id, nome, descricao) values (69, 'Meembee', 'nonummy');
insert into tipo_departamento (id, nome, descricao) values (70, 'Blogtag', 'vivamus vestibulum');
insert into tipo_departamento (id, nome, descricao) values (71, 'Dynabox', 'tortor risus');
insert into tipo_departamento (id, nome, descricao) values (72, 'Voomm', 'vel');
insert into tipo_departamento (id, nome, descricao) values (73, 'Jabbersphere', 'vivamus');
insert into tipo_departamento (id, nome, descricao) values (74, 'Yombu', 'dapibus at');
insert into tipo_departamento (id, nome, descricao) values (75, 'Gabvine', 'eget');
insert into tipo_departamento (id, nome, descricao) values (76, 'Camimbo', 'nulla suscipit');
insert into tipo_departamento (id, nome, descricao) values (77, 'Wordtune', 'et');
insert into tipo_departamento (id, nome, descricao) values (78, 'Quimba', 'interdum');
insert into tipo_departamento (id, nome, descricao) values (79, 'Tagcat', 'vitae');
insert into tipo_departamento (id, nome, descricao) values (80, 'Tambee', 'platea dictumst');
insert into tipo_departamento (id, nome, descricao) values (81, 'Fliptune', 'mi');
insert into tipo_departamento (id, nome, descricao) values (82, 'Skimia', 'morbi');
insert into tipo_departamento (id, nome, descricao) values (83, 'Meedoo', 'nullam varius');
insert into tipo_departamento (id, nome, descricao) values (84, 'Izio', 'consectetuer adipiscing');
insert into tipo_departamento (id, nome, descricao) values (85, 'Mynte', 'elit');
insert into tipo_departamento (id, nome, descricao) values (86, 'Photobug', 'arcu adipiscing');
insert into tipo_departamento (id, nome, descricao) values (87, 'Flashset', 'duis');
insert into tipo_departamento (id, nome, descricao) values (88, 'Eayo', 'non velit');
insert into tipo_departamento (id, nome, descricao) values (89, 'Blogtags', 'pellentesque viverra');
insert into tipo_departamento (id, nome, descricao) values (90, 'Yodoo', 'congue');
insert into tipo_departamento (id, nome, descricao) values (91, 'Flashpoint', 'habitasse');
insert into tipo_departamento (id, nome, descricao) values (92, 'Demivee', 'maecenas');
insert into tipo_departamento (id, nome, descricao) values (93, 'Zooxo', 'ac');
insert into tipo_departamento (id, nome, descricao) values (94, 'Cogidoo', 'sapien');
insert into tipo_departamento (id, nome, descricao) values (95, 'Browsetype', 'rutrum neque');
insert into tipo_departamento (id, nome, descricao) values (96, 'Linkbridge', 'dolor');
insert into tipo_departamento (id, nome, descricao) values (97, 'Skinder', 'bibendum morbi');
insert into tipo_departamento (id, nome, descricao) values (98, 'Aibox', 'etiam');
insert into tipo_departamento (id, nome, descricao) values (99, 'Divape', 'habitasse');
insert into tipo_departamento (id, nome, descricao) values (100, 'Flipstorm', 'ante');
insert into tipo_departamento (id, nome, descricao) values (101, 'Buzzster', 'sit');
insert into tipo_departamento (id, nome, descricao) values (102, 'Skipfire', 'mi sit');
insert into tipo_departamento (id, nome, descricao) values (103, 'Yabox', 'diam neque');
insert into tipo_departamento (id, nome, descricao) values (104, 'Skinte', 'nunc');
insert into tipo_departamento (id, nome, descricao) values (105, 'Skibox', 'nonummy');
insert into tipo_departamento (id, nome, descricao) values (106, 'Jayo', 'pede libero');
insert into tipo_departamento (id, nome, descricao) values (107, 'Gabtype', 'purus sit');
insert into tipo_departamento (id, nome, descricao) values (108, 'Skaboo', 'donec vitae');
insert into tipo_departamento (id, nome, descricao) values (109, 'Quimba', 'maecenas');
insert into tipo_departamento (id, nome, descricao) values (110, 'LiveZ', 'nibh quisque');
insert into tipo_departamento (id, nome, descricao) values (111, 'Roombo', 'quam');
insert into tipo_departamento (id, nome, descricao) values (112, 'Yata', 'metus');
insert into tipo_departamento (id, nome, descricao) values (113, 'Voolia', 'imperdiet et');
insert into tipo_departamento (id, nome, descricao) values (114, 'Realpoint', 'id');
insert into tipo_departamento (id, nome, descricao) values (115, 'Feedmix', 'ut');
insert into tipo_departamento (id, nome, descricao) values (116, 'Youopia', 'quis');
insert into tipo_departamento (id, nome, descricao) values (117, 'Roombo', 'vulputate ut');
insert into tipo_departamento (id, nome, descricao) values (118, 'Jaxworks', 'amet');
insert into tipo_departamento (id, nome, descricao) values (119, 'Eazzy', 'fermentum justo');
insert into tipo_departamento (id, nome, descricao) values (120, 'Skiptube', 'est donec');
insert into tipo_departamento (id, nome, descricao) values (121, 'Skaboo', 'duis');
insert into tipo_departamento (id, nome, descricao) values (122, 'Jabbertype', 'aliquam');
insert into tipo_departamento (id, nome, descricao) values (123, 'Zoombeat', 'mauris sit');
insert into tipo_departamento (id, nome, descricao) values (124, 'Jaxnation', 'mattis nibh');
insert into tipo_departamento (id, nome, descricao) values (125, 'Feedfish', 'elit proin');
insert into tipo_departamento (id, nome, descricao) values (126, 'Photolist', 'elit');
insert into tipo_departamento (id, nome, descricao) values (127, 'Tagpad', 'erat volutpat');
insert into tipo_departamento (id, nome, descricao) values (128, 'Trudoo', 'semper interdum');
insert into tipo_departamento (id, nome, descricao) values (129, 'Thoughtstorm', 'sagittis sapien');
insert into tipo_departamento (id, nome, descricao) values (130, 'Meembee', 'ante');
insert into tipo_departamento (id, nome, descricao) values (131, 'Zooveo', 'lorem id');
insert into tipo_departamento (id, nome, descricao) values (132, 'Skynoodle', 'at');
insert into tipo_departamento (id, nome, descricao) values (133, 'Ntags', 'aenean sit');
insert into tipo_departamento (id, nome, descricao) values (134, 'Bluezoom', 'faucibus');
insert into tipo_departamento (id, nome, descricao) values (135, 'Jabberbean', 'viverra');
insert into tipo_departamento (id, nome, descricao) values (136, 'Browsedrive', 'proin at');
insert into tipo_departamento (id, nome, descricao) values (137, 'Edgetag', 'id');
insert into tipo_departamento (id, nome, descricao) values (138, 'Browseblab', 'nisl');
insert into tipo_departamento (id, nome, descricao) values (139, 'Mudo', 'libero');
insert into tipo_departamento (id, nome, descricao) values (140, 'Twinder', 'pellentesque');
insert into tipo_departamento (id, nome, descricao) values (141, 'Tambee', 'eget');
insert into tipo_departamento (id, nome, descricao) values (142, 'Gabspot', 'orci eget');
insert into tipo_departamento (id, nome, descricao) values (143, 'Dynabox', 'integer non');
insert into tipo_departamento (id, nome, descricao) values (144, 'Feednation', 'erat curabitur');
insert into tipo_departamento (id, nome, descricao) values (145, 'Mudo', 'eget vulputate');
insert into tipo_departamento (id, nome, descricao) values (146, 'Skipfire', 'eget massa');
insert into tipo_departamento (id, nome, descricao) values (147, 'Quimm', 'curabitur');
insert into tipo_departamento (id, nome, descricao) values (148, 'Brainverse', 'amet sem');
insert into tipo_departamento (id, nome, descricao) values (149, 'Aimbu', 'nisi');
insert into tipo_departamento (id, nome, descricao) values (150, 'Buzzster', 'vestibulum');
insert into tipo_departamento (id, nome, descricao) values (151, 'Trunyx', 'vulputate');
insert into tipo_departamento (id, nome, descricao) values (152, 'Skiba', 'erat eros');
insert into tipo_departamento (id, nome, descricao) values (153, 'Agimba', 'sagittis sapien');
insert into tipo_departamento (id, nome, descricao) values (154, 'Dabfeed', 'etiam');
insert into tipo_departamento (id, nome, descricao) values (155, 'Skalith', 'in eleifend');
insert into tipo_departamento (id, nome, descricao) values (156, 'Youbridge', 'dapibus');
insert into tipo_departamento (id, nome, descricao) values (157, 'Meetz', 'sapien');
insert into tipo_departamento (id, nome, descricao) values (158, 'Eidel', 'morbi porttitor');
insert into tipo_departamento (id, nome, descricao) values (159, 'Quatz', 'nibh in');
insert into tipo_departamento (id, nome, descricao) values (160, 'Dynazzy', 'quis orci');
insert into tipo_departamento (id, nome, descricao) values (161, 'Yakijo', 'quis tortor');
insert into tipo_departamento (id, nome, descricao) values (162, 'Wordify', 'duis bibendum');
insert into tipo_departamento (id, nome, descricao) values (163, 'Twitterwire', 'quam');
insert into tipo_departamento (id, nome, descricao) values (164, 'Omba', 'rhoncus');
insert into tipo_departamento (id, nome, descricao) values (165, 'Blogpad', 'proin at');
insert into tipo_departamento (id, nome, descricao) values (166, 'Quinu', 'amet');
insert into tipo_departamento (id, nome, descricao) values (167, 'Kwinu', 'eget rutrum');
insert into tipo_departamento (id, nome, descricao) values (168, 'Yoveo', 'in libero');
insert into tipo_departamento (id, nome, descricao) values (169, 'Photofeed', 'venenatis lacinia');
insert into tipo_departamento (id, nome, descricao) values (170, 'Rhyloo', 'pellentesque');
insert into tipo_departamento (id, nome, descricao) values (171, 'Jabbersphere', 'nisl nunc');
insert into tipo_departamento (id, nome, descricao) values (172, 'Brightdog', 'erat quisque');
insert into tipo_departamento (id, nome, descricao) values (173, 'Riffpath', 'felis');
insert into tipo_departamento (id, nome, descricao) values (174, 'Nlounge', 'ipsum primis');
insert into tipo_departamento (id, nome, descricao) values (175, 'Thoughtbridge', 'neque sapien');
insert into tipo_departamento (id, nome, descricao) values (176, 'Yodel', 'fusce');
insert into tipo_departamento (id, nome, descricao) values (177, 'Oyoba', 'est risus');
insert into tipo_departamento (id, nome, descricao) values (178, 'Flipopia', 'purus eu');
insert into tipo_departamento (id, nome, descricao) values (179, 'Viva', 'augue');
insert into tipo_departamento (id, nome, descricao) values (180, 'Camimbo', 'sed interdum');
insert into tipo_departamento (id, nome, descricao) values (181, 'Jaxbean', 'quam nec');
insert into tipo_departamento (id, nome, descricao) values (182, 'Dynabox', 'elementum');
insert into tipo_departamento (id, nome, descricao) values (183, 'Feedmix', 'ut dolor');
insert into tipo_departamento (id, nome, descricao) values (184, 'Yacero', 'duis');
insert into tipo_departamento (id, nome, descricao) values (185, 'Demivee', 'dictumst');
insert into tipo_departamento (id, nome, descricao) values (186, 'Photobean', 'ac');
insert into tipo_departamento (id, nome, descricao) values (187, 'Trilith', 'sit');
insert into tipo_departamento (id, nome, descricao) values (188, 'Zoomlounge', 'sit amet');
insert into tipo_departamento (id, nome, descricao) values (189, 'Jetwire', 'non');
insert into tipo_departamento (id, nome, descricao) values (190, 'Aibox', 'nulla integer');
insert into tipo_departamento (id, nome, descricao) values (191, 'Oozz', 'nullam varius');
insert into tipo_departamento (id, nome, descricao) values (192, 'Realblab', 'quam pharetra');
insert into tipo_departamento (id, nome, descricao) values (193, 'Browseblab', 'sapien');
insert into tipo_departamento (id, nome, descricao) values (194, 'Ooba', 'pede');
insert into tipo_departamento (id, nome, descricao) values (195, 'Bubbletube', 'lorem');
insert into tipo_departamento (id, nome, descricao) values (196, 'Fivebridge', 'in faucibus');
insert into tipo_departamento (id, nome, descricao) values (197, 'Leenti', 'sagittis nam');
insert into tipo_departamento (id, nome, descricao) values (198, 'Eazzy', 'congue etiam');
insert into tipo_departamento (id, nome, descricao) values (199, 'Meevee', 'tempor');
insert into tipo_departamento (id, nome, descricao) values (200, 'Vinder', 'amet');
insert into tipo_departamento (id, nome, descricao) values (201, 'Trunyx', 'nulla sed');
insert into tipo_departamento (id, nome, descricao) values (202, 'Avaveo', 'etiam justo');
insert into tipo_departamento (id, nome, descricao) values (203, 'Brainbox', 'varius');
insert into tipo_departamento (id, nome, descricao) values (204, 'Dazzlesphere', 'non velit');
insert into tipo_departamento (id, nome, descricao) values (205, 'Quaxo', 'libero');
insert into tipo_departamento (id, nome, descricao) values (206, 'Yozio', 'ultrices');
insert into tipo_departamento (id, nome, descricao) values (207, 'Yambee', 'mauris');
insert into tipo_departamento (id, nome, descricao) values (208, 'Rooxo', 'neque aenean');
insert into tipo_departamento (id, nome, descricao) values (209, 'Jaxbean', 'cubilia curae');
insert into tipo_departamento (id, nome, descricao) values (210, 'Babblestorm', 'et');
insert into tipo_departamento (id, nome, descricao) values (211, 'Skilith', 'integer pede');
insert into tipo_departamento (id, nome, descricao) values (212, 'Youspan', 'eleifend');
insert into tipo_departamento (id, nome, descricao) values (213, 'Gabcube', 'faucibus');
insert into tipo_departamento (id, nome, descricao) values (214, 'Jayo', 'nibh');
insert into tipo_departamento (id, nome, descricao) values (215, 'Kaymbo', 'justo');
insert into tipo_departamento (id, nome, descricao) values (216, 'Realpoint', 'est et');
insert into tipo_departamento (id, nome, descricao) values (217, 'Snaptags', 'proin');
insert into tipo_departamento (id, nome, descricao) values (218, 'Izio', 'sit');
insert into tipo_departamento (id, nome, descricao) values (219, 'Zoozzy', 'egestas metus');
insert into tipo_departamento (id, nome, descricao) values (220, 'Meezzy', 'sapien');
insert into tipo_departamento (id, nome, descricao) values (221, 'Fivebridge', 'pulvinar');
insert into tipo_departamento (id, nome, descricao) values (222, 'Yata', 'malesuada in');
insert into tipo_departamento (id, nome, descricao) values (223, 'Wordpedia', 'aliquet');
insert into tipo_departamento (id, nome, descricao) values (224, 'Digitube', 'est quam');
insert into tipo_departamento (id, nome, descricao) values (225, 'Youtags', 'turpis');
insert into tipo_departamento (id, nome, descricao) values (226, 'Jabbercube', 'amet');
insert into tipo_departamento (id, nome, descricao) values (227, 'Browsedrive', 'malesuada');
insert into tipo_departamento (id, nome, descricao) values (228, 'Feednation', 'tellus semper');
insert into tipo_departamento (id, nome, descricao) values (229, 'Devcast', 'quisque ut');
insert into tipo_departamento (id, nome, descricao) values (230, 'Innotype', 'eget');
insert into tipo_departamento (id, nome, descricao) values (231, 'Aimbu', 'dolor sit');
insert into tipo_departamento (id, nome, descricao) values (232, 'Twitterlist', 'mi integer');
insert into tipo_departamento (id, nome, descricao) values (233, 'Wikivu', 'faucibus accumsan');
insert into tipo_departamento (id, nome, descricao) values (234, 'Jaxspan', 'luctus et');
insert into tipo_departamento (id, nome, descricao) values (235, 'Zoonoodle', 'ante');
insert into tipo_departamento (id, nome, descricao) values (236, 'Jetpulse', 'etiam faucibus');
insert into tipo_departamento (id, nome, descricao) values (237, 'Jayo', 'nullam');
insert into tipo_departamento (id, nome, descricao) values (238, 'Quimba', 'felis');
insert into tipo_departamento (id, nome, descricao) values (239, 'Skibox', 'arcu');
insert into tipo_departamento (id, nome, descricao) values (240, 'Yozio', 'dui');
insert into tipo_departamento (id, nome, descricao) values (241, 'Wordware', 'eget');
insert into tipo_departamento (id, nome, descricao) values (242, 'Talane', 'nisi volutpat');
insert into tipo_departamento (id, nome, descricao) values (243, 'Eidel', 'nunc proin');
insert into tipo_departamento (id, nome, descricao) values (244, 'Quinu', 'a');
insert into tipo_departamento (id, nome, descricao) values (245, 'Pixonyx', 'volutpat');
insert into tipo_departamento (id, nome, descricao) values (246, 'Zooxo', 'tempus');
insert into tipo_departamento (id, nome, descricao) values (247, 'Jabbercube', 'lacus at');
insert into tipo_departamento (id, nome, descricao) values (248, 'Zava', 'eros viverra');
insert into tipo_departamento (id, nome, descricao) values (249, 'Zoonder', 'non pretium');
insert into tipo_departamento (id, nome, descricao) values (250, 'Zava', 'elit sodales');
