insert into tipo_espaco (id, nome, permite_aula) values (1, 'odio', 1);
insert into tipo_espaco (id, nome, permite_aula) values (2, 'viverra', 1);
insert into tipo_espaco (id, nome, permite_aula) values (3, 'ullamcorper', 0);
insert into tipo_espaco (id, nome, permite_aula) values (4, 'elementum', 1);
insert into tipo_espaco (id, nome, permite_aula) values (5, 'eros suspendisse', 1);
insert into tipo_espaco (id, nome, permite_aula) values (6, 'sociis', 0);
insert into tipo_espaco (id, nome, permite_aula) values (7, 'lobortis ligula', 0);
insert into tipo_espaco (id, nome, permite_aula) values (8, 'ante vel', 0);
insert into tipo_espaco (id, nome, permite_aula) values (9, 'sed tincidunt', 0);
insert into tipo_espaco (id, nome, permite_aula) values (10, 'ut', 1);
insert into tipo_espaco (id, nome, permite_aula) values (11, 'lacinia', 0);
insert into tipo_espaco (id, nome, permite_aula) values (12, 'in hac', 1);
insert into tipo_espaco (id, nome, permite_aula) values (13, 'ultricies eu', 0);
insert into tipo_espaco (id, nome, permite_aula) values (14, 'praesent id', 1);
insert into tipo_espaco (id, nome, permite_aula) values (15, 'sed', 1);
insert into tipo_espaco (id, nome, permite_aula) values (16, 'ipsum primis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (17, 'eu nibh', 1);
insert into tipo_espaco (id, nome, permite_aula) values (18, 'aenean sit', 0);
insert into tipo_espaco (id, nome, permite_aula) values (19, 'ac nulla', 0);
insert into tipo_espaco (id, nome, permite_aula) values (20, 'amet', 0);
insert into tipo_espaco (id, nome, permite_aula) values (21, 'in', 1);
insert into tipo_espaco (id, nome, permite_aula) values (22, 'convallis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (23, 'elit ac', 1);
insert into tipo_espaco (id, nome, permite_aula) values (24, 'pharetra magna', 0);
insert into tipo_espaco (id, nome, permite_aula) values (25, 'duis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (26, 'ultrices', 1);
insert into tipo_espaco (id, nome, permite_aula) values (27, 'duis consequat', 0);
insert into tipo_espaco (id, nome, permite_aula) values (28, 'etiam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (29, 'erat vestibulum', 1);
insert into tipo_espaco (id, nome, permite_aula) values (30, 'interdum', 1);
insert into tipo_espaco (id, nome, permite_aula) values (31, 'libero', 0);
insert into tipo_espaco (id, nome, permite_aula) values (32, 'malesuada', 0);
insert into tipo_espaco (id, nome, permite_aula) values (33, 'suspendisse accumsan', 1);
insert into tipo_espaco (id, nome, permite_aula) values (34, 'sit amet', 0);
insert into tipo_espaco (id, nome, permite_aula) values (35, 'in', 1);
insert into tipo_espaco (id, nome, permite_aula) values (36, 'nullam porttitor', 0);
insert into tipo_espaco (id, nome, permite_aula) values (37, 'mollis molestie', 1);
insert into tipo_espaco (id, nome, permite_aula) values (38, 'venenatis non', 1);
insert into tipo_espaco (id, nome, permite_aula) values (39, 'amet', 1);
insert into tipo_espaco (id, nome, permite_aula) values (40, 'tristique', 0);
insert into tipo_espaco (id, nome, permite_aula) values (41, 'convallis', 0);
insert into tipo_espaco (id, nome, permite_aula) values (42, 'imperdiet sapien', 1);
insert into tipo_espaco (id, nome, permite_aula) values (43, 'velit', 0);
insert into tipo_espaco (id, nome, permite_aula) values (44, 'iaculis diam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (45, 'tempus sit', 1);
insert into tipo_espaco (id, nome, permite_aula) values (46, 'ultrices', 1);
insert into tipo_espaco (id, nome, permite_aula) values (47, 'curae', 0);
insert into tipo_espaco (id, nome, permite_aula) values (48, 'et magnis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (49, 'vel nulla', 0);
insert into tipo_espaco (id, nome, permite_aula) values (50, 'proin', 0);
insert into tipo_espaco (id, nome, permite_aula) values (51, 'diam id', 0);
insert into tipo_espaco (id, nome, permite_aula) values (52, 'hac', 0);
insert into tipo_espaco (id, nome, permite_aula) values (53, 'in', 1);
insert into tipo_espaco (id, nome, permite_aula) values (54, 'in', 1);
insert into tipo_espaco (id, nome, permite_aula) values (55, 'sagittis sapien', 0);
insert into tipo_espaco (id, nome, permite_aula) values (56, 'lobortis vel', 1);
insert into tipo_espaco (id, nome, permite_aula) values (57, 'mauris sit', 1);
insert into tipo_espaco (id, nome, permite_aula) values (58, 'dignissim vestibulum', 0);
insert into tipo_espaco (id, nome, permite_aula) values (59, 'integer', 1);
insert into tipo_espaco (id, nome, permite_aula) values (60, 'duis consequat', 0);
insert into tipo_espaco (id, nome, permite_aula) values (61, 'sem', 0);
insert into tipo_espaco (id, nome, permite_aula) values (62, 'pede', 0);
insert into tipo_espaco (id, nome, permite_aula) values (63, 'sed nisl', 0);
insert into tipo_espaco (id, nome, permite_aula) values (64, 'quisque id', 0);
insert into tipo_espaco (id, nome, permite_aula) values (65, 'a ipsum', 0);
insert into tipo_espaco (id, nome, permite_aula) values (66, 'diam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (67, 'convallis tortor', 1);
insert into tipo_espaco (id, nome, permite_aula) values (68, 'lectus in', 1);
insert into tipo_espaco (id, nome, permite_aula) values (69, 'suspendisse', 1);
insert into tipo_espaco (id, nome, permite_aula) values (70, 'nec', 1);
insert into tipo_espaco (id, nome, permite_aula) values (71, 'odio', 1);
insert into tipo_espaco (id, nome, permite_aula) values (72, 'sed interdum', 0);
insert into tipo_espaco (id, nome, permite_aula) values (73, 'erat nulla', 1);
insert into tipo_espaco (id, nome, permite_aula) values (74, 'quam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (75, 'tellus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (76, 'nulla elit', 0);
insert into tipo_espaco (id, nome, permite_aula) values (77, 'eros', 0);
insert into tipo_espaco (id, nome, permite_aula) values (78, 'sagittis', 0);
insert into tipo_espaco (id, nome, permite_aula) values (79, 'primis', 0);
insert into tipo_espaco (id, nome, permite_aula) values (80, 'cursus urna', 1);
insert into tipo_espaco (id, nome, permite_aula) values (81, 'donec dapibus', 1);
insert into tipo_espaco (id, nome, permite_aula) values (82, 'tempor', 1);
insert into tipo_espaco (id, nome, permite_aula) values (83, 'fusce', 0);
insert into tipo_espaco (id, nome, permite_aula) values (84, 'nulla', 1);
insert into tipo_espaco (id, nome, permite_aula) values (85, 'risus', 1);
insert into tipo_espaco (id, nome, permite_aula) values (86, 'id ornare', 1);
insert into tipo_espaco (id, nome, permite_aula) values (87, 'volutpat erat', 1);
insert into tipo_espaco (id, nome, permite_aula) values (88, 'ac', 0);
insert into tipo_espaco (id, nome, permite_aula) values (89, 'faucibus orci', 0);
insert into tipo_espaco (id, nome, permite_aula) values (90, 'nisl', 1);
insert into tipo_espaco (id, nome, permite_aula) values (91, 'nec', 1);
insert into tipo_espaco (id, nome, permite_aula) values (92, 'ut', 0);
insert into tipo_espaco (id, nome, permite_aula) values (93, 'maecenas', 0);
insert into tipo_espaco (id, nome, permite_aula) values (94, 'diam neque', 1);
insert into tipo_espaco (id, nome, permite_aula) values (95, 'fusce posuere', 0);
insert into tipo_espaco (id, nome, permite_aula) values (96, 'orci', 1);
insert into tipo_espaco (id, nome, permite_aula) values (97, 'ut', 0);
insert into tipo_espaco (id, nome, permite_aula) values (98, 'orci nullam', 0);
insert into tipo_espaco (id, nome, permite_aula) values (99, 'quam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (100, 'eget nunc', 1);
insert into tipo_espaco (id, nome, permite_aula) values (101, 'interdum', 0);
insert into tipo_espaco (id, nome, permite_aula) values (102, 'duis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (103, 'nulla', 1);
insert into tipo_espaco (id, nome, permite_aula) values (104, 'ultrices', 1);
insert into tipo_espaco (id, nome, permite_aula) values (105, 'dolor', 1);
insert into tipo_espaco (id, nome, permite_aula) values (106, 'duis ac', 1);
insert into tipo_espaco (id, nome, permite_aula) values (107, 'luctus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (108, 'id', 0);
insert into tipo_espaco (id, nome, permite_aula) values (109, 'nisl duis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (110, 'justo nec', 0);
insert into tipo_espaco (id, nome, permite_aula) values (111, 'sed interdum', 1);
insert into tipo_espaco (id, nome, permite_aula) values (112, 'magna bibendum', 0);
insert into tipo_espaco (id, nome, permite_aula) values (113, 'dictumst', 0);
insert into tipo_espaco (id, nome, permite_aula) values (114, 'convallis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (115, 'id', 0);
insert into tipo_espaco (id, nome, permite_aula) values (116, 'in sagittis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (117, 'molestie', 0);
insert into tipo_espaco (id, nome, permite_aula) values (118, 'nec sem', 0);
insert into tipo_espaco (id, nome, permite_aula) values (119, 'integer', 0);
insert into tipo_espaco (id, nome, permite_aula) values (120, 'dolor morbi', 0);
insert into tipo_espaco (id, nome, permite_aula) values (121, 'vel augue', 1);
insert into tipo_espaco (id, nome, permite_aula) values (122, 'cubilia', 1);
insert into tipo_espaco (id, nome, permite_aula) values (123, 'duis ac', 0);
insert into tipo_espaco (id, nome, permite_aula) values (124, 'a', 1);
insert into tipo_espaco (id, nome, permite_aula) values (125, 'sit amet', 0);
insert into tipo_espaco (id, nome, permite_aula) values (126, 'vitae quam', 0);
insert into tipo_espaco (id, nome, permite_aula) values (127, 'morbi', 1);
insert into tipo_espaco (id, nome, permite_aula) values (128, 'etiam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (129, 'in', 0);
insert into tipo_espaco (id, nome, permite_aula) values (130, 'non mattis', 0);
insert into tipo_espaco (id, nome, permite_aula) values (131, 'ultrices aliquet', 0);
insert into tipo_espaco (id, nome, permite_aula) values (132, 'consequat metus', 1);
insert into tipo_espaco (id, nome, permite_aula) values (133, 'at lorem', 1);
insert into tipo_espaco (id, nome, permite_aula) values (134, 'maecenas ut', 1);
insert into tipo_espaco (id, nome, permite_aula) values (135, 'libero', 0);
insert into tipo_espaco (id, nome, permite_aula) values (136, 'donec', 1);
insert into tipo_espaco (id, nome, permite_aula) values (137, 'porta', 1);
insert into tipo_espaco (id, nome, permite_aula) values (138, 'platea dictumst', 0);
insert into tipo_espaco (id, nome, permite_aula) values (139, 'in consequat', 0);
insert into tipo_espaco (id, nome, permite_aula) values (140, 'lectus pellentesque', 1);
insert into tipo_espaco (id, nome, permite_aula) values (141, 'sit', 0);
insert into tipo_espaco (id, nome, permite_aula) values (142, 'nulla', 0);
insert into tipo_espaco (id, nome, permite_aula) values (143, 'quis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (144, 'sed', 1);
insert into tipo_espaco (id, nome, permite_aula) values (145, 'eget', 0);
insert into tipo_espaco (id, nome, permite_aula) values (146, 'fermentum', 0);
insert into tipo_espaco (id, nome, permite_aula) values (147, 'tortor', 1);
insert into tipo_espaco (id, nome, permite_aula) values (148, 'elit', 1);
insert into tipo_espaco (id, nome, permite_aula) values (149, 'cursus', 1);
insert into tipo_espaco (id, nome, permite_aula) values (150, 'tristique', 1);
insert into tipo_espaco (id, nome, permite_aula) values (151, 'vel', 0);
insert into tipo_espaco (id, nome, permite_aula) values (152, 'curae', 1);
insert into tipo_espaco (id, nome, permite_aula) values (153, 'tortor', 1);
insert into tipo_espaco (id, nome, permite_aula) values (154, 'rhoncus aliquet', 0);
insert into tipo_espaco (id, nome, permite_aula) values (155, 'libero', 1);
insert into tipo_espaco (id, nome, permite_aula) values (156, 'fusce', 0);
insert into tipo_espaco (id, nome, permite_aula) values (157, 'felis', 0);
insert into tipo_espaco (id, nome, permite_aula) values (158, 'nam dui', 1);
insert into tipo_espaco (id, nome, permite_aula) values (159, 'aliquam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (160, 'a', 1);
insert into tipo_espaco (id, nome, permite_aula) values (161, 'habitasse', 0);
insert into tipo_espaco (id, nome, permite_aula) values (162, 'massa donec', 0);
insert into tipo_espaco (id, nome, permite_aula) values (163, 'aliquet pulvinar', 1);
insert into tipo_espaco (id, nome, permite_aula) values (164, 'iaculis diam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (165, 'volutpat sapien', 0);
insert into tipo_espaco (id, nome, permite_aula) values (166, 'in', 0);
insert into tipo_espaco (id, nome, permite_aula) values (167, 'vivamus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (168, 'velit donec', 0);
insert into tipo_espaco (id, nome, permite_aula) values (169, 'augue', 0);
insert into tipo_espaco (id, nome, permite_aula) values (170, 'non ligula', 1);
insert into tipo_espaco (id, nome, permite_aula) values (171, 'tortor risus', 1);
insert into tipo_espaco (id, nome, permite_aula) values (172, 'tempus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (173, 'integer aliquet', 1);
insert into tipo_espaco (id, nome, permite_aula) values (174, 'commodo', 1);
insert into tipo_espaco (id, nome, permite_aula) values (175, 'non', 1);
insert into tipo_espaco (id, nome, permite_aula) values (176, 'in purus', 1);
insert into tipo_espaco (id, nome, permite_aula) values (177, 'viverra eget', 0);
insert into tipo_espaco (id, nome, permite_aula) values (178, 'sapien', 1);
insert into tipo_espaco (id, nome, permite_aula) values (179, 'pellentesque', 1);
insert into tipo_espaco (id, nome, permite_aula) values (180, 'justo etiam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (181, 'orci pede', 0);
insert into tipo_espaco (id, nome, permite_aula) values (182, 'non lectus', 1);
insert into tipo_espaco (id, nome, permite_aula) values (183, 'curae duis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (184, 'tellus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (185, 'felis donec', 1);
insert into tipo_espaco (id, nome, permite_aula) values (186, 'in congue', 0);
insert into tipo_espaco (id, nome, permite_aula) values (187, 'dapibus at', 1);
insert into tipo_espaco (id, nome, permite_aula) values (188, 'neque', 1);
insert into tipo_espaco (id, nome, permite_aula) values (189, 'feugiat', 0);
insert into tipo_espaco (id, nome, permite_aula) values (190, 'quis orci', 1);
insert into tipo_espaco (id, nome, permite_aula) values (191, 'sed magna', 1);
insert into tipo_espaco (id, nome, permite_aula) values (192, 'sapien arcu', 0);
insert into tipo_espaco (id, nome, permite_aula) values (193, 'metus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (194, 'elit proin', 1);
insert into tipo_espaco (id, nome, permite_aula) values (195, 'et', 0);
insert into tipo_espaco (id, nome, permite_aula) values (196, 'sapien cum', 1);
insert into tipo_espaco (id, nome, permite_aula) values (197, 'vulputate', 1);
insert into tipo_espaco (id, nome, permite_aula) values (198, 'integer', 0);
insert into tipo_espaco (id, nome, permite_aula) values (199, 'imperdiet nullam', 0);
insert into tipo_espaco (id, nome, permite_aula) values (200, 'morbi a', 0);
insert into tipo_espaco (id, nome, permite_aula) values (201, 'nunc donec', 1);
insert into tipo_espaco (id, nome, permite_aula) values (202, 'nulla', 1);
insert into tipo_espaco (id, nome, permite_aula) values (203, 'in faucibus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (204, 'in', 0);
insert into tipo_espaco (id, nome, permite_aula) values (205, 'accumsan tortor', 0);
insert into tipo_espaco (id, nome, permite_aula) values (206, 'phasellus', 1);
insert into tipo_espaco (id, nome, permite_aula) values (207, 'augue vestibulum', 0);
insert into tipo_espaco (id, nome, permite_aula) values (208, 'amet', 1);
insert into tipo_espaco (id, nome, permite_aula) values (209, 'sed nisl', 1);
insert into tipo_espaco (id, nome, permite_aula) values (210, 'ante', 0);
insert into tipo_espaco (id, nome, permite_aula) values (211, 'vitae quam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (212, 'felis eu', 0);
insert into tipo_espaco (id, nome, permite_aula) values (213, 'morbi vestibulum', 0);
insert into tipo_espaco (id, nome, permite_aula) values (214, 'primis', 1);
insert into tipo_espaco (id, nome, permite_aula) values (215, 'quis turpis', 0);
insert into tipo_espaco (id, nome, permite_aula) values (216, 'consequat nulla', 1);
insert into tipo_espaco (id, nome, permite_aula) values (217, 'pede', 1);
insert into tipo_espaco (id, nome, permite_aula) values (218, 'nisi', 0);
insert into tipo_espaco (id, nome, permite_aula) values (219, 'eget elit', 0);
insert into tipo_espaco (id, nome, permite_aula) values (220, 'in', 0);
insert into tipo_espaco (id, nome, permite_aula) values (221, 'rhoncus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (222, 'justo', 1);
insert into tipo_espaco (id, nome, permite_aula) values (223, 'nisl venenatis', 0);
insert into tipo_espaco (id, nome, permite_aula) values (224, 'feugiat', 0);
insert into tipo_espaco (id, nome, permite_aula) values (225, 'feugiat non', 0);
insert into tipo_espaco (id, nome, permite_aula) values (226, 'tellus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (227, 'eget eros', 0);
insert into tipo_espaco (id, nome, permite_aula) values (228, 'tempus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (229, 'felis sed', 1);
insert into tipo_espaco (id, nome, permite_aula) values (230, 'pede', 0);
insert into tipo_espaco (id, nome, permite_aula) values (231, 'interdum', 1);
insert into tipo_espaco (id, nome, permite_aula) values (232, 'aliquam erat', 1);
insert into tipo_espaco (id, nome, permite_aula) values (233, 'pellentesque at', 1);
insert into tipo_espaco (id, nome, permite_aula) values (234, 'sollicitudin', 1);
insert into tipo_espaco (id, nome, permite_aula) values (235, 'vehicula', 0);
insert into tipo_espaco (id, nome, permite_aula) values (236, 'neque', 0);
insert into tipo_espaco (id, nome, permite_aula) values (237, 'eget massa', 1);
insert into tipo_espaco (id, nome, permite_aula) values (238, 'faucibus cursus', 1);
insert into tipo_espaco (id, nome, permite_aula) values (239, 'fusce', 1);
insert into tipo_espaco (id, nome, permite_aula) values (240, 'et', 1);
insert into tipo_espaco (id, nome, permite_aula) values (241, 'dolor', 1);
insert into tipo_espaco (id, nome, permite_aula) values (242, 'non mattis', 0);
insert into tipo_espaco (id, nome, permite_aula) values (243, 'quam', 1);
insert into tipo_espaco (id, nome, permite_aula) values (244, 'nisl', 1);
insert into tipo_espaco (id, nome, permite_aula) values (245, 'cum', 0);
insert into tipo_espaco (id, nome, permite_aula) values (246, 'et commodo', 1);
insert into tipo_espaco (id, nome, permite_aula) values (247, 'luctus', 0);
insert into tipo_espaco (id, nome, permite_aula) values (248, 'vel augue', 1);
insert into tipo_espaco (id, nome, permite_aula) values (249, 'turpis nec', 1);
insert into tipo_espaco (id, nome, permite_aula) values (250, 'nunc purus', 1);
