insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (1, 'maecenas', 'pellentesque', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (2, 'ipsum', 'duis mattis', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (3, 'vel', 'nulla', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (4, 'in', 'volutpat', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (5, 'arcu', 'duis', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (6, 'montes', 'sed', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (7, 'lacus', 'sed', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (8, 'vestibulum', 'curabitur', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (9, 'vel', 'nisl duis', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (10, 'ut', 'mauris lacinia', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (11, 'in', 'consequat lectus', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (12, 'leo', 'in est', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (13, 'sapien', 'a odio', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (14, 'porttitor', 'sagittis', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (15, 'vestibulum', 'curae', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (16, 'blandit', 'eleifend donec', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (17, 'lacinia', 'id luctus', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (18, 'amet', 'tincidunt', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (19, 'pede', 'luctus et', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (20, 'hendrerit', 'enim leo', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (21, 'praesent', 'consequat', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (22, 'tristique', 'quam', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (23, 'at', 'hendrerit at', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (24, 'non', 'nunc', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (25, 'et', 'vel', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (26, 'congue', 'fusce', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (27, 'suspendisse', 'vivamus', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (28, 'felis', 'curabitur gravida', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (29, 'id', 'a nibh', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (30, 'mauris', 'elementum in', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (31, 'consectetuer', 'pretium quis', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (32, 'lectus', 'eu felis', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (33, 'adipiscing', 'aenean fermentum', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (34, 'diam', 'felis', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (35, 'nullam', 'odio porttitor', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (36, 'sed', 'neque vestibulum', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (37, 'lectus', 'scelerisque', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (38, 'vivamus', 'in felis', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (39, 'erat', 'a', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (40, 'id', 'convallis eget', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (41, 'a', 'accumsan', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (42, 'sapien', 'id lobortis', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (43, 'ut', 'in', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (44, 'quis', 'lobortis', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (45, 'magna', 'pede ac', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (46, 'eu', 'nunc donec', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (47, 'nascetur', 'semper porta', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (48, 'proin', 'libero quis', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (49, 'dis', 'massa', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (50, 'non', 'in', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (51, 'ultrices', 'sapien dignissim', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (52, 'pede', 'tincidunt', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (53, 'ultrices', 'nunc', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (54, 'commodo', 'magnis dis', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (55, 'nulla', 'nullam', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (56, 'suscipit', 'in', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (57, 'mi', 'eu', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (58, 'ac', 'quam fringilla', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (59, 'eget', 'in felis', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (60, 'vestibulum', 'amet nulla', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (61, 'pellentesque', 'quam', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (62, 'morbi', 'rutrum at', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (63, 'eros', 'vulputate ut', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (64, 'erat', 'eget eros', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (65, 'id', 'pede', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (66, 'pellentesque', 'maecenas', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (67, 'nulla', 'feugiat', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (68, 'in', 'eu', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (69, 'eget', 'at', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (70, 'tristique', 'nunc', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (71, 'id', 'sed tincidunt', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (72, 'morbi', 'eget semper', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (73, 'justo', 'lacus at', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (74, 'curabitur', 'purus aliquet', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (75, 'montes', 'commodo', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (76, 'eget', 'quam', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (77, 'eget', 'condimentum neque', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (78, 'maecenas', 'platea', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (79, 'felis', 'nec', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (80, 'nulla', 'id', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (81, 'orci', 'sapien', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (82, 'urna', 'non', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (83, 'vitae', 'vivamus', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (84, 'duis', 'magnis', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (85, 'in', 'a', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (86, 'quam', 'potenti in', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (87, 'aliquam', 'justo aliquam', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (88, 'posuere', 'aenean auctor', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (89, 'consequat', 'arcu', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (90, 'pellentesque', 'odio donec', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (91, 'curabitur', 'leo', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (92, 'nulla', 'etiam pretium', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (93, 'est', 'nam', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (94, 'praesent', 'eget', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (95, 'tortor', 'euismod scelerisque', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (96, 'habitasse', 'at lorem', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (97, 'odio', 'vulputate justo', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (98, 'vulputate', 'amet sem', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (99, 'non', 'congue', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (100, 'magnis', 'lorem id', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (101, 'nisi', 'vel augue', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (102, 'vitae', 'non', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (103, 'purus', 'ac', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (104, 'eu', 'ut', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (105, 'rhoncus', 'a', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (106, 'vitae', 'tristique tortor', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (107, 'bibendum', 'tortor', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (108, 'blandit', 'donec', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (109, 'ultrices', 'orci pede', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (110, 'odio', 'sed', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (111, 'interdum', 'posuere nonummy', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (112, 'sit', 'dapibus nulla', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (113, 'maecenas', 'mauris sit', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (114, 'sapien', 'vel', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (115, 'rutrum', 'turpis sed', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (116, 'metus', 'nisi', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (117, 'fringilla', 'nullam', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (118, 'aenean', 'lectus', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (119, 'pulvinar', 'suscipit', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (120, 'justo', 'luctus', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (121, 'dictumst', 'sapien placerat', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (122, 'dapibus', 'lacus', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (123, 'porttitor', 'nonummy', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (124, 'iaculis', 'nibh ligula', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (125, 'magnis', 'felis ut', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (126, 'et', 'luctus', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (127, 'justo', 'arcu', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (128, 'volutpat', 'nam dui', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (129, 'vitae', 'magna', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (130, 'amet', 'et', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (131, 'dapibus', 'mattis', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (132, 'erat', 'sed', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (133, 'aliquam', 'turpis', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (134, 'donec', 'nisi volutpat', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (135, 'odio', 'ut', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (136, 'viverra', 'ridiculus mus', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (137, 'non', 'mi', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (138, 'vel', 'nec', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (139, 'sociis', 'lacus curabitur', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (140, 'mus', 'sed interdum', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (141, 'morbi', 'felis ut', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (142, 'nec', 'enim leo', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (143, 'duis', 'a feugiat', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (144, 'sollicitudin', 'consequat', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (145, 'duis', 'magnis', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (146, 'enim', 'ut', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (147, 'id', 'volutpat dui', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (148, 'nisl', 'sagittis', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (149, 'tellus', 'pede', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (150, 'turpis', 'turpis', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (151, 'in', 'praesent', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (152, 'vel', 'et', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (153, 'in', 'pede', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (154, 'quis', 'consequat dui', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (155, 'sed', 'elit', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (156, 'potenti', 'posuere', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (157, 'vulputate', 'odio', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (158, 'rutrum', 'neque', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (159, 'lacus', 'magna', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (160, 'at', 'turpis', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (161, 'praesent', 'quis', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (162, 'suspendisse', 'sagittis', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (163, 'integer', 'vestibulum', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (164, 'ultrices', 'pellentesque', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (165, 'faucibus', 'in faucibus', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (166, 'ac', 'sed', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (167, 'porttitor', 'nulla neque', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (168, 'lectus', 'suspendisse', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (169, 'rutrum', 'nec', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (170, 'ornare', 'libero', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (171, 'sapien', 'a odio', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (172, 'bibendum', 'mauris lacinia', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (173, 'tincidunt', 'dictumst morbi', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (174, 'tincidunt', 'sollicitudin', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (175, 'nisl', 'sit amet', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (176, 'tristique', 'dui nec', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (177, 'at', 'nunc purus', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (178, 'consectetuer', 'curabitur at', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (179, 'at', 'penatibus et', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (180, 'odio', 'consequat ut', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (181, 'blandit', 'purus', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (182, 'est', 'pellentesque', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (183, 'tortor', 'duis', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (184, 'integer', 'rutrum rutrum', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (185, 'at', 'natoque penatibus', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (186, 'ultrices', 'nulla', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (187, 'sem', 'volutpat in', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (188, 'rhoncus', 'in purus', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (189, 'eget', 'quam pede', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (190, 'vestibulum', 'ante', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (191, 'tortor', 'in hac', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (192, 'aliquet', 'id', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (193, 'suscipit', 'in', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (194, 'nisi', 'lobortis', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (195, 'tortor', 'vivamus', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (196, 'facilisi', 'dui luctus', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (197, 'tortor', 'elementum', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (198, 'augue', 'faucibus accumsan', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (199, 'dapibus', 'placerat', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (200, 'velit', 'malesuada', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (201, 'lectus', 'amet', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (202, 'platea', 'nunc', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (203, 'morbi', 'nibh in', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (204, 'leo', 'eget eleifend', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (205, 'viverra', 'cursus', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (206, 'platea', 'iaculis congue', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (207, 'curabitur', 'vitae', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (208, 'dictumst', 'libero', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (209, 'in', 'posuere cubilia', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (210, 'ut', 'leo', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (211, 'vivamus', 'a', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (212, 'orci', 'id', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (213, 'vestibulum', 'nulla', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (214, 'ac', 'nibh', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (215, 'at', 'quis', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (216, 'praesent', 'vel', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (217, 'in', 'sapien', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (218, 'nisi', 'amet nulla', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (219, 'pellentesque', 'vivamus', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (220, 'quam', 'eu felis', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (221, 'et', 'parturient montes', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (222, 'elit', 'vel', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (223, 'turpis', 'turpis', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (224, 'elementum', 'curabitur at', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (225, 'vestibulum', 'aenean lectus', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (226, 'facilisi', 'interdum', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (227, 'tempus', 'curabitur convallis', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (228, 'volutpat', 'semper', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (229, 'ut', 'eget tempus', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (230, 'ut', 'leo', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (231, 'enim', 'fusce consequat', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (232, 'mus', 'id', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (233, 'feugiat', 'magna at', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (234, 'semper', 'id lobortis', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (235, 'lobortis', 'pellentesque', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (236, 'ligula', 'morbi non', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (237, 'volutpat', 'non', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (238, 'eu', 'luctus', 0, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (239, 'ut', 'ut', 0, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (240, 'in', 'morbi', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (241, 'pellentesque', 'nulla', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (242, 'ultrices', 'turpis', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (243, 'ipsum', 'justo in', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (244, 'eget', 'cursus id', 0, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (245, 'at', 'aenean', 1, 0, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (246, 'neque', 'tempus', 1, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (247, 'dolor', 'non sodales', 0, 1, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (248, 'dictumst', 'enim', 1, 1, 0);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (249, 'proin', 'gravida', 1, 0, 1);
insert into tipo_avaliacao (id, nome, descricao, requer_entrega, permite_grupo, permite_filhos) values (250, 'a', 'porttitor', 0, 0, 0);
