insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (1, 1, 'platea dictumst');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (2, 2, 'iaculis justo');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (3, 3, 'nunc rhoncus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (4, 4, 'curae');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (5, 5, 'libero');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (6, 6, 'quam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (7, 7, 'sodales sed');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (8, 8, 'parturient montes');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (9, 9, 'diam neque');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (10, 10, 'molestie sed');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (11, 11, 'quam nec');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (12, 12, 'tellus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (13, 13, 'est congue');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (14, 14, 'morbi');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (15, 15, 'parturient montes');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (16, 16, 'vestibulum sit');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (17, 17, 'donec');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (18, 18, 'rutrum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (19, 19, 'feugiat');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (20, 20, 'proin risus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (21, 21, 'nibh ligula');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (22, 22, 'arcu libero');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (23, 23, 'mauris');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (24, 24, 'sapien');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (25, 25, 'tincidunt');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (26, 26, 'a feugiat');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (27, 27, 'faucibus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (28, 28, 'donec');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (29, 29, 'purus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (30, 30, 'mattis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (31, 31, 'pellentesque');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (32, 32, 'dis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (33, 33, 'justo sollicitudin');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (34, 34, 'nibh');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (35, 35, 'at');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (36, 36, 'curabitur at');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (37, 37, 'pellentesque ultrices');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (38, 38, 'erat');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (39, 39, 'sollicitudin');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (40, 40, 'magna');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (41, 41, 'eleifend pede');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (42, 42, 'suspendisse');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (43, 43, 'tincidunt');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (44, 44, 'nec nisi');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (45, 45, 'odio');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (46, 46, 'quisque erat');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (47, 47, 'quis turpis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (48, 48, 'orci');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (49, 49, 'faucibus accumsan');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (50, 50, 'quis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (51, 51, 'cursus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (52, 52, 'vestibulum aliquet');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (53, 53, 'at diam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (54, 54, 'turpis elementum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (55, 55, 'potenti cras');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (56, 56, 'lacinia');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (57, 57, 'tempus vel');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (58, 58, 'quis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (59, 59, 'tortor id');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (60, 60, 'sit');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (61, 61, 'sed');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (62, 62, 'dui');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (63, 63, 'nunc rhoncus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (64, 64, 'interdum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (65, 65, 'mollis molestie');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (66, 66, 'phasellus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (67, 67, 'ullamcorper');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (68, 68, 'nulla justo');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (69, 69, 'proin');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (70, 70, 'ac diam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (71, 71, 'eu sapien');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (72, 72, 'faucibus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (73, 73, 'aliquam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (74, 74, 'felis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (75, 75, 'vel');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (76, 76, 'sapien dignissim');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (77, 77, 'adipiscing');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (78, 78, 'a');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (79, 79, 'pellentesque quisque');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (80, 80, 'nisl venenatis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (81, 81, 'tempus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (82, 82, 'varius integer');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (83, 83, 'quis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (84, 84, 'fermentum justo');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (85, 85, 'fringilla rhoncus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (86, 86, 'sit amet');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (87, 87, 'ligula nec');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (88, 88, 'congue elementum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (89, 89, 'sit');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (90, 90, 'ac');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (91, 91, 'scelerisque mauris');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (92, 92, 'libero non');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (93, 93, 'potenti in');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (94, 94, 'luctus ultricies');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (95, 95, 'venenatis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (96, 96, 'ac nulla');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (97, 97, 'turpis a');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (98, 98, 'libero');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (99, 99, 'quis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (100, 100, 'pellentesque eget');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (101, 101, 'euismod');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (102, 102, 'etiam pretium');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (103, 103, 'blandit non');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (104, 104, 'sem');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (105, 105, 'a');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (106, 106, 'est');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (107, 107, 'tortor');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (108, 108, 'phasellus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (109, 109, 'mauris');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (110, 110, 'nisl duis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (111, 111, 'fermentum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (112, 112, 'dolor sit');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (113, 113, 'cursus id');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (114, 114, 'tortor');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (115, 115, 'iaculis justo');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (116, 116, 'sem');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (117, 117, 'diam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (118, 118, 'potenti nullam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (119, 119, 'ac enim');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (120, 120, 'ultrices');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (121, 121, 'dolor vel');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (122, 122, 'ac tellus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (123, 123, 'luctus ultricies');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (124, 124, 'sit amet');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (125, 125, 'eu felis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (126, 126, 'est');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (127, 127, 'purus sit');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (128, 128, 'risus praesent');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (129, 129, 'dignissim vestibulum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (130, 130, 'eleifend luctus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (131, 131, 'convallis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (132, 132, 'neque');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (133, 133, 'nam nulla');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (134, 134, 'elementum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (135, 135, 'eu');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (136, 136, 'quis libero');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (137, 137, 'duis faucibus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (138, 138, 'nam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (139, 139, 'praesent');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (140, 140, 'ultrices posuere');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (141, 141, 'augue a');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (142, 142, 'vivamus in');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (143, 143, 'posuere cubilia');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (144, 144, 'pede');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (145, 145, 'cubilia curae');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (146, 146, 'dapibus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (147, 147, 'ridiculus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (148, 148, 'purus phasellus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (149, 149, 'suscipit nulla');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (150, 150, 'lorem vitae');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (151, 151, 'cubilia curae');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (152, 152, 'morbi');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (153, 153, 'vulputate');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (154, 154, 'orci');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (155, 155, 'elementum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (156, 156, 'ridiculus mus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (157, 157, 'elit ac');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (158, 158, 'turpis a');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (159, 159, 'blandit lacinia');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (160, 160, 'non ligula');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (161, 161, 'commodo vulputate');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (162, 162, 'augue');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (163, 163, 'scelerisque mauris');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (164, 164, 'ultrices');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (165, 165, 'viverra');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (166, 166, 'morbi');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (167, 167, 'diam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (168, 168, 'suspendisse');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (169, 169, 'pulvinar lobortis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (170, 170, 'rutrum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (171, 171, 'ante ipsum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (172, 172, 'penatibus et');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (173, 173, 'ultrices');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (174, 174, 'iaculis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (175, 175, 'suspendisse');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (176, 176, 'convallis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (177, 177, 'nulla');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (178, 178, 'erat quisque');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (179, 179, 'turpis enim');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (180, 180, 'praesent blandit');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (181, 181, 'amet nunc');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (182, 182, 'ultrices');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (183, 183, 'sed');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (184, 184, 'urna ut');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (185, 185, 'id');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (186, 186, 'sapien');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (187, 187, 'etiam justo');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (188, 188, 'convallis eget');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (189, 189, 'mus etiam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (190, 190, 'convallis duis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (191, 191, 'leo rhoncus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (192, 192, 'auctor');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (193, 193, 'eget');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (194, 194, 'quisque');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (195, 195, 'nisl duis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (196, 196, 'ante ipsum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (197, 197, 'orci vehicula');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (198, 198, 'odio');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (199, 199, 'ante vel');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (200, 200, 'eget nunc');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (201, 201, 'id');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (202, 202, 'libero convallis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (203, 203, 'magna bibendum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (204, 204, 'quam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (205, 205, 'non');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (206, 206, 'lectus in');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (207, 207, 'id');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (208, 208, 'interdum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (209, 209, 'phasellus in');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (210, 210, 'nam tristique');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (211, 211, 'lacinia aenean');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (212, 212, 'odio elementum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (213, 213, 'sem');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (214, 214, 'at vulputate');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (215, 215, 'platea dictumst');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (216, 216, 'cras');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (217, 217, 'sed ante');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (218, 218, 'condimentum id');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (219, 219, 'sagittis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (220, 220, 'libero nullam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (221, 221, 'sit');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (222, 222, 'in');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (223, 223, 'maecenas');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (224, 224, 'condimentum id');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (225, 225, 'tincidunt');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (226, 226, 'suspendisse ornare');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (227, 227, 'consectetuer eget');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (228, 228, 'pellentesque');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (229, 229, 'aliquam');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (230, 230, 'ipsum');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (231, 231, 'at');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (232, 232, 'sociis natoque');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (233, 233, 'porttitor');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (234, 234, 'vivamus metus');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (235, 235, 'at');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (236, 236, 'vestibulum sagittis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (237, 237, 'eros');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (238, 238, 'erat quisque');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (239, 239, 'nulla');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (240, 240, 'turpis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (241, 241, 'nam dui');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (242, 242, 'quis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (243, 243, 'cursus urna');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (244, 244, 'massa quis');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (245, 245, 'massa');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (246, 246, 'egestas');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (247, 247, 'maecenas ut');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (248, 248, 'tellus nisi');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (249, 249, 'tortor');
insert into uc_docente (unidade_curricular_id, docente_id, funcao) values (250, 250, 'sapien urna');
