-- =============================================================================
-- 10. PACOTE DE CONSTANTES E PARÂMETROS DE NEGÓCIO
-- =============================================================================

CREATE OR REPLACE PACKAGE PKG_CONSTANTES IS
    -- Parâmetros de Rigor
    FUNCTION VALIDACAO_RIGOROSA_NIF RETURN BOOLEAN;
    FUNCTION VALIDACAO_RIGOROSA_CC RETURN BOOLEAN;

    -- Outras Constantes
    FUNCTION TAXA_MULTA_ATRASO RETURN NUMBER;
    FUNCTION LIMITE_HORAS_DIARIAS_DOCENTE RETURN NUMBER;
    FUNCTION NOTA_APROVACAO RETURN NUMBER;
    FUNCTION NOTA_MINIMA RETURN NUMBER;
    FUNCTION NOTA_MAXIMA RETURN NUMBER;
    FUNCTION LIMITE_ECTS_ANUAL RETURN NUMBER;
END PKG_CONSTANTES;
/

CREATE OR REPLACE PACKAGE BODY PKG_CONSTANTES IS
    -- Altere para FALSE se quiser desativar a matemática do NIF
    FUNCTION VALIDACAO_RIGOROSA_NIF RETURN BOOLEAN IS BEGIN RETURN TRUE; END;

    -- Altere para FALSE se quiser desativar a matemática do CC
    FUNCTION VALIDACAO_RIGOROSA_CC RETURN BOOLEAN IS BEGIN RETURN TRUE; END;

    FUNCTION TAXA_MULTA_ATRASO RETURN NUMBER IS BEGIN RETURN 0.10; END;
    FUNCTION LIMITE_HORAS_DIARIAS_DOCENTE RETURN NUMBER IS BEGIN RETURN 8; END;
    FUNCTION NOTA_APROVACAO RETURN NUMBER IS BEGIN RETURN 9.5; END;
    FUNCTION NOTA_MINIMA RETURN NUMBER IS BEGIN RETURN 0; END;
    FUNCTION NOTA_MAXIMA RETURN NUMBER IS BEGIN RETURN 20; END;

    FUNCTION LIMITE_ECTS_ANUAL RETURN NUMBER IS 
    BEGIN 
        RETURN 60; 
    END;

END PKG_CONSTANTES;
/