-- =============================================================================
-- 10. PACOTE DE CONSTANTES E PARÂMETROS DE NEGÓCIO
-- =============================================================================

CREATE OR REPLACE PACKAGE PKG_CONSTANTES IS
    FUNCTION TAXA_MULTA_ATRASO RETURN NUMBER;
    FUNCTION LIMITE_HORAS_DIARIAS_DOCENTE RETURN NUMBER;
    FUNCTION NOTA_APROVACAO RETURN NUMBER;
    FUNCTION NOTA_MINIMA RETURN NUMBER;
    FUNCTION NOTA_MAXIMA RETURN NUMBER;
    FUNCTION LIMITE_ECTS_ANUAL(p_curso_id IN NUMBER DEFAULT NULL) RETURN NUMBER;
    
    -- ESTADOS DE MATRÍCULA
    FUNCTION EST_MATRICULA_CONCLUIDA RETURN NUMBER; -- ID para 'Concluída'
END PKG_CONSTANTES;
/

CREATE OR REPLACE PACKAGE BODY PKG_CONSTANTES IS
    FUNCTION TAXA_MULTA_ATRASO RETURN NUMBER IS BEGIN RETURN 0.10; END;
    FUNCTION LIMITE_HORAS_DIARIAS_DOCENTE RETURN NUMBER IS BEGIN RETURN 8; END;
    FUNCTION NOTA_APROVACAO RETURN NUMBER IS BEGIN RETURN 9.5; END;
    FUNCTION NOTA_MINIMA RETURN NUMBER IS BEGIN RETURN 0; END;
    FUNCTION NOTA_MAXIMA RETURN NUMBER IS BEGIN RETURN 20; END;
    FUNCTION LIMITE_ECTS_ANUAL(p_curso_id IN NUMBER DEFAULT NULL) RETURN NUMBER IS 
    BEGIN IF p_curso_id = 1 THEN RETURN 60; END IF; RETURN 72; END;

    -- Assume-se que no DDL o ID 3 é 'Concluída'
    FUNCTION EST_MATRICULA_CONCLUIDA RETURN NUMBER IS BEGIN RETURN 3; END;
END PKG_CONSTANTES;
/
