-- =============================================================================
-- 14. TRIGGERS DE INTERCEPTAÇÃO DE DELETE
-- Integração direta com PKG_GESTAO_DADOS baseada na estrutura da tabela.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 14.1. TABELAS COM CHAVE PRIMÁRIA SIMPLES (ID) -> PRC_REMOVER
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_DEL_AULA BEFORE DELETE ON aula FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('AULA', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_AVALIACAO BEFORE DELETE ON avaliacao FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('AVALIACAO', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_CURSO BEFORE DELETE ON curso FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('CURSO', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_DOCENTE BEFORE DELETE ON docente FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('DOCENTE', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_ENTREGA BEFORE DELETE ON entrega FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('ENTREGA', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_ESTUDANTE BEFORE DELETE ON estudante FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('ESTUDANTE', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_FICHEIRO_ENTREGA BEFORE DELETE ON ficheiro_entrega FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('FICHEIRO_ENTREGA', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_FICHEIRO_RECURSO BEFORE DELETE ON ficheiro_recurso FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('FICHEIRO_RECURSO', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_INSCRICAO BEFORE DELETE ON inscricao FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('INSCRICAO', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_LOG BEFORE DELETE ON log FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('LOG', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_MATRICULA BEFORE DELETE ON matricula FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('MATRICULA', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_PARCELA_PROPINA BEFORE DELETE ON parcela_propina FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('PARCELA_PROPINA', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_RECURSO BEFORE DELETE ON recurso FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('RECURSO', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_SALA BEFORE DELETE ON sala FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('SALA', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_TIPO_AULA BEFORE DELETE ON tipo_aula FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('TIPO_AULA', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_TIPO_AVALIACAO BEFORE DELETE ON tipo_avaliacao FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('TIPO_AVALIACAO', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_TIPO_CURSO BEFORE DELETE ON tipo_curso FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('TIPO_CURSO', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_TURMA BEFORE DELETE ON turma FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('TURMA', :OLD.id); END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_UNIDADE_CURRICULAR BEFORE DELETE ON unidade_curricular FOR EACH ROW 
BEGIN PKG_GESTAO_DADOS.PRC_REMOVER('UNIDADE_CURRICULAR', :OLD.id); END;
/

-- -----------------------------------------------------------------------------
-- 14.2. TABELAS COM CHAVE COMPOSTA -> PRC_REMOVER_RELACAO
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_DEL_ESTUDANTE_ENTREGA BEFORE DELETE ON estudante_entrega FOR EACH ROW 
BEGIN 
    PKG_GESTAO_DADOS.PRC_REMOVER_RELACAO('ESTUDANTE_ENTREGA', :OLD.entrega_id, 'entrega_id', :OLD.inscricao_id, 'inscricao_id'); 
END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_NOTA BEFORE DELETE ON nota FOR EACH ROW 
BEGIN 
    PKG_GESTAO_DADOS.PRC_REMOVER_RELACAO('NOTA', :OLD.avaliacao_id, 'avaliacao_id', :OLD.inscricao_id, 'inscricao_id'); 
END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_PRESENCA BEFORE DELETE ON presenca FOR EACH ROW 
BEGIN 
    PKG_GESTAO_DADOS.PRC_REMOVER_RELACAO('PRESENCA', :OLD.aula_id, 'aula_id', :OLD.inscricao_id, 'inscricao_id'); 
END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_UC_CURSO BEFORE DELETE ON uc_curso FOR EACH ROW 
BEGIN 
    PKG_GESTAO_DADOS.PRC_REMOVER_RELACAO('UC_CURSO', :OLD.curso_id, 'curso_id', :OLD.unidade_curricular_id, 'unidade_curricular_id'); 
END;
/

CREATE OR REPLACE TRIGGER TRG_DEL_UC_DOCENTE BEFORE DELETE ON uc_docente FOR EACH ROW 
BEGIN 
    PKG_GESTAO_DADOS.PRC_REMOVER_RELACAO('UC_DOCENTE', :OLD.unidade_curricular_id, 'unidade_curricular_id', :OLD.docente_id, 'docente_id'); 
END;
/