-- =============================================================================
-- 1. TRIGGERS DE AUTO-INCREMENTO
-- Atribui automaticamente o valor da sequência ao ID se este for nulo.
-- =============================================================================

CREATE OR REPLACE TRIGGER TRG_INC_AULA BEFORE INSERT ON aula FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_AULA.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_AVALIACAO BEFORE INSERT ON avaliacao FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_AVALIACAO.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_CURSO BEFORE INSERT ON curso FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_CURSO.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_DOCENTE BEFORE INSERT ON docente FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_DOCENTE.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_ENTREGA BEFORE INSERT ON entrega FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_ENTREGA.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_ESTUDANTE BEFORE INSERT ON estudante FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_ESTUDANTE.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_FICHEIRO_ENTREGA BEFORE INSERT ON ficheiro_entrega FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_FICHEIRO_ENTREGA.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_FICHEIRO_RECURSO BEFORE INSERT ON ficheiro_recurso FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_FICHEIRO_RECURSO.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_INSCRICAO BEFORE INSERT ON inscricao FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_INSCRICAO.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_LOG BEFORE INSERT ON log FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_LOG.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_MATRICULA BEFORE INSERT ON matricula FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_MATRICULA.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_PARCELA_PROPINA BEFORE INSERT ON parcela_propina FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_PARCELA_PROPINA.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_RECURSO BEFORE INSERT ON recurso FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_RECURSO.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_SALA BEFORE INSERT ON sala FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_SALA.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_TIPO_AULA BEFORE INSERT ON tipo_aula FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_TIPO_AULA.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_TIPO_AVALIACAO BEFORE INSERT ON tipo_avaliacao FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_TIPO_AVALIACAO.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_TIPO_CURSO BEFORE INSERT ON tipo_curso FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_TIPO_CURSO.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_TURMA BEFORE INSERT ON turma FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_TURMA.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_INC_UNIDADE_CURRICULAR BEFORE INSERT ON unidade_curricular FOR EACH ROW
BEGIN IF :NEW.id IS NULL THEN :NEW.id := SEQ_UNIDADE_CURRICULAR.NEXTVAL; END IF; END;
/
