
-- Logs (para cada tabela) (chama PKG_LOG.REGISTAR_DML)

CREATE OR REPLACE TRIGGER TRG_AUDIT_AULA
    AFTER INSERT OR UPDATE OR DELETE ON AULA
    FOR EACH ROW
DECLARE
    v_id VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('AULA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_AVALIACAO
    AFTER INSERT OR UPDATE OR DELETE ON AVALIACAO
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('AVALIACAO', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_CURSO
    AFTER INSERT OR UPDATE OR DELETE ON CURSO
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('CURSO', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_DOCENTE
    AFTER INSERT OR UPDATE OR DELETE ON DOCENTE
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('DOCENTE', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_ENTREGA
    AFTER INSERT OR UPDATE OR DELETE ON ENTREGA
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('ENTREGA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_ESTUDANTE
    AFTER INSERT OR UPDATE OR DELETE ON ESTUDANTE
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('ESTUDANTE', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_ESTUDANTE_ENTREGA
    AFTER INSERT OR UPDATE OR DELETE ON ESTUDANTE_ENTREGA
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ENTREGA_ID) || '-' || TO_CHAR(:OLD.INSCRICAO_ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ENTREGA_ID) || '-' || TO_CHAR(:NEW.INSCRICAO_ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ENTREGA_ID) || '-' || TO_CHAR(:NEW.INSCRICAO_ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('ESTUDANTE_ENTREGA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_FICHEIRO_ENTREGA
    AFTER INSERT OR UPDATE OR DELETE ON FICHEIRO_ENTREGA
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('FICHEIRO_ENTREGA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_FICHEIRO_RECURSO
    AFTER INSERT OR UPDATE OR DELETE ON FICHEIRO_RECURSO
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('FICHEIRO_RECURSO', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_INSCRICAO
    AFTER INSERT OR UPDATE OR DELETE ON INSCRICAO
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('INSCRICAO', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_MATRICULA
    AFTER INSERT OR UPDATE OR DELETE ON MATRICULA
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('MATRICULA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_NOTA
    AFTER INSERT OR UPDATE OR DELETE ON NOTA
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.AVALIACAO_ID) || '-' || TO_CHAR(:OLD.INSCRICAO_ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.AVALIACAO_ID) || '-' || TO_CHAR(:NEW.INSCRICAO_ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.AVALIACAO_ID) || '-' || TO_CHAR(:NEW.INSCRICAO_ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('NOTA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_PARCELA_PROPINA
    AFTER INSERT OR UPDATE OR DELETE ON PARCELA_PROPINA
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('PARCELA_PROPINA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_PRESENCA
    AFTER INSERT OR UPDATE OR DELETE ON PRESENCA
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.AULA_ID) || '-' || TO_CHAR(:OLD.INSCRICAO_ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.AULA_ID) || '-' || TO_CHAR(:NEW.INSCRICAO_ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.AULA_ID) || '-' || TO_CHAR(:NEW.INSCRICAO_ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('PRESENCA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_RECURSO
    AFTER INSERT OR UPDATE OR DELETE ON RECURSO
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('RECURSO', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_SALA
    AFTER INSERT OR UPDATE OR DELETE ON SALA
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('SALA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_TIPO_AULA
    AFTER INSERT OR UPDATE OR DELETE ON TIPO_AULA
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('TIPO_AULA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_TIPO_AVALIACAO
    AFTER INSERT OR UPDATE OR DELETE ON TIPO_AVALIACAO
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('TIPO_AVALIACAO', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_TIPO_CURSO
    AFTER INSERT OR UPDATE OR DELETE ON TIPO_CURSO
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('TIPO_CURSO', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_TURMA
    AFTER INSERT OR UPDATE OR DELETE ON TURMA
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('TURMA', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_UC_CURSO
    AFTER INSERT OR UPDATE OR DELETE ON UC_CURSO
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.CURSO_ID) || '-' || TO_CHAR(:OLD.UNIDADE_CURRICULAR_ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.CURSO_ID) || '-' || TO_CHAR(:NEW.UNIDADE_CURRICULAR_ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.CURSO_ID) || '-' || TO_CHAR(:NEW.UNIDADE_CURRICULAR_ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('UC_CURSO', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_UC_DOCENTE
    AFTER INSERT OR UPDATE OR DELETE ON UC_DOCENTE
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.UNIDADE_CURRICULAR_ID) || '-' || TO_CHAR(:OLD.DOCENTE_ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.UNIDADE_CURRICULAR_ID) || '-' || TO_CHAR(:NEW.DOCENTE_ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.UNIDADE_CURRICULAR_ID) || '-' || TO_CHAR(:NEW.DOCENTE_ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('UC_DOCENTE', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_UNIDADE_CURRICULAR
    AFTER INSERT OR UPDATE OR DELETE ON UNIDADE_CURRICULAR
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('UNIDADE_CURRICULAR', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDIT_FICHEIRO_RECURSO
    AFTER INSERT OR UPDATE OR DELETE ON FICHEIRO_RECURSO
    FOR EACH ROW
DECLARE
    v_id   VARCHAR2(255);
    v_acao VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_id   := TO_CHAR(:OLD.ID);
        v_acao := 'DELETE';
    ELSIF UPDATING THEN
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'UPDATE';
    ELSE
        v_id   := TO_CHAR(:NEW.ID);
        v_acao := 'INSERT';
    END IF;
    PKG_LOG.REGISTAR_DML('FICHEIRO_RECURSO', v_acao, v_id);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
