-- =============================================================================
-- SEQUÊNCIAS PARA AS TABELAS DO PROJETO
-- As sequências começam em 10000 para evitar conflitos com dados de teste existentes.
-- =============================================================================

-- Tabelas Principais
CREATE SEQUENCE SEQ_ESTUDANTE START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DOCENTE START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CURSO START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_UNIDADE_CURRICULAR START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TURMA START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SALA START WITH 10000 INCREMENT BY 1 NOCACHE;

-- Tabelas de Gestão Académica
CREATE SEQUENCE SEQ_MATRICULA START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INSCRICAO START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AULA START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AVALIACAO START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ENTREGA START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECURSO START WITH 10000 INCREMENT BY 1 NOCACHE;

-- Tabelas de Ficheiros
CREATE SEQUENCE SEQ_FICHEIRO_ENTREGA START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FICHEIRO_RECURSO START WITH 10000 INCREMENT BY 1 NOCACHE;

-- Tabelas Financeiras
CREATE SEQUENCE SEQ_PARCELA_PROPINA START WITH 10000 INCREMENT BY 1 NOCACHE;

-- Tabelas de Configuração e Tipos
CREATE SEQUENCE SEQ_TIPO_CURSO START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TIPO_AULA START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TIPO_AVALIACAO START WITH 10000 INCREMENT BY 1 NOCACHE;

-- Auditoria
CREATE SEQUENCE SEQ_LOG START WITH 10000 INCREMENT BY 1 NOCACHE;

-- Nota: Tabelas de junção (estudante_entrega, nota, presenca, uc_curso, uc_docente) 
-- utilizam chaves compostas e não necessitam de sequência própria.
